### ISSUE TITLE
Both downloadables (MSI and ZIP) contain a Trojan

### ISSUE THREAD

**Issue by MattGertz** [TabularEditor/TabularEditor#1000]
!!! Please make sure you're using the latest version of Tabular Editor 2.X before submitting a bug !!!
!!! For Tabular Editor 3 issues, go here -> https://github.com/TabularEditor/TabularEditor3/issues !!!

**Describe the bug**
When downloading either the current MSI or the ZIP, Microsoft Defender identifies a Trojan ("AgentTesla") with a high severity.  This occurred on both 2.16.0 and 2.16.6.

**Comment by MattGertz** [comment]
Groovy, thanks for the very fast response!  Because of company policy (coincidentally, I work at Microsoft), the download is immediately nuked for me, so I will chill out and wait :-).  (I'm working my way through "Expert Data Modeling with PowerBI" which leverages Tabular Editor, hence my running into this.)

**Comment by marcosqlbi** [comment]
I confirm the link in the previous post works, the one on the release page does not.

**Comment by MattGertz** [comment]
@otykier Yes, the links work for me as well (and I am unblocked -- thank you!).  Very peculiar indeed.

**Comment by otykier** [comment]
I think we will close this issue, as there doesn't seem to be anything we can do about it from our end.
