### ISSUE TITLE
Can't open the windows Intergrated login window on version 2.16.7

### ISSUE THREAD

**Issue by Yappawu** [TabularEditor/TabularEditor#1002]
Can't open the windows Intergrated login window on version **2.16.7**. No problem on previous version on the same machine.

**Comment by speedmind** [comment]
Same here, switching to the previous release is the workaround for now for me.

**Comment by otykier** [comment]
Thanks for reporting. It looks like this is an issue with the newest TOM/AMO library (19.42.0.4). I've submitted a bug report to Microsoft. Indeed, downgrading to 2.16.6 would be the workaround for now.

**Comment by otykier** [comment]
**Update:**

Adding the following to the `TabularEditor.exe.config` file in the installation folder should make it work:

```xml
<appSettings>
	<add key="AS_EnforceAdalUsage" value="true" />
</appSettings>
```

The final file should look something like:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<startup>
		<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8"/>
	</startup>
	<appSettings>
		<add key="AS_EnforceAdalUsage" value="true" />
	</appSettings>
</configuration>
```

**Comment by speedmind** [comment]
Thx @otykier for the workaround.

Also very useful to know it's related to TOM API...
