### ISSUE TITLE
 NO attribute group by column

### ISSUE THREAD

**Issue by jiaopengzi** [TabularEditor/TabularEditor#1006]
hi @otykier 

I want to use custom field parameters.

I've seen some friends use tabular Editor with properties like `group by column`

But I have been looking for a long time, but I still can't find the attribute `group by column`

Is there something wrong with my usage? Please give me your guidance.

Thank you very much

---
tabular editor version 2.16.7
power bi version 2.107.683.0 64-bit (2022-7)
---
![image](https://user-images.githubusercontent.com/52224629/179498348-2b444bf3-4f8a-44af-acc5-0859c0aaac53.png)

**Comment by otykier** [comment]
When connected to a model in Power BI Desktop, only a subset of properties are available [for reasons described here](https://docs.tabulareditor.com/te3/desktop-limitations.html). If you want to experiment, you can **allow unsupported Power BI features** under **File > Preferences**.

**Comment by jiaopengzi** [comment]
> When connected to a model in Power BI Desktop, only a subset of properties are available [for reasons described here](https://docs.tabulareditor.com/te3/desktop-limitations.html). If you want to experiment, you can **allow unsupported Power BI features** under **File > Preferences**.

Yes it is!

Thank you very much
