### ISSUE TITLE
Find out if Tabular Editor is connected to Power BI Desktop

### ISSUE THREAD

**Issue by shiyanovg** [TabularEditor/TabularEditor#1010]
**What are you trying to achieve?**
Hello, Daniel!
I'd like to know how can I figure out if TE is connected to Power BI Desktop or not because of scripting.
For example I develop a script that can disable Avalability in MDX or change Data Type of one or more columns, etc.
But not all the actions are suported against Power BI Desktop. So it would be great to have a check as the first step of the C# script.

**What have you tried so far?**
So far I tried to loop through model properties with the following script
[TE_Script_PBI_Test.txt](https://github.com/TabularEditor/TabularEditor/files/9176678/TE_Script_PBI_Test.txt)

But maybe there is an easier way of doing it with the TOM Wrapper?
Thank you in advance!

**Comment by otykier** [comment]
The following script should work with all versions of Tabular Editor:

```csharp
#r "Microsoft.AnalysisServices.Core.dll"

var server = Model.Database.TOMDatabase.Server as Microsoft.AnalysisServices.Tabular.Server;
var isPbiDesktop = server.ServerLocation == Microsoft.AnalysisServices.ServerLocation.OnPremise
    && server.CompatibilityMode == Microsoft.AnalysisServices.CompatibilityMode.PowerBI;
    
if(isPbiDesktop)
    Info("Connected to PBI Desktop");
else
    Info("Not connected to PBI Desktop");
```

**Comment by shiyanovg** [comment]
Thank you, Daniel!
This script works if I'm connected to and instance of PBI Desktop, but it raises an error if metadata is loaded from a file or and folder structure.
For example we use Azure DevOps to publish a model and all the changes are tracked in Git
Is it possible to protect this script to find out if I'm loading model from a file?
Error example below:
![image](https://user-images.githubusercontent.com/94114128/181359400-586073fa-6ee0-4134-91df-2bfa38240a4b.png)

Thank you again for taking this question!
I'm gonna experiment on script development for some of the patterns now with the help of your code.

**Comment by otykier** [comment]
Please modify the code as follows:

```csharp
#r "Microsoft.AnalysisServices.Core.dll"

var server = Model.Database.TOMDatabase.Server as Microsoft.AnalysisServices.Tabular.Server;
var isLoadedFromFile = server == null;
var isPbiDesktop = sever != null && server.ServerLocation == Microsoft.AnalysisServices.ServerLocation.OnPremise
    && server.CompatibilityMode == Microsoft.AnalysisServices.CompatibilityMode.PowerBI;

if(isLoadedFromFile)
    Info("Metadata loaded from file");
else if(isPbiDesktop)
    Info("Connected to PBI Desktop");
else
    Info("Not connected to PBI Desktop");
```

**Comment by shiyanovg** [comment]
Thank you, Daniel!
Found a typo in "isPbiDesktop = sever != null" it should be "isPbiDesktop = **server** != null"
Fixed it right away in the code

Please note that any of the code that I'll publish on Github will have a link to this issue
And also after some development and testing I plan on contributing to the TE Scripts Git Repo.
How can I do so?

**Comment by otykier** [comment]
Hi @shiyanovg - thanks a lot for considering contribution to the TE scripts repo. You can go ahead and submit a PR to that repo any time!
