### ISSUE TITLE
Create 400 similar measure automaticaly

### ISSUE THREAD

**Issue by jeanpascalbi** [TabularEditor/TabularEditor#1014]
Hi All

I need to create 400 dax measure (for 400 of my customers) that looks all the same :

`Price Customer1 = calculate(price,[Customer]="Customer1")`
`Price Customer2 = calculate(price,[Customer]="Customer2")`
`....`

Is there any easy way that tabular editor can help doing that ? 
I would avoid creating this 400 measures manually.

Many thanks for your help

**Comment by otykier** [comment]
This sounds like a job for ... *superhero theme music playing* ... **[Advanced Scripting](https://docs.tabulareditor.com/te2/Advanced-Scripting.html)**!

Assuming you want to create one such measure for each distinct value in the 'Customers'[CustomerID] column, the script should look like this:

```csharp
using System.Data;

// -------------------------

// The table on which new measures are created:
var measureTable = Model.Tables["Customer"];

// Name of new measures to be created, {0} will be replaced by the values read from the table:
var measureName = "Price {0}";

// A DAX expression that returns a one-column table of values which will be used when creating the measures:
var queryDax = "VALUES(Customers[CustomerID])";

// The DAX expression to assign to each measure, {0} will be replaced by the values read from the table:
var measureDax = "CALCULATE([Price], 'Customers'[CustomerID] = \"{0}\")";

// --------------------------

var queryData = EvaluateDax(queryDax) as DataTable;
foreach(DataRow row in queryData.Rows)
{
    var measureValue = row[0].ToString();
    measureTable.AddMeasure(string.Format(measureName, measureValue), string.Format(measureDax, measureValue));
}
```

**Comment by jeanpascalbi** [comment]
Thank you so much, it works and save us a lot of time !

I am now using this 400 DAX measure inside a bar chart (I know it sound surprising to use so many measure, but that was the only solution that me and my team found that match our need).

Our issue now, is that the color of this 400 measure on the bar chart is set randomly, while we would like to define the color of each measure according to a specific color coding. We would like to avoid to do that manually, so we are looking for a solution to do it automaticaly.

From my understanding, tabular editor is not (yet ;) ) able to do that, am i correct ?

![image](https://user-images.githubusercontent.com/110389036/182387248-7ce192d1-22b5-4b39-b651-cf829903c345.png)

**Comment by otykier** [comment]
Unfortunately, Tabular Editor can only be used to edit the data model - it knows nothing about visuals, charts, etc.

**Comment by jeanpascalbi** [comment]
Thank you  so much @otykier  !
