### ISSUE TITLE
Disable check update feature

### ISSUE THREAD

**Issue by yumccarthy** [TabularEditor/TabularEditor#1016]
Is it possible to disable check update feature? We would like to use SCCM to manage the software update instead of user update by themselves.

**Comment by otykier** [comment]
Sure. You can disable update checks under File > Preferences.

**Comment by yumccarthy** [comment]
> 



> Sure. You can disable update checks under File > Preferences.

**Comment by yumccarthy** [comment]
How to make the "check update" button grey out?

**Comment by otykier** [comment]
With the newest version [2.17.0](https://github.com/TabularEditor/TabularEditor/releases/tag/2.17.0), it is now possible to disable certain features, such as the update check, by using [policies](https://docs.tabulareditor.com/common/policies.html).
