### ISSUE TITLE
Azure DevOps Pipeline - MS hosted Agent, downloaded 'TabularEditor.exe' is not recognized

### ISSUE THREAD

**Issue by fausttiger** [TabularEditor/TabularEditor#1018]
!!! For Tabular Editor 3 questions, go here --> https://github.com/TabularEditor/TabularEditor3/issues !!!

**What are you trying to achieve?**
Running the https://tabulareditor.github.io/2019/10/08/DevOps3.html example for a BIM build to AAS... I'm getting the  TabularEditor.exe not found issue.
Have read some similar issues/responses on that article discussion thread and this github... but no solution.

MS Hosted Agent --- Agent Pool = Azure Pipelines,  windows

We have other build and release pipelines running against different resources, but trying to get this to work with tabular editor.

Details below...

thanks!   Tony
----------

====== 
INPUT SCRIPTS

repo root 
C:\Users\.....\source\repos\REPO_NAME\bids\Models\L2L\Model.bim

hence path is  \bids\Models\L2L\Model.bim

------
1) DOWNLOAD SCRIPT Inline

```powershell
# Download URL for Tabular Editor portable:
$TabularEditorUrl = "https://github.com/otykier/TabularEditor/releases/download/2.16.7/TabularEditor.Portable.zip" 

# Download destination (root of PowerShell script execution path):
$DownloadDestination = join-path (get-location) "TabularEditor.zip"

# Download from GitHub:
Invoke-WebRequest -Uri $TabularEditorUrl -OutFile $DownloadDestination

# Unzip Tabular Editor portable, and then delete the zip file:
Expand-Archive -Path $DownloadDestination -DestinationPath (get-location).Path
Remove-Item $DownloadDestination
```

------------------

2) DEPLOY SCRIPT -- inline

```cmd
echo 'Build.SourcesDirectory = ' , $(Build.SourcesDirectory)

TabularEditor.exe "$(Build.SourcesDirectory)\bids\Models\L2L\Model.bim" -D "$(ASConnectionString)" "$(ASDatabaseName)" -O -C -P -R -M -W -E -V
```

--------------------
OUTPUTS
--------------------
1) OUTPUT Download task run

```
Starting: Download Tabular Editor
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\527a32b5-447e-4d49-9544-e658ef7fd577.ps1'"
Finishing: Download Tabular Editor
```

2) OUTPUT DEPLOY SCRIPT
```
Starting: Deploy AS model using Tabular Editor
Generating script.
========================== Starting Command Output 
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\545ce3c4-3433-41dd-9861-7cee4d877814.ps1'"
Build.SourcesDirectory = 
D:\a\1\s
TabularEditor.exe : The term 'TabularEditor.exe' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.
At D:\a\_temp\545ce3c4-3433-41dd-9861-7cee4d877814.ps1:5 char:1
+ TabularEditor.exe "D:\a\1\s\bids\Models\L2L\Model.bim" -D "Provider=M ...
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (TabularEditor.exe:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by otykier** [comment]
I recommend using a Command Line Task in step 2, instead of PowerShell, as PowerShell doesn't handle the output of TabularEditor.exe properly.

Also, you may need to specify the Working Directory in step 2, to ensure that it points to the location where Tabular Editor was downloaded and extracted in the previous step.

![image](https://user-images.githubusercontent.com/8976200/184073913-f8b05b30-4d47-4548-8ae8-0ce4950670df.png)

**Comment by fausttiger** [comment]
Command Line Step worked!

I did not have to specify the working directory path.
(can also deploy from TE3 directly).

Thanks, Tony

Still have to address the (power query data source related) warning items, but I knew about them and are addressing in another TE3 post.

##[warning]Information: Unprocessed object: partition 'Partition' on table 'XXX' (NoData)
##[warning]Information: Unprocessed object: column 'YYY'[ServerSiteSlicer] (CalculationNeeded)
