### ISSUE TITLE
TabularEditor.exe 2.16.7 Best Practice run (-A)  still fails if '-V' option not given (fails cmd.exe run with -1)

### ISSUE THREAD

**Issue by fausttiger** [TabularEditor/TabularEditor#1020]
**Describe the bug**
Running command line TabularEditor best practices run...  v2.16.7  with -A flag but -V flag removed,  still fails step when [error] occurs, and hence pipeline run.   -V flag presence being ignored? (always considers present?)

From earlier TE documentation/blog:
"The -V switch instructs Azure DevOps to treat rule violations differently, depending on the severity level of the rule being broken. Severity level 3 violations are reported as errors (causing the build to fail), level 2 are reported as warnings (causing the build to partially succeed), and level 1 are only informational."

**To Reproduce**
1)  create pipeline run in Azure DevOps on Tabular Model hosted in AAS

2) Download URL for Tabular Editor portable:
$TabularEditorUrl = "https://github.com/otykier/TabularEditor/releases/download/2.16.7/TabularEditor.Portable.zip" 

3. Command Line step (use -A option, but NOT  -V option)
REM add -V option to fail step if  severity 3 or greater found
TabularEditor.exe "$(Build.SourcesDirectory)\bids\Models\L2L\Model.bim" -A

4) run pipeline again model with  [error] rule tagging 'Do not use floating point data types'

5) warning and errors are still found, but NOT tagged (orange for [warning[, red for [error] )
 if -V is present than the  warning, error, etc. tags ARE created.     but not without -V
only [error] are floating point errors
i.e.
  Column 'Machine'[CycleCountMultiplier] violates rule "Do not use floating point data types"
  ...
  Column 'Pitches'[DowntimeMins_pitch] violates rule "Do not use floating point data types"

AAS Model still works for these data types... will address, but want to complete best practice and deployment pipelines before adjusting data types in working model.

6) step still fails for  [error]  
##[error]Cmd.exe exited with code '1'.

**Expected behavior**
Ignores [error] condition and returns step as success

**Observed behavior**
##[error]Cmd.exe exited with code '1'.    when [error] present and -V option removed

**Application specifics**
 - Tabular Editor 2.X version: [v2.16.7]
 - Semantic Engine used: [Azure Analysis Services,  Azure SQL data source]
 - Model Compatibility Level: [1400.]

**Additional context**

image of step with no -V flag,  still stopping next step with fail

![no V flag but next step aborted](https://user-images.githubusercontent.com/905135/184456744-a11576ce-8f7a-4a86-ab17-aa9bfc288a0e.JPG)

**Comment by otykier** [comment]
Severity level 3 rule violations always cause TabularEditor.exe to return a non-zero exit code (indicating failure). -V is only used for specifying the format of the console output - it doesn't affect the exit code. When using -V, Azure DevOps is able to nicely format the log (showing errors in red and warnings in yellow).

If you want DevOps to ignore any errors in this step, just enable the "Continue on error" option.

![image](https://user-images.githubusercontent.com/8976200/184809870-e1213709-d7a3-4856-834a-986e823f45a4.png)

**Comment by fausttiger** [comment]
resolved from feedback.
