### ISSUE TITLE
C# Script overwrites the old advanced scripting scripts

### ISSUE THREAD

**Issue by tschwenger** [TabularEditor/TabularEditor#1022]
!!! Please make sure you're using the latest version of Tabular Editor 2.X before submitting a bug !!!
!!! For Tabular Editor 3 issues, go here -> https://github.com/TabularEditor/TabularEditor3/issues !!!

**Describe the bug**
I created a new "macro" in the most recent release of tabular editor and it wiped out all the old rules that I had. 

When I originally opened the new c# scripting, it had all my old rules, but when I used the plus button, all my old rules that I wrote were erased.

**To Reproduce**
1. If you have old c# scripts created by the advanced scripting
2. go to C# script
3. Go to macros (you should see all your old scripts)
4. create a new script
5. new script will be added but all old scripts will be deleted. 

**Expected behavior**
Expect when adding a new macro that my old macros don't get deleted from the prior version

**Observed behavior**
A clear and concise description of what happened. Include any error messages or stack traces if possible. Also, feel free to add screenshots or recordings showing the problem.

**Application specifics**
 - Tabular Editor 2.17.0 
 - Semantic Engine used: [e.g. Power BI Desktop, Azure Analysis Services, SSAS 2019, etc.]
 - Model Compatibility Level: [e.g. 1400, 1500, 1520, etc.]

**Additional context**

**Comment by otykier** [comment]
Thanks for reporting. A fix is available now: https://github.com/TabularEditor/TabularEditor/releases/tag/2.17.1
