### ISSUE TITLE
Creation of EntityPartition to enable DirectQuery over Power BI Dataset.

### ISSUE THREAD

**Issue by mattias-de-coninck** [TabularEditor/TabularEditor#1026]
Hi All,

With the ability to create models on top of already existing Power BI Datasets via (https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-datasets-azure-analysis-services) a whole new can of worms has been opened for the CI/CD geeks among us.

The current scenario I have is that I would like to automatically create a DirectQuery model on top of an already existing Power BI Dataset in order to hide certain columns and measures for a different audience. The problem I am bumping into is that there is no way for me to create EntityPartitions as far as I can see.

Is there perhaps an alternative way to create such partitions without the use of the **AddPartition** and **AddMPartition** functions available for the Table objects?

Any help is much appreciated!

**Comment by otykier** [comment]
This is now possible in [2.17.2](https://github.com/TabularEditor/TabularEditor/releases/tag/2.17.2), which introduces the **AddEntityPartition** method.
