### ISSUE TITLE
Advanced Filter on columns  - calculation items issue

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor#1027]
**Describe the bug**
Filtering the ObjectType within the advanced filter to 'Column' also includes calculation items. The goal of the syntax below is to find column(s) which have a specific Translated Name. Not sure if this is a bug or part of TOM (or if there is a workaround). Thanks!

**To Reproduce**
1. Enter the following into the Advanced Filter: :ObjectType = "Column" and TranslatedNames = "hello"
2. See error

![image](https://user-images.githubusercontent.com/29556918/187063983-06a216e4-3c8c-4072-b19a-65e167aa6ad3.png)

**Expected behavior**
Would expect to filter to just columns (as calculation items are not columns).

**Observed behavior**
Oddly enough, the calculation items are not shown in the TOM explorer when the filter on ObjectType = "Column" is applied.

**Application specifics**
 - Tabular Editor 2.17.1

**Comment by otykier** [comment]
Hi Michael. Apologies for the late reply. The issue here is that you need to specify a culture as well, as `TranslatedNames` is an indexed property:

```
:ObjectType="Column" and TranslatedNames["en-US"]="hello"
```

**Comment by m-kovalsky** [comment]
thanks Daniel!
