### ISSUE TITLE
Cannot connect to Azure SQL Database with MFA

### ISSUE THREAD

**Issue by goreavin** [TabularEditor/TabularEditor#1029]
I followed the steps mentioned on Importing Tables [page](https://docs.tabulareditor.com/te2/Importing-Tables.html#azure-active-directory-with-mfa) but was unsuccessful in connecting with the following error:
![image](https://user-images.githubusercontent.com/62012170/188284853-6ddaf923-3fd5-46f4-8a19-4319e7a4b640.png)

The MFA window did apprear and I confirmed that it accepted the password.
What could be the issue?
Details: I am trying to connecting to the SQL server supporting Datamart on PowerBI service (Premium Workspaces)

**Comment by otykier** [comment]
Microsoft does not allow third party tools to connect to the Power BI Datamarts SQL endpoint.

**Comment by goreavin** [comment]
Thank you for the explaination Daniel. It is a shame that Microsoft does not permit this. But now I know at least that it is not something wrong with the tool or my settings.
