### ISSUE TITLE
SHA256 Checksum for the download for version 2.X

### ISSUE THREAD

**Issue by shishini** [TabularEditor/TabularEditor#1030]
Is it possible to provide the SHA256 Checksum/filehash for the .msi installer for version 2.X
this will add some security and assurance to the verification of  the download 

Thanks

**Comment by otykier** [comment]
Great suggestion. We've added this to [2.17.1](https://github.com/TabularEditor/TabularEditor/releases/tag/2.17.1) and will make sure to include that going forward.
