### ISSUE TITLE
Scripts with built-in custom classes cannot be saved as Macro?

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor#1034]
Hi, 

I created a script with a built-in custom class at the end with the trick of closing one extra curly bracket and leaving one open at the end.  It executes fine, but when I want to store it as a macro it says it has errors 

the script is here and creates a calc group to enable the selected inactive relationships 
https://github.com/bernatagulloesbrina/TabularEditor-Scripts/blob/main/Advanced/One-Click%20Macros/Inactive%20Relationships%20Activation%20Calc%20Group%20Script.csx

is there anyway this can be saved as a macro in TE2 ? 

Regards!

**Comment by otykier** [comment]
This will be fixed in 2.17.2, where it will also no longer be necessary to use the hack with the extra curly bracket.

**Comment by bernatagulloesbrina** [comment]
THIS IS AWESOME! thank you!!

**Comment by otykier** [comment]
[2.17.2](https://github.com/TabularEditor/TabularEditor/releases/tag/2.17.2) is now available!
