### ISSUE TITLE
Table Description Disappears After Hitting "Apply"

### ISSUE THREAD

**Issue by jd-edwards-12** [TabularEditor/TabularEditor#1039]
Using Tabular Editor 2.17.1

**Describe the bug**
A manually inputted description (or a description from a C# script) for a table will disappear after hitting "apply" for updates to a .pbix file.

**To Reproduce**
1. Open a .pbix file that has at least one table imported into it.
2. Open Tabular Editor.
3. Click on 'Tables' from the Model Pane.
4. Scroll down to the table and select the table.
5. Under the 'Basic' options for the table, input a description in the 'Description' field.
![image](https://user-images.githubusercontent.com/113471642/193330398-10969854-2c7e-4df6-bd38-cee8aeb437e0.png)
6. Go to "File->Save"
7. Verify the "Description" for the table carried the new description into the model.
8. After Step 6 (saving the updated description to the model), a message pops up in the .pbix notifying the user they have pending changes and if they want to apply or discard the changes.
![image](https://user-images.githubusercontent.com/113471642/193331291-6610786d-8fd3-4b4a-8eb6-6ba870d4aaf7.png)
9. Once selecting "Apply changes", the description then disappears from the model.  If the user selects "Discard changes", and then eventually refreshes the data  in the model, the description again disappears from the model.
![image](https://user-images.githubusercontent.com/113471642/193332623-af6ed26b-0b1f-4bca-bdbc-98103572f3e1.png)

**Expected behavior**
Expected behavior would be for the table descriptions to be maintained after applying changes to the .pbix is clicked (or after a model is refreshed).  When applying the same process to descriptions for columns, the descriptions are maintained after clicking "Apply changes".  

**Application specifics**
 - Tabular Editor 2.17.1
 - Power BI Desktop

**Comment by otykier** [comment]
Editing table properties through external tools, is unfortunately not supported by Power BI Desktop: https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-limitations

**Comment by jd-edwards-12** [comment]
Oh, bummer.  Well thanks for the quick reply, Daniel.  Do you know if this will ever be made available?

**Comment by ellisst** [comment]
I'm using Tabular editor 2 version 2.16.6 and I can successfully add descriptions to tables and columns. Once I deploy my model to my Power BI workspace, I can see the descriptions of both Tables and columns.

**Comment by otykier** [comment]
@ellisst this is why Microsoft lists these types of changes as "not supported": Sometimes it works. Sometimes it doesn't.
