### ISSUE TITLE
Data transfer protocol

### ISSUE THREAD

**Issue by DieselAnalytics** [TabularEditor/TabularEditor#1040]
A client's IT department wants to know the data transfer protocol of Tabular Editor. They want to know if it is secure and safe. Do you have any info I can share with them?

**Comment by otykier** [comment]
Tabular Editor does not implement its own data transfer protocol. Instead, it relies on Microsoft-provided client libraries for communication with Analysis Services. More information [here](https://docs.tabulareditor.com/te3/features/security-privacy.html).

**Comment by DieselAnalytics** [comment]
Thanks for your prompt response!
