### ISSUE TITLE
Measures are not showing anymore

### ISSUE THREAD

**Issue by Akakaboto** [TabularEditor/TabularEditor#1041]
Hello, 

since 2 weeks back I am no longer able to see my measures in tabular editor. 

As you you can see from the picture I have a lot of measures in power BI that I created within Tab Editor. For some reason they are no longer visible when I open up Tabular Editor. I only see the Partitions below my measure folder. 
What could cause this issue? I probably have 1000+ measures in my report. 

![Missing measures Tab Editor 2](https://user-images.githubusercontent.com/115162263/194322513-f0e66618-d05e-4c9f-bb57-25d90ab62aae.png)

**Comment by otykier** [comment]
Toggle display of measures: CTRL+1
