### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by farlyn3** [TabularEditor/TabularEditor#1042]
!!! Please make sure you're using the latest version of Tabular Editor 2.X before submitting a bug !!!
!!! For Tabular Editor 3 issues, go here -> https://github.com/TabularEditor/TabularEditor3/issues !!!

**Describe the bug**
Deployment to SSAS failed

**To Reproduce**
1. Go to 'Model'
2. Click on 'Deploy'
3. Local server using windows integrated login
4. Create new database
5. Deploy with default settings
6. Deploy

**Expected behavior**
Model deployed to SSAS from Tabular Editor 2.17.1

**Observed behavior**
Error occured during deployment.

![image](https://user-images.githubusercontent.com/91094745/194783175-a96fdfaa-0ed1-47f5-a0df-6c7514084d5d.png)

**Application specifics**
 - Tabular Editor 2.X version: [2.17.1]
 - Semantic Engine used: [SSAS 2019]
 - Model Compatibility Level: [1500]

**Additional context**

**Comment by otykier** [comment]
This is an issue related to your Analysis Services instance. Please see this [answer on stackoverflow](https://stackoverflow.com/a/62407422/1594867).
