### ISSUE TITLE
Can you replace lineage tags to prevent server held dashboards breaking when moving columns between tables?

### ISSUE THREAD

**Issue by mark-endicott** [TabularEditor/TabularEditor#1043]
We are restructuring a number of Dimension tables in a model that has been used to create many business facing dashboards. This will involve a number of columns in use in visuals moving to new dimensions. 

I am aware this will break the created dashboards, however I am curious to understand if we can use the existing lineage tags to prevent this? So, can we record the current lineage tags and use tabular editor to overwrite the new tags with the current ones once we have created the new dimensions?

If we can, can you let me know the process?

**Comment by otykier** [comment]
Hi Mark. Unfortunately, Power BI visuals does not consider lineage tags - only names of objects (tables/columns/measures). In general, moving columns/measures between tables, or just renaming a table, will therefore break your visuals. There are [(unsupported) workarounds available](https://community.powerbi.com/t5/Service/Rename-columns-in-dataset-without-breaking-all-deployed-reports/m-p/2671183/highlight/true#M168165) to deal with this.

(As a side note, lineage tags are used by Power BI to track object lineage when building composite models)

**Comment by mark-endicott** [comment]
@otykier - I suspected this was the case when we ran a few tests by renaming columns with the lineage tags unchanged. 

Thank you for the link to the article, we are running some cautious tests to see if this will work for us.
