### ISSUE TITLE
Macros disappear when I close Tabular Editor 2.17.1 and open again

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor#1044]
Hello, 

I'm preparing a session where I use lots of scripts and I realized that every time I close Tabular Editor 2.17.1 and open again all the stored macros are gone -- 

anyone else experiencing the same? 

Regards!

**Comment by bernatagulloesbrina** [comment]
I just wanted to add that macros seem to be there because I can get the code from snippets / macros

they just do not appear on the right click menu 

I can add them as macro and they will show as macro as long as I don't close Tabular Editor. 

https://user-images.githubusercontent.com/40455069/196545188-607f2434-01f3-439c-85c3-3bc53150a445.mp4

**Comment by otykier** [comment]
Hi Bernat. Most likely one of your macros has a bug that does not let it compile. This causes the compilation of all macros upon Tabular Editor startup to fail (as they are compiled as a single module, for performance reasons). Perhaps you can share with me your `%LocalAppData%\TabularEditor\MacroActions.json` file, then I'd be happy to take a closer look?

**Comment by bernatagulloesbrina** [comment]
Hi Daniel, here it comes --all public domain macros after all--
[MacroActions.zip](https://github.com/TabularEditor/TabularEditor/files/9869421/MacroActions.zip)
I had to zip it to be able to upload. 
It did have a "ScriptHelper." but I removed that and the issue persists. 
If everything fails I can delete de file and start over, no big deal. TE2 I use it mainly for demos 

Regards!

**Comment by otykier** [comment]
Thanks for sharing - I located the bug. A fix will be available shortly.

**Comment by otykier** [comment]
Fixed in [2.17.2](https://github.com/TabularEditor/TabularEditor/releases/tag/2.17.2), thanks for reporting!
