### ISSUE TITLE
Pass arguments in CLI

### ISSUE THREAD

**Issue by pawarbi** [TabularEditor/TabularEditor#1047]
Hi, 

Is there a way to pass variable values in the CLI ? For example, I have a simple C# script that's saved as myscript.csx

```
var path = "C:\\Folder";

var properties = ExportProperties(Model.AllColumns);

SaveFile(path+"\\columnproperties.tsv", properties);
```

I can run the command in CLI: 

`start /wait TabularEditor.exe Model.bim -S myscript.csx`

Can I pass the value to the `path` variable instead of hardcoding it in the script. One way would be to launch a dialog box but I was wondering if there is a way to pass it as an argument in the CLI command. Sorry I barely know C#. 

Thanks!

**Comment by otykier** [comment]
One way to do this, is by using environment variables. I.e. set a variable in the command line, before executing the Tabular Editor CLI:

```cmd
set te_path=c:\Folder
```

Then, in your C# script, read the value of that environment variable:

```csharp
var path = Environment.GetEnvironmentVariable("te_path");
```

**Comment by pawarbi** [comment]
Perfect, thanks
