### ISSUE TITLE
Overwrite not actually deploying 

### ISSUE THREAD

**Issue by richardlhughes-ic** [TabularEditor/TabularEditor#1049]
While running the tabular editor via cli with the following options it is not overwrite the current model:

`script: 'TabularEditor "$(Pipeline.Workspace)\drop\Tabular\Reporting\Model.bim" -S $(Pipeline.Workspace)\drop\SetConnectionStringFromEnv.cs -D "$(ASServer)" "$(DatabaseId)" -O -C -R -M -V -E'`

I am having to manually drop the database from the server before running. 

SSAS version 15.0.35.33
Tabular Editor 2.17.1

**Comment by richardlhughes-ic** [comment]
Hi  @otykier  - thanks in advance for your response. 

How can I debug this issue? or can I provide you with more information to make help understand why this isn't working in any of my environments. 

Let me know how I can help resolve this issue. Currently, we are having to drop the models prior to deploying. I am running this via azure devops pipeline using the cli.

**Comment by otykier** [comment]
The command you’re using seems correct. Are you getting an error message? What happens if you attempt to perform a similar deployment through Tabular Editors UI?

**Comment by bgarcevic** [comment]
> Has anyone else seen this issue?

I experienced this error when I attempted to overwrite without the  -P / -PARTITIONS flag. Once I added that the error message dissappeared. I would say that this is a non issue as it only happens when not all changes are deployed.

**Comment by richardlhughes-ic** [comment]
@otykier and @bgarcevic let me follow up with you on these items. It's been so long since I visited this issue. I added a step to drop the model prior to deploying in my pipelines.

**Comment by richardlhughes-ic** [comment]
"I attempted to overwrite without the -P / -PARTITIONS flag" thanks @bgarcevic 

This was able to resolve my issue - might be helpful to others. Add `-P` to my pipelines. 

Thanks

**Comment by Bifarin** [comment]
Am I doing something wrong? I just added the -P switch and I am still getting the overwrite error

**Comment by Bifarin** [comment]
This is resolved for me now. I didnt put spaces between my flags. That was my mistake. I was using -O-P-C-R-M-V-E instead of  -O -P -C -R -M -V -E. This might be a pointer to anyone else
