### ISSUE TITLE
Two Instances of TE3 Open Simulataneously???

### ISSUE THREAD

**Issue by JeridInsight** [TabularEditor/TabularEditor#1053]
Is it possible to open two different models in two different instances of TE3 at the same time?  I can't figure out how to get it to work...

**Comment by otykier** [comment]
Certainly. You just open two instances like any other windows app (if you have a TE3 shortcut on the task bar, hold down SHIFT when you click the shortcut to open a new instance).

**Comment by JeridInsight** [comment]
Wow.  Ok.  I feel stupid now.  Hahaha...  I didn't know holding SHIFT down would do that.  For most applications, if you open it and an instance is already open, it will just spawn a second instance.  Good to know and thanks!
