### ISSUE TITLE
How can I formatting string using dot as thousand separator and comma as decimal separator

### ISSUE THREAD

**Issue by nvtruongmanh** [TabularEditor/TabularEditor#1057]
Is there any way I can use dot as thousand separator and comma as decimal separator in Tabular Editor?

Like this one in DAX:
FORMAT( 1234.567, "#,0.00", "de-DE" )

Desired result:
1.234,57

**Comment by otykier** [comment]
The symbols used as decimal/thousand separators depends on the language locale of your Operating System, or the culture used by your Analysis Services instance. As such, this is unrelated to Tabular Editor.

**Comment by nvtruongmanh** [comment]
@otykier thank you for your answer. You have my appreciate.
