### ISSUE TITLE
Is it possible to extract the model from a SSAS Live connected Power BI report (without being admin of SSAS)

### ISSUE THREAD

**Issue by Yasston** [TabularEditor/TabularEditor#1058]
Hi everyone, this is not an issue, just a question : is it possible to extract the tabular model (json bim model) from SSAS, without being an admin on the SSAS instance.
I have a Read only access to a tabular model hosted on an on-prem SSAS 2019 instance. I need to extract the model to deploy it elsewhere in Import mode. I can Live connect a PBI Desktop report to the SSAS model. If I go into the 'Model' pane in PBI Desktop, I can actually see the model with all the tables and the relationships between them. Is there a way to extract it to a bim json format (the usual model format that I can later on deploy elsewhere) ? 
I tried connecting to the SSAS instance using Tabular editor, but it fails with the error message : `Error loading model: The 'Database' with 'ID' = 'xxxx' doesn't exist in the collection.` I know the database exists, I can connect to it using PBI Desktop, and even Excel. From what I read, TabularEditor fail is normal because I am not an admin of the SSAS instance. FYI, I can also connect to the SSAS model using DAX Studio. But I cannot query any DMV because I am not an admin of the model/SSAS instance.

So, is it still possible to extract it ? How come Power BI Desktop can actually show me the model and all its relationships and everything ?

One last note : Doesn't look like I can leverage the new feature "DirectQuery for Power BI datasets and Analysis Services" in Power BI Desktop to extract a copy of the model. Probably because it is not hosted on a 2022 version of SSAS...

Thank you for reading this far ^^

**Comment by otykier** [comment]
This is not possible, as far as I know, as you only have access to a limited subset of DMVs when you're not an admin. So stuff like partitions, RLS and OLS, etc. can not be retrieved. Even measure definitions (DAX) in some cases. Power BI is able to show the model as names and datatypes of tables, columns, measures and relationships is available for querying through DMVs (or more precisely, through the CSDL schema), even when you're not an admin. But this information is not sufficient to get the full TOM model.

**Comment by Yasston** [comment]
Ok got it, thank you very much for all the info !
