### ISSUE TITLE
Unhandled exception when running commandline with -T and -A if there is a rule with higher compatibility level than model

### ISSUE THREAD

**Issue by DBojsen** [TabularEditor/TabularEditor#1059]
!!! Please make sure you're using the latest version of Tabular Editor 2.X before submitting a bug !!!
!!! For Tabular Editor 3 issues, go here -> https://github.com/TabularEditor/TabularEditor3/issues !!!

**Describe the bug**
I want to run BPA rules check against model and output as TRX file.
I get an exception if there is a rule with a higher compatibility level than the loaded model.

**To Reproduce**
Get the Adventure Works sample model.
Run:
TabularEditor.exe "c:\Temp\AW Tabular\database.json" -T "c:\temp\test.xml" -A "https://raw.githubusercontent.com/microsoft/Analysis-Services/master/BestPracticeRules/BPARules.json"

**Expected behavior**
A file is generated with the result

**Observed behavior**
An unhandled exception occurs and crashes the application

**Comment by otykier** [comment]
Fixed in [2.17.3](https://github.com/TabularEditor/TabularEditor/releases/tag/2.17.3). Thanks for contributing!
