### ISSUE TITLE
Where to find TOMwrapper14.dll 

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor#1061]
hi, 

I just installed Tabular Editor 2.17.0 in a VDI from Azure. However when I go to LocalData 

C:\Users\{myuser}\AppData\Local
is not there to be found 

I've searched to all the obvious places I could think of but did not find it. 
And it has to be somewhere, otherwise it would not work

Regards,

**Comment by otykier** [comment]
The folder and files within are not created until Tabular Editor is run for the first time. Installing is not enough :)

**Comment by bernatagulloesbrina** [comment]
Oh!
indeed!! 
Checked and indeed now the file is there 

thank you!! 

I was so puzzled to see that in the portable version the file did not exist either
