### ISSUE TITLE
API documentation Global Methods, Global Variables

### ISSUE THREAD

**Issue by KommentatorForAll** [TabularEditor/TabularEditor#1064]
Where can i find propper documentation for the available globals?
It is mentioned in the [advanced scripting](https://docs.tabulareditor.com/te2/Advanced-Scripting.html#helper-methods) page that there are the Selected and the Model object available in addition to some methods
but thus far, i was unable to find any documentation especially on the methods and their typing.
And globals aren't even mentioned in the api reference.

It would be great if there was an additional page (best on top) in the api reference showing all global variables and methods

**Comment by otykier** [comment]
The `Selected` object is of type [Selection](https://docs.tabulareditor.com/api/TabularEditor.Shared.Interaction.Selection.html).

`Model` is of type [Model](https://docs.tabulareditor.com/api/TabularEditor.TOMWrapper.Model.html).

The global methods are listed [here](https://docs.tabulareditor.com/api/TabularEditor.Shared.Scripting.ScriptHost.html#TabularEditor_Shared_Scripting_ScriptHost_CallDaxFormatter_System_Nullable_System_Boolean__System_Nullable_System_Boolean__).

Note, a few of them are only available in TE3 - we're working on improving the docs to better indicate this.
