### ISSUE TITLE
Does the Tabular editor needs 32 bit oracle driver or 64 bit oracle driver ?

### ISSUE THREAD

**Issue by mudassarMDV** [TabularEditor/TabularEditor#1068]
Does the Tabular editor needs 32 bit oracle driver or 64 bit oracle driver ?

**Comment by otykier** [comment]
You need to use 32 bits or 64 bits depending on the platform used by Tabular Editor on your machine. You can check this using Windows Task Manager (on my machine, it's 32 bits):

![image](https://user-images.githubusercontent.com/8976200/220102095-7fe968bd-5a20-4ba1-a668-0650ceefc549.png)
