### ISSUE TITLE
Error when deploying using command line but no error when deploying from Application

### ISSUE THREAD

**Issue by BenT13** [TabularEditor/TabularEditor#1070]
Hello,
I'm having the following issue when deploying from command line:

##[error]Deployment failed! Column 'SalesRepNum' in Table 'Sales Rep' contains a duplicate value '91000033' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.
2023-01-12T08:05:51.7453150Z
##[error]Cmd.exe exited with code '1'.

But deploying the same model from TE2 application I'm not having any errors

Already checked Column 'SalesRepNum' in Table 'Sales Rep':

is not a key in the model
is not referenced in any relationships
Could you please help me figuring out this issue?

Thanks in advance,

Ben

**Comment by mlonsk** [comment]
Hi @BenT13 
Could you share the command line that you are using to deploy with?
Thank you

**Comment by BenT13** [comment]
Hi @mlonsk 
Please find here below the command:

`echo (Model.DataSources["BI SQL"] as ProviderDataSource).ConnectionString = Environment.GetEnvironmentVariable("BISQLConnectionString"); > SetConnectionStringFromEnv.cs
"C:\Program Files (x86)\Tabular Editor\TabularEditor.exe" "$(System.ArtifactsDirectory)\$(Build.DefinitionName)\drop\Model.bim" -S SetConnectionStringFromEnv.cs -D "$(ASConnectionString)" "$(ASDatabase)" -O -C -V -E -W -R -P`

Regards,
Ben

**Comment by mlonsk** [comment]
Thank you Ben,
Just to confirm. When you are deploying from within Tabular Editor where it works, you deploy to the same instance (Database and model) as when using the CLI

**Comment by BenT13** [comment]
Yes indeed

**Comment by BenT13** [comment]
If you have some availabilities as can have a screen sharing session and I can show you what I'm doing, maybe I'm missing some steps or not doing the rights things with TE2?

**Comment by mlonsk** [comment]
Hi Ben
I have a few more questions, but we can set up a meeting. :) Shoot me an email on morten.lonskov@tabulareditor.com
Have you tried deploying from the CLI from your local laptop and does that work? 
Which version of TE2 are you using in Devops?
Have you tried to "Process Clear" your SalesRep table and then running the deployment? Does it work then

**Comment by BenT13** [comment]
Hi Morten,
I didn't try yet deploying from CLI from my local laptop.
Version of TE2 on my tfs server is 2.17.2, the same installed on my local laptop.
After a "Process Clear" deployment is successful, I'll know it for next time :)

Thanks a lot for your support,
Best regards,
Ben
