### ISSUE TITLE
Execute C# scripts from cmd with parameters?

### ISSUE THREAD

**Issue by Arklur** [TabularEditor/TabularEditor#1074]
**What are you trying to achieve?**
I have a C# script, it's saved to a file. When I execute the script from CMD, for example:

`TabularEditor.exe "%bim_file_path%" -S "%script_file_path%" -BIM "%bim_file_path%" >> "%output_log_file_path%"`

I would like to pass parameters to the script itself. Let's say...I would like to replace date filters in measures and I want to pass the new date to which I'll replace the old ones to. How could I achieve this directly and not indirectly? I thought about creating a "config file" somewhere that can be read from the C# script, "passing parameters" from there, but that seems an ugly workaround.

**Comment by otykier** [comment]
You can use environment variables. In the command line, you can set a variable before running TabularEditor.exe:

```
set datefilter=2023-01-28
```

In your C# script:

```csharp
string dateFilter = Environment.GetEnvironmentVariable("datefilter");
```

**Comment by Arklur** [comment]
Awesome, thanks for the quick answer and help!
