### ISSUE TITLE
ResolveObjectPath always returns null

### ISSUE THREAD

**Issue by o-o00o-o** [TabularEditor/TabularEditor#1077]
**Describe the bug**
ResolveObjectPath always returns null

**To Reproduce**
- Create a model with a Dates table and a Date column
- run c# script ```ResolveObjectPath("Model.Dates.Date").Output();````
- See output shows null
- Expected to return the column found

![image](https://user-images.githubusercontent.com/13693159/217324289-0d5bb893-0875-4d2c-bd6e-d76cfb431afe.png)

**Expected behavior**
- Expected to return the Dates[date] column found

**Observed behavior**
null returned

**Application specifics**
 - Tabular Editor 2.X version: v2.17.2
 - Semantic Engine used: N/A
 - Model Compatibility Level 1500

**Additional context**
This used to work fine but not sure when in the last couple of years exactly when it broke as the affected code is not regularly run on our system

**Comment by otykier** [comment]
I believe we changed the path structure a while back, to account for ambiguity. Try changing the string to:

`Model.T.Dates.C.Date`

or call `GetObjectPath()` on an object to see what it returns.

**Comment by o-o00o-o** [comment]
Yes, Model.T.Dates.C.Date works but this presents the code with a new problem - I don't know implicitly whether it is a Column or a Measure being referred to (and I didn't need to know). 

What was the ambiguity that this was to resolve? It doesn't seem possible to have a measure and a column in the same table with the same name. 

Any chance of providing a backward compatible version that will work as the previous one did (accepting that if it gets a conflict it will exception?). I guess the alternative is that I would need to try both T.X.C.Y and then if null returned try T.X.M.Y ..

**Comment by otykier** [comment]
[2.17.3](https://github.com/TabularEditor/TabularEditor/releases/tag/2.17.3) now lets `ResolveObjectPath()` work with the "old format", i.e. paths such as: `Model.Dates.Date`.
