### ISSUE TITLE
Download all models from Server

### ISSUE THREAD

**Issue by DerekJarvis** [TabularEditor/TabularEditor#1079]
Is it possible to download all models from a specific server connection? Currently I need to `Connect to Tabular Server`, `Choose Database`, and then `Save As` or `Save to Folder` for each model. With 20 models, this is slow.

It would be great if there was a way to download all of them at once, or perhaps this is possible with a script?

I see in issue https://github.com/TabularEditor/TabularEditor/issues/991 it may be possible to create a batch script where I create an entry for each database, but I would need to update this script each time a new database is added. Also, because each one would be a separate invocation, it would require multiple interactions with the MFA popup for organizations that have that enabled.

**Comment by m-kovalsky** [comment]
Try running this script while connected to an AS instance from Tabular Editor. Just make sure to update the folderPath and saveType parameters.
https://github.com/m-kovalsky/Tabular/blob/master/SaveAllModelsOnServer.cs

**Comment by DerekJarvis** [comment]
Thank you for this. It seems to function the similar to a batch file I put together. Yours is better because it can pull the list of databases from the server, but it doesn't seem to work remotely with a powerbi:// datasource; I'm getting a "Error loading model: A connection cannot be made. Ensure that the server is running."

It seems this still requires authentication for each database download - is there a way around this? Could it all be done within one TabularEditor process, instead of spawning additional processes?

**Comment by m-kovalsky** [comment]
If you're trying to save all the datasets from a Premium workspace, then you will need to update the cmdText to the following, while filling in the <Application ID>, <Tenant ID>, <App Secret> values of your service principal. Service principals are the way to avoid the authentication issue.

@"start /wait /d ""C:\Program Files (x86)\Tabular Editor"" TabularEditor.exe " + @"""" + @"Provider=MSOLAP;Data Source=powerbi://api.powerbi.com/v1.0/myorg/" + serverName + ";User ID=app:<Application ID>@<Tenant ID>;Password=<App Secret>" + @"""";

**Comment by DerekJarvis** [comment]
> If you're trying to save all the datasets from a Premium workspace, then you will need to update the cmdText to the following, while filling in the , , values of your service principal. Service principals are the way to avoid the authentication issue.
> 
> @"start /wait /d ""C:\Program Files (x86)\Tabular Editor"" TabularEditor.exe " + @"""" + @"Provider=MSOLAP;Data Source=powerbi://api.powerbi.com/v1.0/myorg/" + serverName + ";User ID=app:@;Password=" + @"""";

Thank you very much, not only for your detailed answer to this question - but also for such a great tool!
