### ISSUE TITLE
Metadata translation works differently according to Power BI tenants.

### ISSUE THREAD

**Issue by AvaNaka** [TabularEditor/TabularEditor#1082]
**Describe the bug**
Metadata translation does not work simultaneously with the language setting of browser.

**To Reproduce**
1. Add metadata translation (ex: en_US and ja_JP) to some Measures using Tabular Editor.
2. Save the Power BI report and upload it into a Power BI workspace.
3. Switch to Browser language to Japanese (Power BI workspace language setting is set to "default(browser language)")

**Expected behavior**
In every tenant,translation behavior is the same.
 
**Observed behavior**
In one tenant,They are translated into English
But, in the other two tenants,they are translated in Japanse.
 

**Application specifics**
 - Tabular Editor 2.X version: 2.17.2
 - Semantic Engine used: Power BI Desktop(Version:2.114.803.0 64-bit )
 - Model Compatibility Level: not sure
 - 
**Additional context**
In all 3 tenants, Pro licenses are assigned. 
In the tenant where texts are translated in English, I'm guest user to the tenant, but am assigned admin role in the workspace.

**Questions**
Do any admin settings of Power BI tenants affect metadata translation's behavior of each tenant?

**Comment by otykier** [comment]
Unfortunately, this is not a Tabular Editor specific problem. Please raise this issue on the [Power BI community forums](https://community.powerbi.com/) or raise a support ticket with Microsoft.
