### ISSUE TITLE
Cannot connect to database - Minimal Compatibility Level of 2147483647

### ISSUE THREAD

**Issue by mwhit1** [TabularEditor/TabularEditor#1083]
When I attempt to open tabular editor from my PowerBI model, I receive a message that the "database compatibility level of 1601 is below the minimal compatibility level of 2147483647 needed for [model 'Model]...FormatStringDefinition at PowerBI mode."

A clear and concise description of what happened. Include any error messages or stack traces if possible. Also, feel free to add screenshots or recordings showing the problem.

![image](https://user-images.githubusercontent.com/102912997/222606844-388b27e2-bd2f-466a-a22c-7c6da49379ef.png)

**Application specifics**
 - Tabular Editor 2.16.8214.24954
 - Semantic Engine used: [e.g. Power BI Desktop, Azure Analysis Services, SSAS 2019, etc.]
 - Model Compatibility Level: 1601 (I think)

**Additional context**
The model includes a DirectQuery Connection to a PowerBI dataset in service and a few import tables. I have had a previous, potentially related, issue in this model while working in tabular editor. After working in tabular, I was unable to save the changes to PBI, because it somehow duplicated format string measures were created even though I don't use the format string expressions in this model. Luckily, I had recently saved my work and was able to continue using tabular editor after opening the last saved file.

**Comment by otykier** [comment]
Try to update to the latest version of Tabular Editor (2.17.3) and let us know if the issue persists.

**Comment by mwhit1** [comment]
That did the trick. Thanks, the check for updates button under preferences suggested there were no updates. But I just downloaded and installed the newest version and I am now able to use the editor again. Thanks again!
