### ISSUE TITLE
Azure SQL DB - Date datatype recognized as String

### ISSUE THREAD

**Issue by jozsefbraun** [TabularEditor/TabularEditor#1084]
I have an Azure SQL Database (PaaS) based AAS model where tables were correctly imported initially, but for a while now source data type DATE are not recognized correctly in Tabular Editor (latest version 2.17.8455), and "Refresh Table metadata" continuously bringing it up as a mismatch to modify it to String.
SQL user has full access to db, I even tried explicitly cast the data type to DATE in the view but same result.
![image](https://user-images.githubusercontent.com/75267241/223698732-2eb11954-e220-4d9e-b431-ae6fc939cebb.png)
![image](https://user-images.githubusercontent.com/75267241/223698954-abcb3c8f-e8e0-436b-b899-bdf2f3d83a81.png)

**Comment by jozsefbraun** [comment]
"Data source providers SQLOLEDB and SQLNCLI have been deprecated. Use MSOLEDBSQL instead." This advice from BPA rules solves the issue, but would appreciate if I can get a confirmation

**Comment by otykier** [comment]
Hi @jozsefbraun 
Apologies for the late reply. Yes, there are several reasons why it is preferred to use MSOLEDBSQL. One of them, is that the "Refresh table metadata" feature is better able to map datatypes.
