### ISSUE TITLE
Changes disappeared after refresh in power bi 

### ISSUE THREAD

**Issue by e2epradeep** [TabularEditor/TabularEditor#1090]
I have a power bi file with single table from azure SQL and opening tabular editor from external tools. 

When I change the name of column and save the tabular editor instance. I can see the changes in power bi file. If a refresh the power bi file, the changes made are disappeared.

Can you please help me here. Thanks

Pradeep

**Comment by otykier** [comment]
Changing column names through external tools is [not currently supported by Power BI Desktop](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#supported-write-operations)
