### ISSUE TITLE
Encoding in Expression Editor differ from Properties

### ISSUE THREAD

**Issue by Jdcfo** [TabularEditor/TabularEditor#1096]
When adding special character in M partitions or Dax Expression it is shown correct in properties, tooltips ect but not in the Expression Editor 

**To Reproduce**
1. add a Dax Measurement or M Expression like “ /* 🤐😟 */ SUM(Data[Sales])“ to a Power BI Report 
2. Open in Tabular Editor 2 and click on the measurement

![Pic](https://powerbi.fo/ImgUpload/TE2Encoding.png)

**Expected behavior**
Show the same encoding as Properties

Tested in Tabular Editor 2.18.1

**Comment by otykier** [comment]
The text editor component used by TE2 unfortunately does not support wide-char (unicode) characters, such as emojis. We don't currently have any plans to switch to another editor component.
