### ISSUE TITLE
CLI: Unable to save to .BIM after loading from TMDL folder

### ISSUE THREAD

**Issue by jhoolachan** [TabularEditor/TabularEditor#1101]
**Describe the bug**

I am able to load a model from a TMDL folder using the CLI but when I try to save to a .BIM file, I receive the error "File not found: {location of TMDL_Model folder}".

**To Reproduce**

1. Open PBIX
2. Open TE2 external tool
3. Save to folder with TMDL option selected, name folder TMDL_Model
4. Open command line

Running

 `start /wait /d "C:\Program Files (x86)\Tabular Editor" TabularEditor.exe "C:\...\TMDL_Model"`

successfully opens the model in TE2

while running

`start /wait /d "C:\Program Files (x86)\Tabular Editor" TabularEditor.exe "C:\...\TMDL_Model" -B "C:\...\Model.bim" ` 

fails with "File not found: C:\\...\TMDL_Model"

**Expected behavior**

Saving to .bim from a TMSL folder takes similar arguments as above and succeeds so I expected the above to work, particularly since I am able to successfully open the model from the TMDL folder.

**Application specifics**

 - Tabular Editor 2.18.8503.15415

**Comment by otykier** [comment]
Thanks for reporting. This will be fixed in the next update.

**Comment by otykier** [comment]
This is now fixed in [2.20.0](https://github.com/TabularEditor/TabularEditor/releases/tag/2.20.0)! Thanks for reporting!
