### ISSUE TITLE
Tabular Editor 2.18.1 Unhandled Exception connecting to Older Version of SSAS Tabular (2012)

### ISSUE THREAD

**Issue by Cedz** [TabularEditor/TabularEditor#1106]
!!! Please make sure you're using the latest version of Tabular Editor 2.X before submitting a bug !!!

**Describe the bug**
When opening a tabular model from a Analysis Services Server the application crashes throws an unhandled exception 

**To Reproduce**
1. Go to 'TabularEditor.2.18.1'
2. Click on 'File -> Open -> From DB'
3. Enter Tabular Server name ' xxxx.xxx.com\tab | with Windows Integrated or Azure AD Login'
4. See "Invalid Argument below"
 
![image](https://user-images.githubusercontent.com/12426229/236914938-44f2fca0-ae98-42d7-843c-0fe7befed4a3.png)

**Expected behavior**
I expect as per previous versions that the structure/schema of the Model will be connected to, and a visual hierarchy appears on the left as per below image

![image](https://user-images.githubusercontent.com/12426229/236914802-d06ea7df-656b-4f3d-8920-3d9d56ef830e.png)

**Observed behavior**
Application tries to open the model but encounters error 

**Application specifics**
 - Tabular Editor 2.X version: [e.g. 2.18.1.0]
 - Semantic Engine used: [Azure Analysis Services, SSAS 2012]
 - Model Compatibility Level: [1050, 1100, 1103]

**Additional context**
N/A

**Comment by otykier** [comment]
Tabular Editor requires that the model is in compatibility level 1200 or higher. This CL is only available from SQL Server 2016.
