### ISSUE TITLE
Copy and paste measure with dynamic format string in a target without any existing measure failed

### ISSUE THREAD

**Issue by cfkperso** [TabularEditor/TabularEditor#1109]
Copy and paste measure with dynamic format string in a target without any existing measure failed

1. To open my files, i launch PBI Desktop first and then open the dataset with tabular editor (from the external tool link)
2. Open a first dataset containing a measure with a dynamic format string
3. Open a second dataset without any measure with dynamic format string
4. copy the measure with the dynamic format string
5. paste it in the second model
6. You will have the error as below

**Expected behavior**
Should work without issue as it's working when the second dataset already contains a measure with dynamic format string.

**Observed behavior**
See the screenshot

**Application specifics**
 - Tabular Editor 2.X version: 2.18.2
 - Semantic Engine used: Power BI Desktop 
 - Model Compatibility Level: 1567 and 1601

![image](https://github.com/TabularEditor/TabularEditor/assets/71018635/1704583e-4716-47ae-a1ff-6c6b1a31dd3c)

**Comment by otykier** [comment]
Hi there.
Please upgrade the destination model to CompatibilityLevel 1601 before attempting to insert/paste measures with dynamic format strings. You can upgrade the model either through Tabular Editor, or by adding a dynamic format string to a measure through Power BI Desktop.
