### ISSUE TITLE
Show/hide metadata information columns not showing

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor#1114]
**Describe the bug**
The 'show/hide metadata information columns' button doesn't show metadata properties (besides 'name').

**To Reproduce**
1. Click on the button as mentioned above.
2. Just the 'name' shows. No other properties show.

**Expected behavior**
This used to show import/dq mode and other relevant metadata

**Application specifics**
 TE 2.18.2

**Comment by m-kovalsky** [comment]
Ah it's due to the length of some columns/measures. There are measures which have a length of 65 characters. If I expand the pane then it shows fine. If not, it looks like this.

<img width="289" alt="image" src="https://github.com/TabularEditor/TabularEditor/assets/29556918/43cf1d3d-306e-4b10-a11d-776fab1998a3">

**Comment by otykier** [comment]
You should also see a scrollbar at the bottom, in this case:
<img width="306" alt="image" src="https://github.com/TabularEditor/TabularEditor/assets/8976200/c3a94622-5629-4917-a2e1-bf6a41c0e2de">

**Comment by m-kovalsky** [comment]
Yes, I see the scrollbar. Thanks!
