### ISSUE TITLE
Refresh Table MetaData - timeout

### ISSUE THREAD

**Issue by mst42a** [TabularEditor/TabularEditor#1115]
**Is your feature request related to a problem? Please describe.**

During the "Refresh Table MetaData" or schemacheck operation, we often encounter an error; From what we have observed, it is due to the timeout (query in the partition is quite complex, and the server will not be able to respond in the default 30 seconds).

I have try earlier with

`"c:\Program Files (x86)\Tabular Editor\TabularEditor.exe" "$(System.DefaultWorkingDirectory)\BITabular\TabularArtifact\s\TABULARMODEL\database.json" -SCRIPT "$(System.DefaultWorkingDirectory)\BITabular\TabularArtifact\s\AddTimeOutToConnectionString.csx" -SCHEMACHECK -E -Vsts
`

where AddTimeOutToConnectionString.csx  is

```

foreach(var dataSource in Model.DataSources.OfType<ProviderDataSource>())
{   
    var evName = dataSource.Name.Replace(" ", "") + "ConnectionString";
    var NewConn = dataSource.ConnectionString + ";Connect Timeout=240;ConnectRetryCount=5";
    dataSource.ConnectionString = NewConn;

}
```
    
But this seems not working.

I would like to extend this default timeout. Probably in TableImport.cs below row 250 as

„cmd.CommandTimeout = 120;”.

![image](https://github.com/TabularEditor/TabularEditor/assets/63145285/c89e1095-5582-4b25-9a91-a1db16c7eb32)

**Comment by otykier** [comment]
This feature has been implemented and is available in [2.21.0](https://github.com/TabularEditor/TabularEditor/releases/tag/2.21.0). The timeout has to be specified in the data source:

![image](https://github.com/TabularEditor/TabularEditor/assets/8976200/5fcd1c58-8671-4d16-828e-bc6c1a0b5d83)

Thanks for suggesting!
