### ISSUE TITLE
Deploy TMDL model from command line failed to parse object named culture en-US

### ISSUE THREAD

**Issue by imagimage** [TabularEditor/TabularEditor#1124]
While trying to deploy model from tmdl folder structure, encountered error `##[error]Error loading file: TmdlFormatException encountered while deserializing TMDL: [InvalidName] Failed to parse object name from 'culture en-US'.`

**To Reproduce**
1. Save model as TMDL
2. Publish to Azure devops repo
3. Run pipeline to deploy
    - Download Tabular Editor 2.18.2
    - Deploy model with
        - `TabularEditor.exe "D:\a\1\s\"***"\model.tmd" -D Provider=MSOLAP;Data Source="***";User ID=app:"***"@"***";Password="***"; "***" -O -C -P -R -M -W -E -V
`

**Expected behavior**
I expect the model to be published to the workspace

**Observed behavior**
`##[error]Error loading file: TmdlFormatException encountered while deserializing TMDL: [InvalidName] Failed to parse object name from 'culture en-US'.`
`##[error]Cmd.exe exited with code '1'.`

**Application specifics**
 - Tabular Editor: 2.18.2
 - compatibilityLevel: 1567

**Comment by otykier** [comment]
CC @mthierba

**Comment by mthierba** [comment]
There was a breaking change between TMDL Preview-2 (19.64) and Preview-3 (19.65.7.2).

Preview-2, which is what the latest version of Tabular Editor is using, _requires_ single quotes `'` around object names, the latest Preview-3 does not.

See [this commit](https://github.com/mthierba/tmdl-example/commit/7d93a71209cd646f1bdd6df0d7204891395e67ed) for a full syntax diff between the two releases. Once TE is patched to the latest TMDL release that syntax will be valid. Until then, single quotes need to be added.

**Comment by otykier** [comment]
Thanks @mthierba - I'll provide a new build of TE2 soon.
