### ISSUE TITLE
Database compatibility level issue 

### ISSUE THREAD

**Issue by steved-MarketGrunt** [TabularEditor/TabularEditor#1127]
Ive installed TE2 V2.18.2. However, when I open a model, I see this error.
![2023-08-16_17-44-56](https://github.com/TabularEditor/TabularEditor/assets/42726129/71e677b2-3e8e-4c3d-8dfa-7ff08bf43941)
I also have TE3 and I'm able to open the model with out the error.

**Comment by mlonsk** [comment]
Hi @steved-MarketGrunt 
Could you try to install the newest version 2.19.0, as the TOM was updated to the latest version therein. 
Does the issue still persist?

**Comment by steved-MarketGrunt** [comment]
Sorry, my bad... I have 2 versions of TE2. The one from the Business Ops app has not been updated to the latest version. The other version, which has been updated, doesn't have the issue.

**Comment by mlonsk** [comment]
No worries, just glad that it works.
