### ISSUE TITLE
Unable to Format Time Intelligence Calculation 

### ISSUE THREAD

**Issue by Osam93** [TabularEditor/TabularEditor#1131]
When formatting the following calculations for a newly create dashboard where the data is being house in SharePoint. I am getting the following error message: 

![image](https://github.com/TabularEditor/TabularEditor/assets/122176215/d3dba0ae-6fbc-4a03-b36e-783cc7067fba)

 Below are the calculations:
1.
SELECTEDMEASURE ()

2.

CALCULATE(
 SELECTEDMEASURE(),
SAMEPERIODLASTYEAR('Calendar'[Date])
)

3.

VAR CurrentPeriod = SELECTEDMEASURE()
VAR PriorPeriod =
CALCULATE(
    SELECTEDMEASURE(),
    SAMEPERIODLASTYEAR(
        'Calendar'[Date]  )
        )
VAR Result = 
    IF(
       NOT(ISBLANK(CurrentPeriod))
        && NOT(ISBLANK(PriorPeriod)),
   CurrentPeriod - PriorPeriod
        )
   Return
   Result

4.

VAR CurrentPeriod = SELECTEDMEASURE()
VAR PriorPeriod =
CALCULATE(
    SELECTEDMEASURE(),
    SAMEPERIODLASTYEAR(
        'Calendar'[Date]  )
        )
VAR Result = 
    Divide(IF(
       NOT(ISBLANK(CurrentPeriod))
        && NOT(ISBLANK(PriorPeriod)),
        (CurrentPeriod - PriorPeriod)
        ),PriorPeriod)
   Return
   Result

**Comment by otykier** [comment]
Hi @Osam93 
Sorry for the late reply. This issue seems unrelated to Tabular Editor. If you believe this issue is caused by Tabular Editor, please feel free to reopen the issue with a more detailed explanation.
