### ISSUE TITLE
Command line unable to open model.tmdl

### ISSUE THREAD

**Issue by matt40k** [TabularEditor/TabularEditor#1132]
!!! Please make sure you're using the latest version of Tabular Editor 2.X before submitting a bug !!!
!!! For Tabular Editor 3 issues, go here -> https://github.com/TabularEditor/TabularEditor3/issues !!!

**Describe the bug**
Unable to find model.tmdl - this relates to the file extensions from .tmd to .tmdl. 

**To Reproduce**
TabularEditor.exe "DataModel" -S "documentation.csx"

**Expected behavior**
Runs successfully

**Observed behavior**
Tabular Editor 2.20.1 (build 2.20.8650.18985)
--------------------------------
File not found: DataModel
Tabular Editor exit code: 1

**Application specifics**
 - Tabular Editor 2.X version: Current Version: 2.20.8650.18985

**Additional context**
Affected areas are:
CommandLineHandler.cs - line 310
FormMain.cs - line 33 and line 654
FormMain.Designer.cs - line 2570.cs
TabularModelHandler.FileHandling.cs - line 90

**Comment by otykier** [comment]
Fixed in [2.20.2](https://github.com/TabularEditor/TabularEditor/releases/tag/2.20.2). Thanks for reporting!
