### ISSUE TITLE
Fail to open Model if Workspace Name contains a colon

### ISSUE THREAD

**Issue by witschidb** [TabularEditor/TabularEditor#1133]
When connecting to a Power BI workspace with a Colon (:) in the name, Tabular Editor throws an error

Error Connecting to database
 The given path's format is not supported.

![image](https://github.com/TabularEditor/TabularEditor/assets/49579776/0cc77849-bc45-45c2-bd42-7f9dbeed63e9)

Issue occurs in Tabular Editor 2.19+, 2.18.2 and below are not affected.

Workaround is to uninstall v2.19+ and revert to v2.18.2

**Comment by otykier** [comment]
This must be a regression in the Microsoft AMO/TOM client libraries, which Tabular Editor uses to connect. Downgrading would mean that you’re not getting the latest features and improvements, so I can’t recommend that.

Does it help to replace the colon with `%3A` in the connection string?

**Comment by witschidb** [comment]
I tested replacing the Colon with %3a as well as URL-encoding the entire connection string, but I got the same error. If I rename the workspace without the colon, I am able to connect with v2.20.2 (v2.19+), but once renamed with the colon same error.

**Comment by otykier** [comment]
Could be a regression in the AMO/TOM client library. Will try to see if I can reproduce the error and get back to you.

**Comment by otykier** [comment]
Fixed in [2.21.0](https://github.com/TabularEditor/TabularEditor/releases/tag/2.21.0). Thanks for reporting!
