### ISSUE TITLE
Calculation Groups Break Text Boxes

### ISSUE THREAD

**Issue by PBI-David** [TabularEditor/TabularEditor#1135]
I've run into the exact bug described here: https://community.fabric.microsoft.com/t5/Issues/Smart-Narrative-amp-Calculation-Groups-incompatibility/idc-p/3424978#M98921

Is this something you're aware of? Is there any work around for this?

**Comment by otykier** [comment]
This is a bug in Power BI. There’s unfortunate nothing we can do about it from our side.

As an alternative to calculation groups, consider using a disconnected table and suitable SWITCH statements on your measures, to achieve the same behavior. If you have many measures in your model, on which you want the calculation to work, consider using C# scripting to automate the creation of the SWITCH statements.
