### ISSUE TITLE
Source not showing for tables after version 2.20

### ISSUE THREAD

**Issue by rhains** [TabularEditor/TabularEditor#1136]
I had to downgrade to version 2.19.0 to see the sources for each table.

![image](https://github.com/TabularEditor/TabularEditor/assets/144365095/676a83cf-3a03-4fbd-a62f-4f1b16630495)

!!! Please make sure you're using the latest version of Tabular Editor 2.X before submitting a bug !!!
!!! For Tabular Editor 3 issues, go here -> https://github.com/TabularEditor/TabularEditor3/issues !!!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Observed behavior**
A clear and concise description of what happened. Include any error messages or stack traces if possible. Also, feel free to add screenshots or recordings showing the problem.

**Application specifics**
 - Tabular Editor 2.X version: [e.g. 2.12.0]
 - Semantic Engine used: [e.g. Power BI Desktop, Azure Analysis Services, SSAS 2019, etc.]
 - Model Compatibility Level: [e.g. 1400, 1500, 1520, etc.]

**Additional context**

**Comment by otykier** [comment]
Fixed in [2.21.0](https://github.com/TabularEditor/TabularEditor/releases/tag/2.21.0). Thanks for reporting!

**Comment by rhains** [comment]
Since we are using now Tabular editor 3 do you know if it has been fixed
there too?

Richard

**Comment by otykier** [comment]
It's planned, but I can't give a timeline right now. Sorry!
