### ISSUE TITLE
Direct Lake Dataset "Mark as Date Table" option

### ISSUE THREAD

**Issue by souldish123** [TabularEditor/TabularEditor#1142]
**Describe the bug**
The "Mark as Date Table" option is not greyed out for Direct Lake datasets.

**To Reproduce**
1. Go to 'Import Direct Lake dataset from Power BI'
2. Right-Click on 'Date Table'
3. Click "Mark As Date Table"
4. Click "Save"

**Expected behavior**
Power BI documentation mentions that DateTime relationships are not supported with Direct Lake datasets. 

<img width="383" alt="image" src="https://github.com/TabularEditor/TabularEditor/assets/147590032/07d26831-76d1-4680-afbb-9ecf331ee4dc">

There should not be an option to "Mark as Date Table" on a Date table within the dataset. 

**Observed behavior**
After marking as date table, the table is identified as a date table and the changes are also able to be saved on the dataset. 

**Application specifics**
 - Tabular Editor 2.X version: 2.20.2
 -  Semantic Engine used: Power BI Premium P Workspace, Direct Lake dataset]
 - Model Compatibility Level: N/A

**Additional context**
Since the dataset is allowed to be saved and marked as date table, it's not clear if there are any side-effects of this change and whether Time Intelligence functions will continue to work as expected like an import dataset. This could be communicated clearer if it is allowed or not, and also if there is a change or not by marking as date table.

**Comment by otykier** [comment]
@souldish123 I disagree. Even though DateTime relationships are not supported in Direct Lake datasets, it could still make sense to mark a table as a Date Table. You could use an integer key column on your date table to avoid the DateTime relationships, and in this case, it still would be very useful to have the Date Table semantics apply.

**Comment by otykier** [comment]
Oh, this is far from the only example of things you can do with Tabular Editor, which is not possible in the Web Modelling ;)

Closing this ticket - thanks.
