### ISSUE TITLE
Error when loading model.tmdl to TE

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor#1146]
**Describe the bug**
I receive an error when attempting to load a model.tmdl file into Tabular Editor. The model.tmdl file was created using the same version of Tabular Editor 2 (2.20.2)

<img width="312" alt="image" src="https://github.com/TabularEditor/TabularEditor/assets/29556918/4bbe8a97-d7d0-4c2c-a4d9-e2fa2a031bd9">

**To Reproduce**
1. Open .bim file
2. File->Preferences->Serialization -> Serialization mode = TMDL (preview)
3. File -> Save to folder...
4. Close TE, Open TE
5. File -> Open -> model.tmdl file which was just created
6. Error appears (see screenshot)

**Application specifics**
 - Tabular Editor 2.X version: 2.20.2
 - Model Compatibility Level: 1500

**Comment by otykier** [comment]
Hi Michael,
This error is raised during TMDL deserialization which is handled by [this library](https://www.nuget.org/packages/Microsoft.AnalysisServices.Tabular.Tmdl.retail.amd64). As such, there's not much I can do about it. Please reach out to the AS product group, as I'm sure you have access to :)

**Comment by m-kovalsky** [comment]
Ah, I see. I will do that, thanks!
