### ISSUE TITLE
Deploy TMDL model from command line failed to parse object

### ISSUE THREAD

**Issue by JT-BergerGroup** [TabularEditor/TabularEditor#1147]
Hello,

I downloaded current version 2.20.2 yesterday and trying to deploy from commandline 

I have the same issue as mentioned here: https://github.com/TabularEditor/TabularEditor/issues/1124

An unhandled exception occurred during deserialization.
TMDL Format Error: [InvalidName] Failed to parse object name from 'relationship 208aaac3-0187-4792-b7eb-4b268427d34a'.

Do i need to specify formatting settings somewhere? I also put TMDL serialization in the settings...
Thanks for any ideas

**Comment by otykier** [comment]
This error occurs during deserialization from TMDL, so unfortunately there's not much I can do on Tabular Editor's side as all TMDL handling is done by a [library provided by Microsoft](https://www.nuget.org/packages/Microsoft.AnalysisServices.Tabular.Tmdl.retail.amd64). This feature is still in preview, but I suggest you raise an issue on the [Microsoft Analysis Services GitHub page](https://github.com/microsoft/Analysis-Services)
