### ISSUE TITLE
Tabular Editor 2 freezing after any changes

### ISSUE THREAD

**Issue by otykier** [TabularEditor/TabularEditor#1148]
### Discussed in https://github.com/TabularEditor/TabularEditor3/discussions/1154

<div type='discussions-op-text'>

<sup>Originally posted by **@VasilinaBalashevich** October 24, 2023</sup>
When I do any changes in a tabular cube, like adding a new table or even renaming the existing ones, the TE starts freezing for ages (  about 1 hour). I've reinstalled it several times, the service desk team updated the system, so it must work properly, as my mates have the same laptops and the same version of TE, and they don't face this issue. Please,  give me a hand as it hinders efficient work. </div>

@otykier: 
Just to clarify, does this freeze happen when you attempt to save the change, or does it happen immediately when you make the change? Which version of TE2 are you using?

@VasilinaBalashevich:
It happens immediately when I make the change, e g I have just created a new relationship, once I clicked 'new relationship' it started freezing. the version is TE 2.20.2

@otykier:
I'm sorry, but it's not something I've seen or heard about before, so it's not easy to figure out what's causing this. Are your colleagues using the same version? Do you have access to another machine where you could try to install Tabular Editor to see if the same issue occurs there?

**Comment by VasilinaBalashevich** [comment]
Yes, my colleagues use the same version. Unfortunately, I don't have another machine, probably it makes sense to install it on VM?

**Comment by otykier** [comment]
Yes, I would recommend installing on a VM to see if that solves the problem.

Which version of Windows are you using on your machine? You can see this by opening a command prompt:

![image](https://github.com/TabularEditor/TabularEditor/assets/8976200/d40beb46-8d86-4313-bccb-52c2e1b6695b)

**Comment by VasilinaBalashevich** [comment]
I have the same as you - Microsoft Windows [Version 10.0.19045.3570]

**Comment by otykier** [comment]
I wonder if you have any custom macros or best practice rules installed, that would cause TE to become slow?

Could you try to rename your `%LocalAppData%\TabularEditor` folder into something else, just to keep it as a backup, and then try again? If this doesn't help, could you let me know if your colleagues are working on the same model as you, or a different one?

**Comment by VasilinaBalashevich** [comment]
The renaming the %LocalAppData%\TabularEditor folder helps! Fantastic! thank you soooo much for your help!

**Comment by otykier** [comment]
Glad to be of help.

Out of curiosity, did you have any custom best practice rules? I suspect that one of these rules may have slowed down your Tabular Editor installation. If you could share your BPARules.json file from that folder either here or with support@tabulareditor.com I would be happy to take a closer look.

**Comment by otykier** [comment]
Thank you. It looks like these are the [official best practice rules from Microsoft](https://powerbi.microsoft.com/en-us/blog/best-practice-rules-to-improve-your-models-performance/)? - last question: How many measures (approximately) does the model you're working on contain?

**Comment by VasilinaBalashevich** [comment]
9057 measures

**Comment by otykier** [comment]
Suspicion confirmed, thanks! (Some of the rules compare every measure in the model against every other measure - so that’s like 9057*9057 comparisons, which happens every time something is changed in the model - so that explains why it becomes so slow it basically freezes).

**Comment by VasilinaBalashevich** [comment]
Thank you for explanation, and for your help! have a great life:))
