### ISSUE TITLE
TE 2 Asking for a dependency?

### ISSUE THREAD

**Issue by SharmaAntriksh** [TabularEditor/TabularEditor#1149]
I have got a new laptop that has Windows 11 home and when I try to install TE2 this is the message I get:

![image](https://github.com/TabularEditor/TabularEditor/assets/73054674/824efe7c-c9df-4242-80ce-b414e4d28281)

Store:
![image](https://github.com/TabularEditor/TabularEditor/assets/73054674/f619a8c3-18b1-44aa-a0f7-a891047d0557)

If it helps I already have SQL Server, SSAS, PBI, Visual Studio installed and working fine.

**Comment by SharmaAntriksh** [comment]
2.19.0 works but not 2.20.2

**Comment by SharmaAntriksh** [comment]
Looks like the issue is because of digital signature, I had to uncheck this option in the windows defender and I could install 2.20.2

![image](https://github.com/TabularEditor/TabularEditor/assets/73054674/17155ce7-5b64-4778-8b34-784617f91412)

**Comment by otykier** [comment]
It is most likely because the 2.20.0 installer wasn't signed correctly. Could you try with [2.21.0](https://github.com/TabularEditor/TabularEditor/releases/tag/2.21.0)?

**Comment by SharmaAntriksh** [comment]
Yeah, that worked.
