### ISSUE TITLE
Installer Not Digitally Signed/Unknown Publisher

### ISSUE THREAD

**Issue by bgribaudo** [TabularEditor/TabularEditor#1150]
Uh oh! Did Tabular Editor 2.20.2 lose the digital signature on its MSI installer?

The SHA256 hash on the release page matches the file I downloaded, but the installer does not indicate that it is signed.

![image](https://github.com/TabularEditor/TabularEditor/assets/857202/7a25fa4d-0e80-4313-9cee-0efefd7b876b)

**Comment by otykier** [comment]
I’m investigating. Recommend using the portable version for now, since that’s signed.

**Comment by bgribaudo** [comment]
Thanks, @otykier.

On the MSI version, can you confirm that the hash posted on the releases page is accurate?

**Comment by otykier** [comment]
The hash is accurate, but there was an error during our release process causing the .msi not to be signed. Unfortunately, we didn't catch this. We'll be uploading a new, signed, .msi soon (which will obviously have a different hash).

**Comment by bgribaudo** [comment]
Thankis, @otykier!

**Comment by otykier** [comment]
[2.21.0](https://github.com/TabularEditor/TabularEditor/releases/tag/2.21.0) is now available, with proper code sign certificate on both the .msi and the .zip content.

**Comment by bgribaudo** [comment]
Thank you, @otykier!
