### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by pawarbi** [TabularEditor/TabularEditor#1153]
Thanks for releasing 2.21.0. The link in the release notes about DirectLakeBehaviour point to the link which is broken. Can you please update. 

Here is the link to teh page : https://github.com/TabularEditor/TabularEditor/releases/tag/2.21.0

Broken link : https://learn.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.model.directlakebehavior?view=analysisservices-dotnet

**Comment by otykier** [comment]
Yeah, unfortunately, Microsoft hasn’t made that page public yet :-(
Will remove the link for now.
