### ISSUE TITLE
Copy and paste between instances of TE

### ISSUE THREAD

**Issue by ccparkhill** [TabularEditor/TabularEditor#1154]
Sometimes I copy and paste between two instances of TE, measures, columns, etc. I wasn't able to do this with the latest build and had to roll back to the previous build. I was copying between a model opened from a DB to one opened from a folder.

**Comment by otykier** [comment]
Could you provide some more details please? I.e.:

- are you getting any error messages?
- what type of objects were you copying?
- did the two models have identical CompatibilityLevel and CompatibilityMode?

**Comment by ccparkhill** [comment]
No error messages, I was mostly copying columns from tables, they are both 1604/PowerBI. I tried copying from 1500/AnalysisServices to 1604/PowerBI and that worked on the previous build.

**Comment by otykier** [comment]
I'll look into it

**Comment by otykier** [comment]
This is now fixed in [2.21.1](https://github.com/TabularEditor/TabularEditor/releases/tag/2.21.1). Thanks for reporting!

**Comment by ccparkhill** [comment]
Amazing, thanks :)
