### ISSUE TITLE
Numeric values become text after adding Calculation Group

### ISSUE THREAD

**Issue by RogerPittet** [TabularEditor/TabularEditor#1159]
1. I created a model using Great Plains data via SQL.
2. Added all the measures and defined the relationships between tables.
3. Opened Tabular Editor 2.20 and tried to create a calculation group and all my numeric fields in my tables broke and started acting like text fields.

![Before](https://github.com/TabularEditor/TabularEditor/assets/152311731/944baec8-5d02-4ede-8fb5-ffb417687ac4)
![After](https://github.com/TabularEditor/TabularEditor/assets/152311731/5babf18f-4a51-4cff-93ef-4d0c34bc811f)

**Comment by mlonsk** [comment]
Creating a calculation group requires implicit measures to be turned off this is a required behaviour and you will experience the same if you create a calculation group directly in Power BI. 
Implicit measures are your numeric columns with the summarise symbol in your first picture. You need to create explicit measures instead which is generally considered a best practice in any case.

**Comment by mlonsk** [comment]
I will close the issue as this is not a TE2 issue

**Comment by RogerPittet** [comment]
Find it unfortunate for situations where you're creating numeric sorts and the like, but I can figure out some easy workarounds.
