### ISSUE TITLE
After adding Power BI roles, View as functionality is throwing error

### ISSUE THREAD

**Issue by sorenhakola** [TabularEditor/TabularEditor#1161]
**Describe the bug**
After adding new roles in Tabular Editor to a Power BI report, there's something going on with the model. The roles are created properly in Tabular Editor, save is working and the roles are showing up in Power BI's Manage Roles. But when using the "View as" functionality, Power BI is complaining about DirectQuery source is not found, although the model does not, I repeat not(!), contain any direct queries. After publishing to Power BI Service, we also notice that the rule in the role does not apply. 

**To Reproduce**
1. Open a Power BI report
2. Open Tabular Editor and connect to the Power BI report
3. In Tabular Editor, create a new role either by using Roles -> Right click -> New role, or by using C# Script Model.AddRole("Rolename"); There's no need to add any rules.
4. Save the model in Tabular Editor
5. Go to Power BI 
6. Use Home -> Security -> View as
7. Select the new role
8. Message shown:
Cannot load model
We could't connect to your DirectQuery data source or internal model. Double-check that your server and database names are correct, and that you have permission to access them.
Either the user '<username>', does not have access to the '<GUID>' database, or the database does not exist.

**Expected behavior**
I expect the role created in Tabular Editor to filter the data as specified in the rule of the role, and that "View as" functionality is not showing any errors.

**Observed behavior**
Roles created in Tabular Editor is doing something with the underlying model in Power BI. Hard to say what, but it is not working as expected. Maintaining roles in Tabular Editor is fine and working as expected. Only creating new roles gives this behavior.

**Application specifics**
 - Tabular Editor 2.21.1
 - Semantic Engine used: tested with these two versions
 * Power BI Desktop 2.123.742.0 64-bit (cloud)
 * Power BI Desktop for Report Server (September 2023)
 - Model Compatibility Level: compatibility level is the one provided by Power BI Desktop

**Additional context**
When creating the role in Power BI Desktop, the role is behaving as expected.
After creating the role in Power BI Desktop, the rules of the roles can be maintained in Tabular Editor. 
I.e. only creating new roles gives issues. Maintaining the roles in Tabular Editor is fine.

**Comment by otykier** [comment]
Did you set the ModelPermission property on the role to “Read”?

If you did, then I’m afraid this is not a Tabular Editor issue, since TE simply uses the AMO/TOM client library, provided by Microsoft, to make modifications to your model, including adding roles. As such, you would see the same behavior if you used a different tool, such as SSMS, to add the roles. In this case, please raise a support ticket with Microsoft.

**Comment by sorenhakola** [comment]
"Read": 
Ah, I did not see that coming. Thanks for pointing this option out! Somehow I totally missed this. Seems to be working after setting the property to Read.

Anyways, I really appreciate the help. Now I can continue with maintaining 100+ roles with C# script
