### ISSUE TITLE
Use new SerializeDatabaseToFolder() method for TMDL export

### ISSUE THREAD

**Issue by mthierba** [TabularEditor/TabularEditor#1164]
https://github.com/TabularEditor/TabularEditor/blob/718b4468e9c6ecac0b6a039317731252ec94d4f1/TOMWrapper/TOMWrapper/TabularModelHandler.FileHandling.cs#L317

TMDL Preview-7 introduced the `TmdlSerializer.SerializeDatabaseToFolder(database, folder)` API which should be used here instead. This will serialize the full database, not just the model, hence provides a full equivalent to TMSL/BIM. Database properties are exported into a new `database.tmdl` file with this API. This preserves the CompatLevel settings among others.

**Comment by otykier** [comment]
Thanks Mathias. We'll use this method going forward in both TE2 and TE3.
