### ISSUE TITLE
Automating Mass Testing of DAX Expressions for Bachelor Thesis.

### ISSUE THREAD

**Issue by AnasBout** [TabularEditor/TabularEditor#1167]
I am currently a student enrolled at the Technical University of Cologne in Germany. I'm working on my bachelor's thesis, focusing on AI models for writing DAX expressions, like Calculated Tables, Calculated Columns and Measures. I'm stuck with a challenge and wanted to ask if you could give some tips on how I can overcome this.

I have over 2000 DAX expressions that I need to automatically test. These DAX Expression are created by an AI Modell. Here's what I'm looking to find out for each expression:
- If it's syntactically and semantically valid.
- Type of errors (syntax or semantic) and specific error messages.
- For valid expressions, the number of columns and rows returned.

The thing is that all of these DAX expressions are related to one dataset. I am using the Northwind Dataset.

I have tried to do this in Batch's Tabular Editor 2 using C#, but it is just not working. The new expressions are added but when I save them to the model, if an expression has an error it does not let me do it.

Thank you so much,
Sincerely,
Anas Boutmitar

**Comment by otykier** [comment]
Hi @AnasBout 
TE2 does not have a way to validate the syntax of a DAX expression. However, Analysis Services/Power BI should inform you if there are any errors, after saving the model changes. In my testing against SSAS 2022, it should be possible to save changes to a model, even if it contains measures/calculated columns/calculated tables with invalid DAX syntax, but there could be other situations where Analysis Services/Power BI will prevent you from saving changes.

After saving, you can inspect the ErrorMessage property of an object. For example, here, I've set the DAX expression of a calculated table to "XXX". After saving, the table will be in an error state, and I can access the error message on the table from C# as shown:

<img width="913" alt="image" src="https://github.com/TabularEditor/TabularEditor/assets/8976200/57f4e5f9-ee89-4fad-a4b9-fe4d096eff1f">

If there are no errors, you can get the column names and data types after saving:

<img width="752" alt="image" src="https://github.com/TabularEditor/TabularEditor/assets/8976200/faae9473-afb4-4e74-bfa9-e9878ff6935a">

You cannot know the number of rows within a calculated table, however, until the model has been refreshed. So if this is what you need, it may be easier to just execute the DAX directly through the C# script, without adding the DAX to a new calculated table:

<img width="419" alt="image" src="https://github.com/TabularEditor/TabularEditor/assets/8976200/29568781-cecd-42c9-88b7-d6aab1ce4173">

`EvaluateDax` returns a [DataTable](https://learn.microsoft.com/en-us/dotnet/api/system.data.datatable?view=netframework-4.7.2) object when the resulting expression is a table. It is straightforward to obtain number of rows and columns from a DataTable object.
