### ISSUE TITLE
Duplicate Table doesn't work

### ISSUE THREAD

**Issue by fosis** [TabularEditor/TabularEditor#1169]
**Describe the bug**
I'm trying to duplicate measure table in Tabular Editor 2.21.1
So the table duplicates in TE, then I save changes to connected database, the duplicated table shows up in PBI Desktop, but when I click 'Apply Changes' in PBI, the duplicated table disappears without any information nor popup.

**To Reproduce**
1. Duplicate Table in TE.
2. Save changes to connected database (Ctrl + S).
3. Click 'Apply Changes' in PBI Desktop.
4. Duplicated table disappear from PBI.

**Expected behavior**
The table should not disappear.

**Observed behavior**
Instead of clicking 'apply chnages' I can also click 'Refresh now', then i get this error: 
'Object reference not set to an instance of an object.
![obraz](https://github.com/TabularEditor/TabularEditor/assets/22603652/e72ae2c5-536d-4360-87ee-0b3707a3cc8b)

**Application specifics**
 - Tabular Editor 2.21.1
 - Power BI Desktop Version: 2.124.1052.0 64-bit (december 2023)

**Comment by otykier** [comment]
[Power BI does not support adding/editing/removing tables through External Tools](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations). One possible workaround is to save your report in the [.pbit format](https://learn.microsoft.com/en-us/power-bi/developer/projects/projects-overview), and then edit the Model.bim file using Tabualr Editor.
