### ISSUE TITLE
Unable to add or delete columns or tables from model if model is opened from TMDL folder.

### ISSUE THREAD

**Issue by ganeytd** [TabularEditor/TabularEditor#1176]
**Describe the bug**
After loading model from TMDL folder I am unable to add or remove columns, tables, relationships, calculated tables, partitions, or columns.  I get an error message instead.

**To Reproduce**
1. Open Tabular Editor 2.22.0
2. File menu -> Open -> From Folder
3. Choose a TMDL folder model
4. Attempt to add or remove columns, tables, relationships, calculated tables, partitions, or columns. 

**Expected behavior**
I would be able to add or remove columns, tables, relationships, calculated tables, partitions, or columns. 

**Observed behavior**
I get the following error message instead:
![image](https://github.com/TabularEditor/TabularEditor/assets/59297930/e9cbdcbc-e151-4f5a-bbff-1d57b1aab66c)

If I try to create a new relationship I get an error with a stack trace which I will provide in the bottom section.
![Screenshot 2024-02-06 121239](https://github.com/TabularEditor/TabularEditor/assets/59297930/bf809368-8153-4ae7-b062-d1a0f000c27e)

**Application specifics**
 - Tabular Editor 2.22.0
 - Semantic Engine used: TMDL folder
 - Model Compatibility Level: 1500

**Additional context**
I do not have this issue if I open a model from a database and the issue does not exist just by saving to TMDL.  It needs to be opening a model from a TMDL folder.

I understand that TMDL is in preview, so this may be a TMDL issue.

***Here is that stack trace:***
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: mode
   at Microsoft.AnalysisServices.Tabular.JsonSerializer.SerializeObject(MetadataObject metadataObject, SerializeOptions options, Int32 dbCompatibilityLevel, CompatibilityMode mode)
   at TabularEditor.TOMWrapper.Undo.UndoAddRemoveAction..ctor(ITabularObjectCollection collection, TabularNamedObject obj, UndoAddRemoveActionType actionType)
   at TabularEditor.TOMWrapper.TabularObjectCollection`1.InternalAdd(T item)
   at TabularEditor.TOMWrapper.SingleColumnRelationship.CreateNew(Model parent, String name)
   at TabularEditor.TOMWrapper.Model.AddRelationship()
   at TabularEditor.UI.Actions.CreateRelationshipAction.Execute(Object arg)
   at TabularEditor.UI.UIController.ContextMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
TabularEditor
    Assembly Version: 2.22.8784.24138
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/TabularEditor.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
TOMWrapper
    Assembly Version: 2.22.8784.24134
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/TabularEditor.exe
----------------------------------------
Microsoft.AnalysisServices.Tabular
    Assembly Version: 19.74.2.0
    Win32 Version: 16.0.117.17
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/Microsoft.AnalysisServices.Tabular.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.AnalysisServices.Core
    Assembly Version: 19.74.2.0
    Win32 Version: 16.0.117.17
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/Microsoft.AnalysisServices.Core.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Microsoft.AnalysisServices.SPClient.Interfaces
    Assembly Version: 19.74.2.0
    Win32 Version: 16.0.117.17
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/Microsoft.AnalysisServices.SPClient.Interfaces.DLL
----------------------------------------
Microsoft.AnalysisServices.Tabular.Json
    Assembly Version: 19.74.2.0
    Win32 Version: 16.0.117.17
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/Microsoft.AnalysisServices.Tabular.Json.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.Identity.Client
    Assembly Version: 4.58.1.0
    Win32 Version: 4.58.1.0
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/Microsoft.Identity.Client.DLL
----------------------------------------
Microsoft.IdentityModel.Abstractions
    Assembly Version: 7.2.0.0
    Win32 Version: 7.2.0.50110
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/Microsoft.IdentityModel.Abstractions.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Buffers
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/System.Buffers.DLL
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 7.0.0.2
    Win32 Version: 7.0.423.11508
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/System.Diagnostics.DiagnosticSource.DLL
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.2
    Win32 Version: 4.6.31308.01
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/System.Memory.DLL
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/System.Numerics.Vectors.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/TabularEditor.exe
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
FastColoredTextBox
    Assembly Version: 2.16.24.0
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/TabularEditor.exe
----------------------------------------
Crad.Windows.Forms.Actions
    Assembly Version: 1.3.0.0
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/TabularEditor.exe
----------------------------------------
Antlr4.Runtime
    Assembly Version: 4.6.0.0
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/TabularEditor.exe
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.2.0
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/TabularEditor.exe
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 2.22.8784.24138
    CodeBase: file:///C:/Apps/TabularEditor.2.22.0/TabularEditor.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by otykier** [comment]
Thanks for reporting. Bug confirmed! We'll provide a fix soon.

**Comment by otykier** [comment]
[Fixed](https://github.com/TabularEditor/TabularEditor/releases/tag/2.22.1)! Thanks again for reporting.

**Comment by ganeytd** [comment]
Works.  Thank you!
