### ISSUE TITLE
DependsOn.Deep does not show for objects with the same value as a keyword

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor#1178]
**Describe the bug**
DependsOn.Deep does not capture dependencies in which the dependent object has the same name as a DAX keyword.

**To Reproduce**
1.Rename a table to 'Calendar'
2. Create a new measure 'test' with the following DAX: COUNTROWS(Calendar)
3. Run the following c# script

var m = Model.Tables["Calendar"].Measures["test"];
m.DependsOn.Deep().Output();

4. No objects show even though the Calendar table is a dependent object. This is because Calendar is also a DAX function.

**Expected behavior**
The calendar table should show as a dependency.

**Application specifics**
 - Tabular Editor 2.21.1

**Comment by otykier** [comment]
Good catch, thanks for reporting!

**Comment by otykier** [comment]
Fixed in [2.23.0](https://github.com/TabularEditor/TabularEditor/releases/tag/2.23.0), thanks for reporting!
