### ISSUE TITLE
Error occurred during deployment Invalid Token 

### ISSUE THREAD

**Issue by aidarwin** [TabularEditor/TabularEditor#1180]
**Describe the bug**
Error occurred during deployment
Invalid Token

![image](https://github.com/TabularEditor/TabularEditor/assets/103006306/32072039-983c-4145-a15b-ecd269178e4d)

**To Reproduce**
1. Add a Calculation Group 'Time Intelligence'
2. Add a Calculation Item called 'MTD' assign this formula CALCULATE ( SELECTEDMEASURE (), DATESMTD ( 'Date'[Date] ) )
3. Click on 'Model' then 'Deploy', Next, Next, Next then Deploy

![image](https://github.com/TabularEditor/TabularEditor/assets/103006306/42d9c8d2-b27b-4f18-917f-4ff8e4a65f3d)

**Expected behavior**
Calculation Group items deployed to PBIX file without error.

**Observed behavior**
Before getting error
![image](https://github.com/TabularEditor/TabularEditor/assets/103006306/b0e5c4cd-6dd0-487d-96be-8e28c8eb4c26)

After Error
![image](https://github.com/TabularEditor/TabularEditor/assets/103006306/87699dae-cd98-44e1-8f07-3aa31b49844c)

**Application specifics**
 - Tabular Editor 2.X version: [e.g. 2.22.0]
 - Semantic Engine used: [e.g. Power BI Desktop  2.124.2028.0 64-bit (December 2023)
 - Model Compatibility Level: Unsure

**Additional context**
Needing calculation groups for time intelligence formulas
Experienced on original report
Tried creating a brand new report with new queries and just one dax measure.
Tried deploying without calculation group (no changes)

**Comment by otykier** [comment]
It is not possible to perform a Deploy against Power BI Desktop. To make changes to a local pbix file loaded in Power BI Desktop, open the model in Tabular Editor, make the changes, then simply hit “Save” (Ctrl+S). The Deploy action is intended when you want to publish the model to the Power BI Service (through the XMLA endpoint).
