### ISSUE TITLE
Unable to add fields in the Value section of Matrix after adding Calculation Group

### ISSUE THREAD

**Issue by KishorDute** [TabularEditor/TabularEditor#1181]
!!! Please make sure you're using the latest version of Tabular Editor 2.X before submitting a bug !!!
!!! For Tabular Editor 3 issues, go here -> https://github.com/TabularEditor/TabularEditor3/issues !!!

**Describe the bug**
Unable to add fields in the Value section of Matrix after adding Calculation Group. Even after deleting the group to problem is not resolved.

**Comment by otykier** [comment]
When adding a calculation group to your model, [implicit measures must be disabled](https://learn.microsoft.com/en-us/analysis-services/tabular-models/calculation-groups?view=asallproducts-allversions#limitations). To restore the ability to add implicit measures to visuals, set `DiscourageImplicitMeasures` on the Model object to *false* after removing the calculation groups:

![image](https://github.com/TabularEditor/TabularEditor/assets/8976200/048a0c17-6eb1-4141-8ac0-7cd80bb4a1ce)

**Comment by KishorDute** [comment]
Thank you.. but it means you cannot have Calculation groups and implicit measures to visuals together.

**Comment by otykier** [comment]
Correct (that’s a limitation of Power BI - not Tabular Editor)
