### ISSUE TITLE
CLI - Save as TMDL

### ISSUE THREAD

**Issue by ScottThompsonNH** [TabularEditor/TabularEditor#1183]
We want to try to use the TMDL structure.  It does not seem like the CLI has a way to save as TMDL folder structure.  It always comes out as JSON when using -F.

It would be great if we could flag which folder structure we want so that TMDL is an option.

Additional context:

We use the master model pattern, so even if we work directly in TMDL, we need the scripting in order to generate the child model.  I am hoping to do either:

TMDL > apply child script >TMDL
or if the scripting can't work effectively directly with TMDL then
TMDL > BIM
BIM > apply child script > TMDL

But either way, it can't work without having a save as TMDL option in the command line

Also, we are using TE3, but I'm posting here as CLI is not in TE3 yet.

**Comment by otykier** [comment]
You should use the -TMDL flag instead of -F to save as TMDL :)

**Comment by ScottThompsonNH** [comment]
Thanks, will try that out!  I did not thing to use /? for the latest options.
