### ISSUE TITLE
Importing from Fabric Warehouse 

### ISSUE THREAD

**Issue by SwiftDerek** [TabularEditor/TabularEditor#1184]
Hi, I'm following the directions for connecting with Azure MFA to a Fabric Warehouse so I can import tables to a semantic model. 

But just want to make sure this is supported? The last section on authenticating with server principal or SQL authentication once it's been saved to the model might stop me with that as I'm not sure that's supported in Fabric just yet.

**Comment by otykier** [comment]
Hi @SwiftDerek - apologies for the late reply.

> I'm following the directions for connecting with Azure MFA to a Fabric Warehouse 

Which directions are you referring to here? Note that Tabular Editor 2 only supports importing tables using legacy (provider) data sources and SQL-based partitions. In theory, it should work with Fabric, but semantic models created in Power BI Desktop (or Tabular Editor 3), generally use implicit data sources with M-based partitions.

**Comment by mvmeasure** [comment]
Hi both,

I hope this applies to the same question.

I want to create a new semantic model in import mode in Tabular Editor 2, connected to a Fabric warehouse (or Lakehouse) SQL endpoint.

I managed to connect to the data in Tabular Editor 2 with the MSOLEDBSQL driver as described here (https://docs.tabulareditor.com/te2/Importing-Tables.html) for the Azure SQL Database. However, when I deploy the model to Fabric, I can't process the model and get the following error:

Exception has been thrown by the target of an invocation.;Cannot set the AccessToken property if 'Authentication' has been specified in the connection string. The exception was raised by the IDbConnection interface. Table: products.

The documentation points out that "When deploying your model to Analysis Services, you will most likely need to specify other credentials, such as a Service Principal application ID and secret or a SQL account, in order for Analysis Services to authenticate itself against the source when refreshing table data. This can be specified using TMSL or SSMS post-deployment, or you can set this up as [part of your CI/CD deployment pipeline](https://tabulareditor.com/2020/06/20/DevOps5.html#creating-your-first-release-pipeline)."

But the link is broken.

How do I set up the connection correctly on the Fabric/Power BI side?

**Comment by otykier** [comment]
I would recommend setting up a dummy model in Power BI Desktop, which loads data from the same source. Then, using Tabular Editor 2, you can copy the table/partition metadata from that dummy model over to the actual model you're working on. That way, the table will be configured in the same way as what Power BI Desktop does, and that should allow the service to perform the refresh.

Note that Tabular Editor 2 will not be able to update the table schema, or import additional tables that use the M-based partitions. So for that, you'll need to (temporarily) switch back to the MSOLEDBSQL approach that you used before, or once again copy a table from a dummy model created in Power BI Desktop.
