### ISSUE TITLE
Power BI Desktop can't open TMDL from TE: Parsing error type - InvalidLineType

### ISSUE THREAD

**Issue by mdieperink** [TabularEditor/TabularEditor#1185]
**Describe the bug**
Trying to open a TMDL folder saved by TE in Power BI Desktop gives the following error:

```
There's a problem with the definition content in your Power BI Project.
TMDL Format Error:
	Parsing error type - InvalidLineType
	Detailed error - Unexpected line type: Other!
	Document - './database'
	Line Number - 1
	Line - '﻿database SemanticModel'
```

**To Reproduce**
1. Save a model in Power BI Desktop as TMDL
2. Open TMDL folder in TE2
3. Click save
4. Open model in Power BI Desktop

**Expected behavior**
That Power BI can open a TMDL model saved by TE

**Observed behavior**

**Application specifics**
 - Tabular Editor 2.X version: 2.22.8804.18829
 - Semantic Engine used: Power BI Desktop
 - Model Compatibility Level: 1601

**Additional context**
I tried all the different Encoding and Newline style options in Serialization options, all give the same error.

**Comment by otykier** [comment]
Please grab the [latest version of TE](https://github.com/TabularEditor/TabularEditor/releases/tag/2.23.0), open then model and save it again, then try to open it in Desktop.
