### ISSUE TITLE
DataCoverageDefinition not taken into account. Tabular Editor fails to connect after deploying model.

### ISSUE THREAD

**Issue by HennySpeelman** [TabularEditor/TabularEditor#1186]
Description:
Fail to re-connect to deployed model after altering the datacoveragedefinition property on a direct query partition of my fact table in the semantic model. Property doesn't seem to be available when opened with SSMS.

Here are my actions:
I first created a data model in Power BI with a fact table (DirectQuery mode).
Then I published this to a premium workspace.
I connected to this model with TE2.23.0 -> this works
- Changed the compatibility mode to 1603
- Duplicated partition of the table I want to make hybrid
- Changed the data storage mode of the new partition to 'import'
- Changed the names of the partitions (DQ and import)
- For the DQ partition, I added the 'datacoveragedefinition':  'FactTable'[Date Key] < 20230101
- I published this model -> this works
- I close Tabular editor and reopen it
- I get the error 'This object does not have any child collections' (error connecting to database)

I would have expected to be able te reconnect and check whether the property was there.
When checking the query optimizer in Power BI desktop (with a live connection to the published data model), I still see a DAX and Directquery, so I assume the property is not deployed correctly. Deploying this option via SSMS also does not work. (succesful commit, but property nowhere to be found after deployment)

Compatibility level:
![image](https://github.com/TabularEditor/TabularEditor/assets/61652027/be2543e1-c433-4c6c-850d-c63ce30b6d44)

Import partition:
![image](https://github.com/TabularEditor/TabularEditor/assets/61652027/62f62674-266a-4b46-b142-8dcd801604a9)

Direct Query partition:
![image](https://github.com/TabularEditor/TabularEditor/assets/61652027/3b138403-ce81-4d7b-b50c-f1efcaf24ce3)

Error:
![image](https://github.com/TabularEditor/TabularEditor/assets/61652027/a5945c26-68e1-4724-9d3b-13dccac57bf9)

**Comment by otykier** [comment]
Thanks for reporting this. I was able to reproduce the issue when re-opening the model in Tabular Editor, and have just published an updated version where this is fixed: https://github.com/TabularEditor/TabularEditor/releases/tag/2.23.1

**Comment by HennySpeelman** [comment]
Great! it works.

Thanks for this lightning fast solution.
