### ISSUE TITLE
'Access Denied' Error saving TMDL structure back to original source folder

### ISSUE THREAD

**Issue by jcberg3** [TabularEditor/TabularEditor#1188]
!!! Please make sure you're using the latest version of Tabular Editor 2.X before submitting a bug !!!
!!! For Tabular Editor 3 issues, go here -> https://github.com/TabularEditor/TabularEditor3/issues !!!

**Describe the bug**
Using latest TE 2.23.1 version

I have a process which simply loads up a model from disk, executes a c# script to make a few updates, and "deploys" back to the source using the -D switch and no extra parameters. (i.e. TabularEditor.exe [path to tmdl folder] -D -S [c# script path] -V )

Everything works as expected, the model loads, the c# script successfully executes, however the updated model fails to save back to disk with "Save failed: Access to the path [path to TMDL folder] is denied."

I have tried running as an admin, making sure no other processes have the file opened, etc. The process works as expected loading a .bim file.

I can open this model in TE3, make updates, and save back just fine as well.

**To Reproduce**
1. Execute TabularEditor.exe from a command line referencing a TMDL folder, with the -D switch, apply a C# script with the -S switch to make updates

**Expected behavior**
The updates are processed and the resulting model is serialized back out to the source folder in the original TMDL format

**Observed behavior**
The updates are processed, however the model fails to serialize back out to the folder with an "Access denied" error

**Application specifics**
 - Tabular Editor 2.X version: 2.23.1
 - Semantic Engine used: PowerBI_V3
 - Model Compatibility Level: [e.g. 1400, 1500, 1520, etc.]

**Additional context**

**Comment by jcberg3** [comment]
Great chatting with you today at fanconf @otykier !

**Comment by otykier** [comment]
Likewise @jcberg3 :)

I'm happy to let you know that this bug was solved in [2.24.0](https://github.com/TabularEditor/TabularEditor/releases/tag/2.24.0). Thanks for reporting it!
