### ISSUE TITLE
BPA with Azure Function

### ISSUE THREAD

**Issue by eudesmcf** [TabularEditor/TabularEditor#1196]
**What are you trying to achieve?**
I'm trying run BPA for all Capacity Reports. Now I have a azure function (C#) for connect and take some datas and I thinking in import BPA for same solution.  Would you have any guidance? Could it be a future feature for BPA to be packaged in Nuget?

**What have you tried so far?**
I see that solution [https://github.com/DaveRuijter/BestPracticeAnalyzerAutomation](url), but they solution is on Power Shell.

**Comment by otykier** [comment]
@eudesmcf we are considering packaging TomWrapper and the BPA as a separate NuGet so it can be included in any C# project. However, I can't give an ETA at the moment.

As a workaround, until such a NuGet is made available, you can deploy the portable version of Tabular Editor as part of your Function App, and then use C# to invoke the Tabular Editor CLI. This assumes your Azure Function environment is configured for Windows OS.

**Comment by eudesmcf** [comment]
Hello @otykier. I'm testing inputing you suggestions.

While I'm at it, I'm having trouble connecting to TE2 with the Service Principal via power shell. Can you tell me if the code below would make sense or if I'm making a mistake with the syntax?

```
$WorkspaceConnection = Myworksapceendpoint
$TenantId = MyteanantId
$AppId = MyappId
$AppSecret = Mysecret
$Catalog = Mydatabase

$TabularEditorPath = "C:\PowerBI_BPAA\TabularEditorPortable\TabularEditor.exe"
$TabularEditorBPARulesPath = "https://raw.githubusercontent.com/microsoft/Analysis-Services/master/BestPracticeRules/BPARules.json"
$Output = "C:\PowerBI_BPAA\TabularEditorPortable\Export"

$connectionString = "Provider=MSOLAP;Data Source=$WorkspaceConnection;User ID=$AppId@$TenantId;Password=$AppSecret;Integrated Security=SSPI;"

$argumentList = @(
   "$connectionString",
    "-A", "$TabularEditorBPARulesPath",
    "-TRX", "$Output",
    "$Catalog"
)

$p = Start-Process -Wait -FilePath $TabularEditorPath -ArgumentList $argumentList -NoNewWindow

exit $p.ExitCode
```

Thank you for your help!

**Comment by otykier** [comment]
When using Service principals, you have to add `app:` to the connection string, in front of the `$AppId`. Also, the `Integrated Security` part is not relevant for service principal auth. So your connection string should look like this:

```powershell
$connectionString = "Provider=MSOLAP;Data Source=$WorkspaceConnection;User ID=app:$AppId@$TenantId;Password=$AppSecret"
```

Hope this helps.
