### ISSUE TITLE
TMDL models not shown in recent models

### ISSUE THREAD

**Issue by mlonsk** [TabularEditor/TabularEditor#1199]
**Describe the bug**
TMDL models are not shown in 'Recent Files'

**To Reproduce**
1. Open a TMDL model
2. Go to File > Recent Files
3. TMDL model is not shown

**Expected behavior**
TMDL models show up under 'Recent Files
**Observed behavior**
A clear and concise description of what happened. Include any error messages or stack traces if possible. Also, feel free to add screenshots or recordings showing the problem.

**Application specifics**
 - Tabular Editor 2.X version: 2.24.1
 - Semantic Engine used: TMDL locally stored model

![image](https://github.com/TabularEditor/TabularEditor/assets/11939114/04800e88-0163-475c-a087-24bd1d6fe5c7)

**Comment by otykier** [comment]
Fixed in [2.25.0](https://github.com/TabularEditor/TabularEditor/releases/tag/2.25). Thanks!
