### ISSUE TITLE
database.tmdl not shown when opening model file

### ISSUE THREAD

**Issue by mlonsk** [TabularEditor/TabularEditor#1200]
**Describe the bug**
When opening a model as a file, the database.tmdl is not shown in Tabular Editor 2. In Tabular Editor 3 it is shown - see screenshot for comparision. 

**To Reproduce**
1. Go to File > Open > From File
2. Navigate to TMDL source code
3. No database.tmdl file present 

**Expected behavior**
That database.tmdl is shown when opening a model from a file

**Application specifics**
 - Tabular Editor 2.X version: 2.14.1
 - Semantic Engine used: Local TMDL model

**Additional context**
<img width="1525" alt="image" src="https://github.com/TabularEditor/TabularEditor/assets/11939114/0669f493-0ba0-47d4-9552-b4e36b6dc1ee">

**Comment by otykier** [comment]
Fixed in [2.25.0](https://github.com/TabularEditor/TabularEditor/releases/tag/2.25). Thanks!
