### ISSUE TITLE
Can't connect to Azure SQL DB anymore via TE 2.24.0 - An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by mvdwielen** [TabularEditor/TabularEditor#1206]
**Describe the bug**
I am trying to connect to Azure SQL Server by adding a new data source in a TE model.
Regardless the provider I use (Microsoft SQL Server (SqlClient) / Microsoft SQL Server (OLE DB)) or the authentication type (ActiveDirectoryPassword, SQL Authentication) I keep getting the error: 'An attempt was made to access a socket in a way forbidden by its access permissions'

Connecting to the database via SQL Server Management using the same credentials is working fine.

**To Reproduce**
1. Start TE
2. Click on 'Data Sources' -> New Data Source (Legacy)
![image](https://github.com/TabularEditor/TabularEditor/assets/62689682/a6e763d6-affc-4815-88ca-dbc765b34ef3)
3. Click on 'Connection String'
4. Click on:
![image](https://github.com/TabularEditor/TabularEditor/assets/62689682/f9ea16fc-4e43-4694-9b29-7cbba99aebb0)
5. Enter server name, username and password and click on 'Test connection'
![image](https://github.com/TabularEditor/TabularEditor/assets/62689682/76ceeb37-2653-4ade-8a18-182469ad7893)
6. See error:
![image](https://github.com/TabularEditor/TabularEditor/assets/62689682/3b087c08-a8a1-4e89-aaa7-71cefae0f239)
7. See successful connection to SQL Server via SSMS on the same machine on whih TE is running"

![image](https://github.com/TabularEditor/TabularEditor/assets/62689682/04182475-067b-4c07-92d5-7c9d401b5ef6)

**Expected behavior**
A database connection to ASQL should work

**Observed behavior**
Connecting to ASQL is not working

**Application specifics**
 - Tabular Editor 2.X version: [e.g. 2.24.0]
 - Semantic Engine used: Power BI Desktop
 - Model Compatibility Level: 1605

**Additional context**

**Comment by mvdwielen** [comment]
issue is due to a change in VPN connection resulting in not bein able to connect anymore, closing the issue

**Comment by otykier** [comment]
Thanks for letting us know!
