### ISSUE TITLE
Can't calculate the calculation groups in TE 2

### ISSUE THREAD

**Issue by TinyTimothy2** [TabularEditor/TabularEditor#1208]
Using SSAS 2019
In TE3 trial i was able within the TE3 tool to calculate the calculation groups and they worked as expected.
I am limited TE2.  I can create the CGroups and deploy.  But i can never use them because they always have error:
''....needs to be recalculated or refreshed"

In SSAS 2019 using SSMS i have full refreshed the CG tables, but that does not work
I have fully refreshed the dimension table which they refer too, ie dim_Date.

In fact i can't go back to the model i did do in TE3 and create new CG (i can create them, but they all have the same error)

**Comment by otykier** [comment]
TE2 does not have a built-in feature that lets you perform refresh operations, including calculate refresh. You would have to use SSMS or a [C# script](https://docs.tabulareditor.com/te2/Useful-script-snippets.html#querying-analysis-services) for that.

What error message are you seeing when you attempt to perform the refresh in SSMS? Maybe the CG is configured incorrectly or has a bad DAX expression?

**Comment by TinyTimothy2** [comment]
No. CG was all good.  In SSMS you have to highlite the SSAS db, rt click, PROCESS Database, and at that point a message pops up with option to recalc.  It is only available at the db level.  It is not available at the table level.
I have not seen this in any documentation.

**Comment by otykier** [comment]
So it works now? Can we close the ticket?

**Comment by TinyTimothy2** [comment]
yes thank you
