### ISSUE TITLE
Accessing objects from a .tmdl file for unit tests

### ISSUE THREAD

**Issue by lorcan17** [TabularEditor/TabularEditor#1212]
**What are you trying to achieve?**

I aim to facilitate the development of unit tests for our Power BI datasets by converting objects from a .tmdl file into a Python dictionary. This approach will enable us to execute unit tests to ensure that the dataset's model adheres to our expectation and no errors/bugs are introduced. For instance, we want to assert that the column object `LOCATION_NAME` in the `Location` table has `dataType = string`. This effort is crucial for preventing unexpected errors in our dataset.

```python
# Example usage:
# Parse the .tmdl content
parsed_dict = parse_tmdl(tmdl_content)

# Assert that column 'LOCATION_NAME' in table 'Location' has dataType = string
assert parsed_dict['Location']['LOCATION_NAME']['dataType'] == 'string'

# Print the parsed dictionary (for verification)
print(parsed_dict)
```

**What have you tried so far?**

I've begun developing a Python script to convert .tmdl files into Python dictionaries. However, I'm encountering challenges with extracting the `source` element from tables due to multiline issues. I'm seeking guidance on whether someone has already developed a script for this purpose or if there are existing solutions online that I could utilize.

**Comment by otykier** [comment]
Since this is a Python question, I am not sure how this question relates to Tabular Editor? Maybe I'm missing something?

**Comment by lorcan17** [comment]
I was checking if anyone in the community has worked on something similar. I thought this would be the best medium since users familiar with TMDL files would likely be Tabular Editor users. If useful for anyone else. this is what worked for me

`class Tmdl:
    def __init__(self, tmdl_file):
        self.tmdl_file = tmdl_file
        self.tmdl = self.parse_tmdl(tmdl_file)
        
    def parse_tmdl(self, tmdl_file):
            def get_indentation(line):
                stripped_line = line.strip()
                if not stripped_line:  # Handle empty lines
                    return None
                else:
                    return len(line) - len(stripped_line)

            with open(tmdl_file, 'r') as file:
                lines = file.readlines()
                lines = [line for line in lines if line.strip()]
            tmdl_dict = {}
            current_level1 = None
            current_level2 = None
            i = 0

            while i < len(lines):

                line = lines[i]
                stripped_line = line.strip()

                indentation = get_indentation(line)

                if indentation == 1:
                    # Level 1 - Object Declaration
                    current_level1 = stripped_line
                    tmdl_dict[current_level1] = {}
                elif indentation == 2:
                    # Level 2 - Object Properties and Child Objects
                    if stripped_line.endswith('='):
                        property_lines = []
                        property_lines.append(stripped_line)
                        i += 1
                        while i < len(lines):
                            next_line = lines[i]
                            next_stripped_line = next_line.strip()
                            if get_indentation(next_line) > indentation:
                                property_lines.append(next_stripped_line)
                            else:
                                break
                            i += 1

                        combined_property = '\n'.join(property_lines)
                        key, value = combined_property.split('=', 1)
                        tmdl_dict[current_level1][key.strip()] = value.strip()
                        i -= 1  # Step back to process the next line correctly
                    elif '=' in stripped_line:
                        # Expression properties
                        key, value = stripped_line.split('=', 1)
                        if i + 1 < len(lines):
                            next_line = lines[i + 1]
                            next_stripped_line = next_line.strip()
                            if next_line.strip():
                                if get_indentation(next_line) > indentation:
                                    current_level2 = key.strip()
                                    tmdl_dict[current_level1][current_level2] = {}  
                                    tmdl_dict[current_level1][current_level2]["value"] = value.strip()
                                else:
                                    tmdl_dict[current_level1][key.strip()] = value.strip()
                        else:
                            tmdl_dict[current_level1][key.strip()] = value.strip()
                    elif ':' in stripped_line:
                        # Non-expression propertiesq
                        key, value = stripped_line.split(':', 1)
                        tmdl_dict[current_level1][key.strip()] = value.strip()
                    else:
                        if i + 1 < len(lines):
                            next_line = lines[i + 1]
                            next_stripped_line = next_line.strip()
                            if next_line.strip():
                                if get_indentation(next_line) > indentation:
                                    current_level2 = stripped_line
                                    tmdl_dict[current_level1][current_level2] = {}  
                                else:
                                    print("unexpected behaivour")



                elif indentation == 3 and current_level2:
                    # Level 3 - Child Object Properties
                    if stripped_line.endswith('='):
                        property_lines = []
                        property_lines.append(stripped_line)
                        i += 1
                        while i < len(lines):
                            next_line = lines[i]
                            next_stripped_line = next_line.strip()
                            if not next_stripped_line:  # Skip empty lines
                                i += 1
                                continue
                            if next_stripped_line and get_indentation(next_line) > indentation:
                                property_lines.append(next_stripped_line)
                            else:
                                break
                            i += 1

                        combined_property = '\n'.join(property_lines)
                        key, value = combined_property.split('=', 1)
                        tmdl_dict[current_level1][current_level2][key.strip()] = value.strip()
                        i -= 1  # Step back to process the next line correctly
                    elif '=' in stripped_line:
                        # Expression properties
                        key, value = stripped_line.split('=', 1)
                        tmdl_dict[current_level1][current_level2][key.strip()] = value.strip()
                    elif ':' in stripped_line:
                        # Non-expression properties
                        key, value = stripped_line.split(':', 1)
                        tmdl_dict[current_level1][current_level2][key.strip()] = value.strip()

                i += 1

            return tmdl_dict
    
`

**Comment by otykier** [comment]
Thanks for sharing your solution :-)

**Comment by hski-github** [comment]
Hello @lorcan17 , have you been able to finish your TMDL parser in Python? I am looking for such a parser to extract certain information from TMDL for documentation of semantic model of our Power BI dashboard development.

**Comment by Atzingen** [comment]
hey @lorcan17 and @lorcan17 I had a similar problem (parse tmdl files) to other uses and did not find a parser that worked out of the box.
If you are interested i made a python library to parte all the files from a powerbi project.
https://pypi.org/project/tmdl-parser/
just pip install tmdl-parser

here is the full source code https://github.com/Atzingen/tmdl-parser

hope it  help others with same need
