### ISSUE TITLE
Version 2.25 - Cannot connect to models in the service

### ISSUE THREAD

**Issue by thedaxshepherd** [TabularEditor/TabularEditor#1223]
**Describe the bug**
Using version 2.25 - both the installed version and portable - I cannot connect to a model in the service. It is not opening the authentication window. 

It works in Tabular Editor 3 as well as both the installed and portable version 2.24.1.

**To Reproduce**
1. Go to File
2. Open -> From DB...
3. For Server: put the URL of the workspace

**Expected behavior**
The authentication window should appear and once authenticated the list of the models for that workspace should be presented. 

This is the window that is not opening so I can authenticate:
![Authenticate](https://github.com/user-attachments/assets/51f3db10-9173-43cb-ae2d-aa5f58ad1e86)

**Observed behavior**

This is the message it is giving me:
![Can't Connect](https://github.com/user-attachments/assets/c1b36d1c-f08a-4d2e-b65d-989c007ce68f)

**Application specifics**
 - Tabular Editor 2.X version: 2.25

**Additional context**
I have done a number of uninstall the 2.25 version and reinstall. I have also installed the 2.24.1 version and it works fine. I have tried both portable versions to try and narrow down the issue.

**Comment by otykier** [comment]
This sounds like the same issue as [this](https://github.com/TabularEditor/TabularEditor3/issues/1322). Could you try to enter the email of the account you wish to use to connect in the “Username” field (set the authentication type to “Username and password”).

**Comment by thedaxshepherd** [comment]
Yes, that method works. It opens up the authentication window and I am able to connect once I select the account.

**Comment by otykier** [comment]
Thanks for confirming. It should also be possible to specify the username as part of the connection string in the **Server** textbox

![image](https://github.com/user-attachments/assets/6a6cf81d-25a1-4f91-bbd1-cec1faed06a0)


`
Data Source=<servername>;User ID=<username>
`

At least this way, Tabular Editor will store the connection string in the dropdown, saving you a few clicks and key strokes the next time you sign in.
