### ISSUE TITLE
Column Descriptions Revert Back to Blank After Script

### ISSUE THREAD

**Issue by MarcusUnell** [TabularEditor/TabularEditor#1229]
I've created a script in C# that takes the source table of the Table in Power BI (through the expression in the partition) and writes it into the description of the table.

This all works fine and I can see the description being correct in TE, when I save this into PBI I can see that the script worked and everything is fine. After this "apply changes" comes up in PBI and when that's clicked the descriptions are reverted back to blank.

This is the script:

-------------------------------------------------
foreach(var t in Model.Tables)
{
    t.Description = "Created Table";
    foreach(var p in t.Partitions)
    {
        string toBeSearched = "Schema{[Name=";
        int ix = p.Expression.IndexOf(toBeSearched);
        if (ix != -1)
        {
            string code = p.Expression.Substring(ix + toBeSearched.Length);
            string Stopstring = ",";
            int iy = code.IndexOf(Stopstring);
            if (iy != -1)
            {
                string code2 = code.Substring(0,code.IndexOf(",Kind"));
                t.Description = 
                "Source Table: " 
                + System.Environment.NewLine 
                + code2;
            }
        }
    }
}
------------------------------------------------

Is there a setting I'm missing that can accomplish this? The problem seem to occur even when I manually change the table description in TE.

**Comment by MarcusUnell** [comment]
Thank you @mlonsk for the response, do you know if it's possible in TE2 or TE3?

For added information; the script above does make the tables without a source table be named "Created Table" even after the "Apply Changes" is pressed.

It feels like it's a setting or something, since I made a script that renames every column in the dataset too. But I can be wrong.

That script:

--------------------------------
public static class ColumnNameConverter
{
    public static void ConvertColumnNamesToProperCase(Model model)
    {
        foreach (var table in model.Tables)
        {
            foreach (var column in table.Columns)
            {
                if (column.Name.StartsWith("DIM") || column.Name.EndsWith("_KEY"))
                {
                    continue;
                }
                string[] parts = column.Name.Replace("_", " ").Split(' ');
                for (int i = 0; i < parts.Length; i++)
                {
                    parts[i] = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(parts[i].ToLower());
                }
                string properCaseName = string.Join(" ", parts);
                column.Name = properCaseName;
            }
        }
    }
}
ColumnNameConverter.ConvertColumnNamesToProperCase(Model);

**Comment by otykier** [comment]
As Morten said, this is not a limitation of TE2 or TE3. It's a limitation in Power BI Desktop. To work around this limitation, you can save your Power BI report as a [Power BI Projects folder](https://learn.microsoft.com/en-us/power-bi/developer/projects/projects-overview), and then load the model.bim file directly in TE2/TE3. This should let you apply descriptions to your table, which will remain in place the next time you open the report in Power BI Desktop.

As can be seen in the linked docs, making changes to tables (including their `Description` property), is not supported when external tools (Tabular Editor) is connected directly to the AS instance. However, it is supported when making the change to the metadata file:

<img width="674" alt="image" src="https://github.com/user-attachments/assets/fb870586-cfdb-4bf5-a849-1e94f45de4c6">

**Comment by MarcusUnell** [comment]
Thank you for explaining @otykier , I will try that! :D
