### ISSUE TITLE
Rules not getting fetched from URL using BPALib

### ISSUE THREAD

**Issue by Cyrillaf94** [TabularEditor/TabularEditor#1237]
!!! Please make sure you're using the latest version of Tabular Editor 2.X before submitting a bug !!!
!!! For Tabular Editor 3 issues, go here -> https://github.com/TabularEditor/TabularEditor3/issues !!!

**Describe the bug**
Thanks to the latest merge of BPALib from mt, I have started running some tests to run it in a CI pipeline
I was unable to load the rules to run the analysis from a url

**To Reproduce**

```bash
// Start a console app from the root of TabularEditor
dotnet new console -o TestApp
cd TestApp
// Add references and packages required
dotnet add reference ../BPALib.csproj
```

In Program.cs:
```cs
using System;
using BPA = TabularEditor.BestPracticeAnalyzer;
using TabularEditor.TOMWrapper;
// Initialize Analyzer
var bpa = new BPA.Analyzer();

// Load external rules from URL
string externalRulesUrl = "https://raw.githubusercontent.com/microsoft/Analysis-Services/master/BestPracticeRules/BPARules.json";
BPA.BestPracticeCollection suppliedRules = BPA.BestPracticeCollection.GetCollectionFromUrl(externalRulesUrl);


if (suppliedRules.Count == 0)
{
    Console.WriteLine("No rules loaded from the external URL. Please verify the URL and rule format.");
}
```

**Expected behavior**
Rules should be picked up from the url. I should get as output "Using System Proxy without credentials" as a log.

**Observed behavior**
Rules are not fetched from the url. 
No errors are raised. 

**Potential issue identified**
TabularEditor.UIServices.Preferences.Current (in BPA.Shims.cs) has no getter method.
This in turn throws an error at execution of GetUrl (request.Proxy = ProxyCache.GetProxy(url);) 

This fixes it for me if I modify the Current member:
```cs
internal static Preferences Current
        {
            get
            {
                return new Preferences();
            }
        }
```        

**Application specifics**
N/A

**Additional context**
Running on WSL2 - Ubuntu
dotnet version 8.0.401

**Comment by otykier** [comment]
Thanks for your contribution. I made a small change and have merged the PR.
