### ISSUE TITLE
2.25.0 TE does not work with new enhanced metadata PBIR preview format

### ISSUE THREAD

**Issue by timahenning** [TabularEditor/TabularEditor#1242]
**Describe the bug**
In TE, after updating column formatting, saving back to Power BI causes visuals to break.

**To Reproduce**
1. Open Power BI report in desktop with new enhanced PBIR preview option enabled.
2. Open TE and update table column format.
3. Save changes back to the connected database.

**Expected behavior**
I expect to see the format changes to be applied and visuals updated.

**Observed behavior**
Page visuals become corrupted and produce an error saying the model column does not exist.  Selecting the columns from the Power BI UI does not fix the issue.

**Application specifics**
 - Tabular Editor 2.25.8952.22276
 - Semantic Engine used: Power BI Desktop - 2.138.782.0 (24.11)
 - Model Compatibility Level: 1568

**Additional context**
Tester had two cups of coffee.

**Comment by otykier** [comment]
That sounds weird. Could you share a few screenshots to illustrate the issue? Also, what exactly did you set as the column format?

**Comment by timahenning** [comment]
I tried to reproduce in a simple Power BI new file, but could not reproduce the error.  I will see if I run into the situation again.
