### ISSUE TITLE
In Data-refresh window, Need an info column that shows refreshing-partition's parent Table name

### ISSUE THREAD

**Issue by apanasara** [TabularEditor/TabularEditor#1243]
In Data-refresh window, Need an info column that shows refreshing-partition's parent Table name

![image](https://github.com/user-attachments/assets/27776bd7-9f17-4825-b973-546b7a15a018)

**Comment by mlonsk** [comment]
Hi @apanasara 

Your request and screenshot seems to be about Tabular Editor 3, which we have a separate forum for: https://github.com/TabularEditor/TabularEditor3/discussions/categories/ideas

However, this is a request that we are already aware off and planning to build
