### ISSUE TITLE
Dark Mode Support for Tabular Editor 2 (/TE2)

### ISSUE THREAD

**Issue by mv-wrk** [TabularEditor/TabularEditor#1247]
Dark mode support for TE2 would be great. 

The latest issue related to this (#168) dates back to 2018. Therefore I'd like to ask again: would this be a possibility and/or where would help be needed?

**Comment by otykier** [comment]
Sorry, that's not something I'll be prioritizing for TE2. If someone else wants to build this feature, by all means - the code is open source and anyone may contribute.

If dark mode and a better/more modern UI is important to you, consider purchasing [Tabular Editor 3](https://tabulareditor.com).
