### ISSUE TITLE
Reference BPA output in Advanced Scripting

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor#848]
Is it possible to reference the BPA output (rules which have been broken) via Advanced Scripting? For example, the ability to loop through the rules and extract all the objects which violate each rule.

**Comment by alwortman** [comment]
I think the best way to do this would be to use the _-Analyze_ parameter of TE via command line. 

[Tabular Editor Command Line Options](https://docs.tabulareditor.com/Command-line-Options.html)

That generates an output that looks something like this:
```

Tabular Editor 2.16.0 (build 2.16.7781.40242)
--------------------------------
Loading model...
Running Best Practice Analyzer...
=================================
Column 'Athena Access'[RoleId] violates rule "Provide format string for visible numeric columns"
Column 'Athena Access'[GroupId] violates rule "Provide format string for visible numeric columns"
Column 'Athena Access'[WWID] violates rule "Provide format string for visible numeric columns"
Column 'HANA Security Table'[Finance Entity] violates rule "Provide format string for visible numeric columns"
Column 'Audit Table'[Access Rank] violates rule "Provide format string for visible numeric columns"
```

From there you could read that in via an Advanced script doing something like this:
```
// Read a text file line by line.

string[] lines = System.IO.File.ReadAllLines(@"C:\Users\alwortma\Downloads\BPAOutput.txt");  
var bpaoutput = "";
foreach (string line in lines){
    bpaoutput += line + System.Environment.NewLine;
}

Output(bpaoutput);
```

![image](https://user-images.githubusercontent.com/13524879/118560834-f7d89400-b71e-11eb-8954-c4d829ca608a.png)


Not sure what your exact workflow looks like for this, but that should be a start.

**Comment by m-kovalsky** [comment]
Interesting, thanks. Was curious if there is a way to do this without using the command line option.

**Comment by otykier** [comment]
There's a better way. You can run a Best Practice Analysis through a script. The following script produces a list of [AnalyzerResult](https://github.com/otykier/TabularEditor/blob/9cee09fc11e3c1a182e8026ef1da1d73ad6b015e/TabularEditor/BestPracticeAnalyzer/Analyzer.cs#L175-L217) objects. Each AnalyzerResult specifies a TOM object in violation of a specific rule:

```csharp
using TabularEditor.BestPracticeAnalyzer;

var bpa = new Analyzer();
bpa.SetModel(Model);

var results = bpa.AnalyzeAll().ToList(); // List<AnalyzerResult>

Info("BPA violations: " + results.Count.ToString());
Info("Violation 1, rule: " + results[0].RuleName + ", object: " + results[0].ObjectName);
Output(results[0].Object);
```

**Comment by m-kovalsky** [comment]
This is precisely what I was looking for - thanks Daniel! Just one more thing - can we get the RuleCategory, Severity and other rule properties within this? I don't see these within the AnalyzerResult class.

Thank you!

**Comment by otykier** [comment]
These exist as properties on the `Rule` property (which is of type [BestPracticeRule](https://github.com/otykier/TabularEditor/blob/9cee09fc11e3c1a182e8026ef1da1d73ad6b015e/TabularEditor/BestPracticeAnalyzer/BestPracticeRule.cs#L126-L160)):

```csharp
Info(results[0].Rule.Category);
```

**Comment by m-kovalsky** [comment]
Perfect! Thanks so much!

**Comment by alwortman** [comment]
Thanks for all the knowledge drops @otykier !! Helpful as always 👍

**Comment by m-kovalsky** [comment]
@otykier can we run the bpa inside of tabular editor (not using the command line) against a .bim file (not against the model loaded into tabular editor)?

**Comment by otykier** [comment]
@m-kovalsky technically, yes. You could always do something like

```csharp
var process = Process.Start("tabulareditor.exe model.bim -A > output.txt");
process.WaitForExit();
```

and then parse the output file in the script.

If you could add a few more words on what you need this for, maybe we can come up with a better solution?

**Comment by m-kovalsky** [comment]
I'd like to have a script/program which can run the BPA against a folder of .bim files (or pbip files) and save the output into a file.

**Comment by otykier** [comment]
I see. Well, the following should work, at least in TE2:

```csharp
using TabularEditor.BestPracticeAnalyzer;
var bpa = new Analyzer();

var model = new TabularModelHandler(@"C:\Users\DanielOtykier\Desktop\model.bim").Model;
bpa.SetModel(model);
var results = bpa.AnalyzeAll().ToList(); // List<AnalyzerResult>
```

Here, I've hardcoded the path of the model to load, so you'd have to put it into a loop, iterating the model.bim, database.json or model.tmd files you'd want to analyze. How you want the result to be outputted is also up to you.

**Comment by m-kovalsky** [comment]
Ah, TabularModelHandler is the key. Thanks Daniel!

**Comment by m-kovalsky** [comment]
Is it possible to run the command line to run a command line to run a c# script without referencing a .bim file or server/database? Just want the script to run against tabular editor (without the program opening).

**Comment by otykier** [comment]
No, you would have to create a minimal/empty model.bim file to use in the CLI, as a workaround.

**Comment by m-kovalsky** [comment]
Ah, ok. Thanks Daniel

**Comment by m-kovalsky** [comment]
Has something changed in the analyzer output? This script doesn't work anymore (object, category, severity)

```c#
using TabularEditor.BestPracticeAnalyzer;

var bpa = new Analyzer();
bpa.SetModel(Model);

var results = bpa.AnalyzeAll().ToList(); // List<AnalyzerResult>

Info("BPA violations: " + results.Count.ToString());
Info("Violation 1, rule: " + results[0].RuleName + ", object: " + results[0].ObjectName);
Output(results[0].Object);
```

**Comment by otykier** [comment]
It seems a bug was introduced after we changed [this property](https://github.com/TabularEditor/TabularEditor/blob/718b4468e9c6ecac0b6a039317731252ec94d4f1/TabularEditor/BestPracticeAnalyzer/Analyzer.cs#L187) to be init-only (which is a relatively new C# language feature).

Could you use `Output(results[0].ObjectName]);` for the last line of your script, as a workaround for now?

**Comment by m-kovalsky** [comment]
Thank Daniel, the code below works. However, it seems that something has changed with category and severity. It used to be Rule.Category & Rule.Severity but that code doesn't work anymore.

```c#
using TabularEditor.BestPracticeAnalyzer;

var bpa = new Analyzer();
bpa.SetModel(Model);

var results = bpa.AnalyzeAll().ToList(); // List<AnalyzerResult>

Info("BPA violations: " + results.Count.ToString());
Info("Violation 1, rule: " + results[0].RuleName + ", object: " + results[0].ObjectName);
Output(results[0].ObjectName);
```

**Comment by otykier** [comment]
Apologies for the delay in getting back to this. However, the issue was fixed a while ago, and your [original script](https://github.com/TabularEditor/TabularEditor/issues/848#issuecomment-1878404944) should now work fine.

**Comment by m-kovalsky** [comment]
Thanks Daniel!
