### ISSUE TITLE
Deploy to a model with RefreshPolicy

### ISSUE THREAD

**Issue by tobimax** [TabularEditor/TabularEditor#867]
Hi,

In #632 you have added a fix to skip deploying partitions to a model if they are part of a Refresh Policy. I can't seem to do this inside the GUI. Could this be set in the preference settings or deployment settings (F6) for Refresh Policy partitions like it is in TE3?

Also there is the issue of serializing the partitions to disk if they are part of a Refresh Policy. I would like to be able to ignore these partitions and not have them serialize.

However even if you delete the partition folder, you cannot load the model from the folder as it throws an error.

Thanks

Toby.

**Comment by otykier** [comment]
[2.16.5](https://github.com/TabularEditor/TabularEditor/releases/tag/2.16.5) adds the GUI option to include/skip refresh policy partitions. I've create a separate issue for ignoring these partitions when saving to folder.
