### ISSUE TITLE
PowerBINotLicensedException Tabular Editor CLI deploy

### ISSUE THREAD

**Issue by subashsivaji** [TabularEditor/TabularEditor#876]
I am using Tabular Editor 2.16.0 CLI to deploy Power BI Dataset (.bim file) to ~~Power BI Premium~~ Power BI Premium Per User workspace (via XMLA endpoint)

Following is the CLI command which is using Service principal id and auth,
`.\TabularEditor.exe "..\Model.bim" -S "..\set.params.cs" -D "Provider=MSOLAP;Data Source=powerbi://api.powerbi.com/v1.0/myorg/Workspace Name;Initial catalog=PBI Dataset Name;User ID=app:appid@tenantid;Password=xxxxx;" "PBI Dataset Name" -O -C -R -M -V -E`

Following is the output 
```
Tabular Editor 2.16.0 (build 2.16.7781.40242)
--------------------------------
Loading model...
Loaded script: ..\set.params.cs
Executing script 0...
Deploying...
##vso[task.logissue type=error;]Deployment failed! Failed to generate MWC token from AAD token. Description: {"error":{"code":"PowerBINotLicensedException","pbi.error":{"code":"PowerBINotLicensedException","parameters":{},"details":[],"exceptionCulprit":1}}}

Technical Details:
RootActivityId: c56af0b0-9360-4ff5-83ff-2928f094a29e.
##vso[task.complete result=Failed;]Done.
```

**Question:**
Do I need any licence for the service principal?

**Application specifics**
 - Tabular Editor version: Tabular Editor 2.16.0
 - Semantic Engine used: Power Bi Premium
 - Model Compatibility Level: 1540

**Comment by marcosqlbi** [comment]
If you use Power BI Premium per User, the service principal is not licensed. It should work with a Power BI Premium capacity license.

**Comment by jasonhendrix** [comment]
@marcosqlbi

When you say, "If you use Power BI Premium per User, the service principal is not licensed", does that mean if you are using PPU with a Service Principal you don't need a license for the Service Principal, and that this method of deployment should work?

Or, does that mean that a Service Principal can't be assigned a PPU license and therefor you can't use this method to deploy?

**Comment by marcosqlbi** [comment]
I mean that the service principal does not work - your batch should work with a service principal with Power BI Premium Capacity.
I'm not saying it's good (it isn't), but it's the way it works now.
