### ISSUE TITLE
Drillthrough page showing wrong values for non-calculation group measures

### ISSUE THREAD

**Issue by JorisKamma** [TabularEditor/TabularEditor#882]
I created a report with a calculation group consisting of several formulas. 
The report consists of 3 pages: 

- Page  1-> containing a Matrix visual
- Page 2-> containing a Matrix visual
- Details Page

The Details page contains drillthrough filters. From Page 1 & 2 Matrix visuals, you can drillthrough to the details page. 

The details page contains the following visuals 

- matrix containing the calculation group items 
- 3 card visuals using measures (not from the calculation group) 
- 1 tabel containing measures (not from the calculation group)
- 1 line chart containing measures (not from the calculation group)

Error: 
If I right click on a value in a matrix on Page 1 or Page 2 and select drillthrough to details page, it will display the values from that calculation Item in the measures that are not in the calculation group. 

![image](https://user-images.githubusercontent.com/63793016/125093556-b4712500-e0d2-11eb-8956-093f4d68d906.png)

![image](https://user-images.githubusercontent.com/63793016/125093780-f1d5b280-e0d2-11eb-9b62-455ad255fcb5.png)

**Expected behavior**
In the screenshots above the amount selected for drillthrough (3000) should not have shown up in any of the other visuals on the details page, since they use completely different formulas. They should therefore be blank instead. 

If I remove the calculation group filter from the drillthrough page, the problem no longer exists. 

Since the calculation group is not a real table, in the sense that it cannot be connected to other tables, I can see that filtering could be problematic sometimes. What I don't understand is seems to overwrite the values of the other formulas. 

**Application specifics**
 - Tabular Editor version: 2.16.1
 - Semantic Engine used: [Power BI Desktop june 2021

**Comment by otykier** [comment]
This issue is not related to Tabular Editor. You should ask it on the [Power BI support forum](https://community.powerbi.com/t5/Forums/ct-p/PBI_Comm_Forums) instead.
