### ISSUE TITLE
Automating serialization of pbix file to folder structure

### ISSUE THREAD

**Issue by Saidheeraj2309** [TabularEditor/TabularEditor#885]
Hi @otykier ,

Is there any way to automate the serialization of pbix file to folder structure done by TE. 

So In general we are opening TE through Power BI desktop and then click on save to folder and saving the serialized dataset (w json objects) in repo. So I was wondering if I can use any CLI or PowerShell script to automate serialization such way that when user places pbix file in a folder or sharepoint the automation process saves the folder structure in a different folder.

Appreciate your help and time.

Thanks
Sai

**Comment by otykier** [comment]
Unfortunately, TE cannot access the data model of a .pbix file directly. You would have to load the .pbix in Power BI Desktop, or use the .pbit file format instead (in Power BI Desktop go to File > Export > Power BI Template).

You can use Tabular Editor's CLI to convert a .pbit file to a folder structure in the following way:

```bash
start /wait TabularEditor.exe "myfile.pbit" -F "gitrepo\myfile"
```

**Comment by Saidheeraj2309** [comment]
Thank you @otykier
