### ISSUE TITLE
High Level Example connecting to Power BI Premium

### ISSUE THREAD

**Issue by annhwallinger** [TabularEditor/TabularEditor#887]
Greetings,
I am a novice C# programmer so please excuse my ignorance here... I am trying to get started using the TomWrapper in my project. I pulled it in as a reference and have it available but I can't see anywhere how to make my basic connection to my model up in Power BI Premium. I have gone through the code snippet examples and they make sense but I am not seeing where to make the basic connection.

For example with Analysis Services without the TomWrapper:
string workspaceConnection = "powerbi://api.powerbi.com/v1.0/myorg/[myworkspace]";
string connectString = $"DataSource={workspaceConnection};";
Server server = new Server();
server.Connect(connectString);
// enumerate through datasets in workspace to display thier names
foreach (Microsoft.AnalysisServices.Tabular.Database database in server.Databases)
{
    Console.WriteLine("Database Found: " + database.Name);
    Microsoft.AnalysisServices.Tabular.Model m = database.Model;             
}

The above works, what is the equivalent for TomWrapper?

thank you!

**Comment by otykier** [comment]
It's as simple as passing the connection string and the ID of the database (in PBI this is a GUID) to the TabularModelHandler constructor:

```csharp
var workspaceConnection = "powerbi://api.powerbi.com/v1.0/myorg/[myworkspace]";
var databaseId = "xxxxxx-xxxx-xxxx-xxxxxx";
var handler = new TabularModelHandler(workspaceConnection, databaseId);
var model = handler.Model;
```

The `model` variable in this example is now a reference to the same type of Model class that you can access through Tabular Editor's scripting.

**Comment by annhwallinger** [comment]
Thank you so much. I have a program that uses the REST APIs in Power BI to automate deployment for CI/CD and the missing piece of the puzzle was getting translations loaded after datasets are deployed. Your code library and hint above helped me complete it. I love the Tabular Editor.
