### ISSUE TITLE
Windows defender freaks out on v2.6

### ISSUE THREAD

**Issue by chrisumphlett** [TabularEditor/TabularEditor#888]
Myself and a teammate are getting this message from Windows Defender when we try to launch the .msi file, or, the application after extracting it from the .zip

![image](https://user-images.githubusercontent.com/7210482/126171360-7c3e5232-fe3d-4f94-95e9-43cd0999c1a4.png)

**Comment by otykier** [comment]
Strongly recommend you upgrade to a newer version, as all releases since 2.9.8 are digitally signed. We do not offer support for versions of Tabular Editor that are more than 1 year old (v. 2.6 is from October 2017).

**Comment by chrisumphlett** [comment]
OK thanks. I was only d/l'ing 2.6 because I was trying to reproduce something from an article that used 2.6. (I opened an issue about that in the TE 3 repo).
