### ISSUE TITLE
Tabular Editor CLI

### ISSUE THREAD

**Issue by odomdave** [TabularEditor/TabularEditor#893]
https://github.com/TabularEditor/TabularEditor/issues/530

I've read the closed issue above and it fits exactly what I'm trying to do. Open a pbit file and run a script that will change column names based upon a lookup table I connect to with a SQL server connection in c#.  Everything runs fine and with the -D argument, it does save the .pbit file. However, when I open the .pbit file with PBI Desktop, the column name changes are not reflected.  When I run the advanced script manually, it works fine. I thought maybe it wasn't passing the windows auth for the sql connection, so I tried with a SQL username and pwd, but that didn't resolve either. Here is the cmd I'm running: start /wait TabularEditor.exe "E:\Temp\Test1.pbit" -S "E:\Temp\ChangeColumnNmesSQLAuth.cs" -D
I've attached the result.
![tabedscreeb](https://user-images.githubusercontent.com/65987143/127217222-6f63dbad-c503-49ba-9a75-6d5a124727de.jpg)

**Comment by otykier** [comment]
It's difficult to figure out what's going on without knowing what your script looks like. You should be aware that in general, making modifications to a .pbit file through external tools is not supported by Microsoft, so this operation is not guaranteed to work.

If you open the .pbit file in Tabular Editor after running the command above, does it seem like the script has made any changes to the model?

Maybe you can add some `Info("Changing name of column " + c.Name + " to " + newName);` statements somewhere in the code to help you debug if the columns are being changed correctly when the script is being executed through the commandline.

**Comment by odomdave** [comment]
```
//This code changes column names based upon a file. The file should be generated from a lookup table that has the Original 
//column name and the new name

//For c# you have to add in the assemblies you will be using
using System.Data;
using System.Data.SqlClient; 

//Create the SQL connection
SqlConnection conn = new SqlConnection();  
conn.ConnectionString = "data source=Sql01;initial catalog=db_1000_ADW_Sample;Integrated Security=True;";  
conn.Open();   
// Set up the command (query)  
SqlCommand cmd = new SqlCommand("SELECT DB_dbName,tbl_Orig_Name, tbl_New_Name,DateUpdated FROM d_ReportGroup_Test_columns", conn);

//Create a datatable to house the retrieved data
DataTable table = new DataTable();
SqlDataAdapter adapter = new SqlDataAdapter(cmd);
adapter.Fill(table);

//---------------------------------------------------------  
//all columns in the model
//foreach(var column in targetTable) {
 foreach(var column in Model.Tables.SelectMany(t => t.Columns)) {

// Iterate through the filled datatable from above
foreach (DataRow row in table.Rows)

{
    string dbname = row["DB_dbName"].ToString();
    string dtupdated = row["DateUpdated"].ToString();
    string origname = row["tbl_Orig_Name"].ToString();
    string newname = row["tbl_New_Name"].ToString();
	
    Info("Changing name of column " + column.Name + " to " + newname);

    //Change the values in the PBI Model.  If change metrics used in calcs, PBI 
    //will make the appropriate changes in the formulas
    if(column.Name == origname) 
    {
        column.Name = newname;
        column.Description = dbname;   //This is an example. This Description attribute is to show where fields originated
        //column.DisplayFolder = "Aging\\Days"  //This column sets up folder hierarchy
    }   

}
}
 


```
Thank you for your response!

Above is the code I'm using. It does work when running manually, but just not when running via script. The script runs without errors, but no, after opening the pbit file nothing has changed in the model. If I run manually, then 'Save changes to the connect db', it works. Also, even adding that info() section in there doesn't show up in the cmd line output, but obviously does when running manually via tabular editor. Although, I noticed with the info() code in there it's not very efficient :) I'll need to work on only iterating 1x through once I can get the script running via cmd line...

I've attached a few files to show exactly what I'm doing, just adding _new to field names for testing...

Here is the interface with the above code:
![Screenshot 2021-08-05 124437](https://user-images.githubusercontent.com/65987143/128406780-e73711f4-9600-4007-bfff-281413aea4a2.jpg)

You can see it running manually successfully:
![Screenshot 2021-08-05 124508](https://user-images.githubusercontent.com/65987143/128406776-863f0207-dba4-459a-8ac1-11a7aad85b86.jpg)

This is the renamed fields:
![Screenshot 2021-08-05 130128](https://user-images.githubusercontent.com/65987143/128406871-35cc82e7-fee5-474f-ad46-c7c4c5c02356.jpg)

This is all manually done, Running via script, doesn't produce these results. It's like nothing was run at all. Fields still have all of the original names etc.

**Comment by otykier** [comment]
This is related to #911 since Tabular Editor's CLI blocks unsupported Power BI changes by default (such as renaming a column). A fix will be available shortly.
