### ISSUE TITLE
ALM Toolkit support for Tabular Editor serialized models

### ISSUE THREAD

**Issue by jasonhendrix** [TabularEditor/TabularEditor#894]
**Is your feature request related to a problem? Please describe.**
To use Tabular Editor's folder serialization option along with ALM Toolkit requires that you first take an additional step to convert back to a single .bim file before using ALM Toolkit for model comparisons. It would be nice to be able to skip that step.

**Describe the solution you'd like**
I am hoping that Tabular Editor could have a new feature added so that any time you click Save when working with folder serialized models that both the folder serialized version and a normal .bim version can both be generated/saved at the same time.  For source control purposes, .bim files could then be added to git ignore files so they don't get checked in but would still be available for ALM Toolkit comparisons.

**Describe alternatives you've considered**
This problem could be solved by ALM Toolkit instead of by Tabular Editor.  I have submitted this similar request to the ALM Toolkit team: https://github.com/microsoft/Analysis-Services/issues/117

**Comment by jspanos71** [comment]
This would be a huge help! +1

**Comment by otykier** [comment]
I'm a huge fan of Tabular Editor folder-format support in ALM toolkit. Will reach out to Christian Wade to see what can be done in this regard.

**Comment by jasonhendrix** [comment]
@otykier I've submitted a Pull Request for your review that addresses this for now by generating a .bim file automatically.  I would also prefer the feature be added to ALM Toolkit, but adding this feature to Tabular Editor gets us what we need (although in a slightly less than ideal way).
