### ISSUE TITLE
What is the command to script a change to the Data Category?

### ISSUE THREAD

**Issue by phogon2** [TabularEditor/TabularEditor#895]
See below for a picture. I am looking to change a columns Data Category to Longitude / Latitude but can't seem to make it work. 

I assume its uses the c.DataCategory function but don't actually know how to use it. Can anyone help me out?

![image](https://user-images.githubusercontent.com/86638782/127454852-4a3d2f5f-8312-48d2-9b49-6c9343b904a7.png)

**Comment by m-kovalsky** [comment]
If you're trying to do this in Advanced Scripting, see the code below. If you're changing the Data Category manually, there's a dropdown in the properties window (same window as your screenshot).

```'C#
var c = Model.Tables["TableName"].Columns["ColumnName"];
c.DataCategory = "Latitude";
```

**Comment by phogon2** [comment]
Thanks!! @m-kovalsky
