### ISSUE TITLE
Hiding "Other" Columns from a table 

### ISSUE THREAD

**Issue by phogon2** [TabularEditor/TabularEditor#903]
If I create a table and want to hide some columns, I understand I can manually select columsn 1 by 1 and use the 

column.DisplayFolder = "Ignore";

function to hide them. However, is there a way for me to move all the columns into a "ignore" folder at once?

i.e. If I have a script like:

var t = (Model.Tables["Test"] as CalculatedTable) 

Is there a way I can move all the columns in that table into a "Ignore" folder, then use the "AddCalculatedTableColumn" to move the columns I need into it's own folder?

Thanks,
Sid

**Comment by otykier** [comment]
```csharp
// Move all columns of table 'Test' into the "Ignore" folder. Move [Column 1] and [Column 2] to the "Another folder" folder:
var t = Model.Tables["Test"];
foreach(var column in t.Columns)
{
    column.DisplayFolder = "Ignore";
}
t.Columns["Column 1"].DisplayFolder = "Another folder";
t.Columns["Column 2"].DisplayFolder = "Another folder";
```

**Comment by phogon2** [comment]
Perfect Thanks!
