### ISSUE TITLE
Misspelling 'sequence' in 'Last' extension

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor#905]
**Describe the bug**

The info on hover has a misspelling 'sequency' which should be 'sequence'.

Model.Tables["Revenue"].Columns.Last(...)

Line 330 of this script:
https://github.com/TabularEditor/TabularEditor/blob/885ff9f84f6497b7958a402854d959d747e0e0a2/TabularEditor/UI/UIController_ScriptEditor.cs

**Application specifics**
 - Tabular Editor version: 2.16.1

**Comment by otykier** [comment]
Fixed in [2.16.2](https://github.com/TabularEditor/TabularEditor/releases/tag/2.16.2).
