### ISSUE TITLE
Role Member Deployment failing for Azure Analysis Services, AzureAD groups

### ISSUE THREAD

**Issue by jcberg3** [TabularEditor/TabularEditor#906]
Attempting to deploy (via command line, tabulareditor.exe) to an Azure Analysis Services instance, and also including roles and role members.  However I cannot get past the below exception:

##[error]Deployment failed! The JSON DDL request failed with the following error: Failed to execute XMLA. Error returned: 'ID cannot be specified for Azure Analysis Services role member: '<pii>obj:dfdfe237-xxxxxxxxxxxxx</pii>'

Searching online this particular error can happen locally through visual studio if your Integrated Workspace Mode is set to False.  I don't know if or how that could apply here, but that was the only reference I could find to this particular exception.

Here are the current switches I'm passing in to the .exe file.

```
-S "$PSScriptRoot\$($_.ConnectionScript)" `
-D "Provider=MSOLAP;Data Source=$($_.BuildASServer);UserID=$aSServicePrincipal;Password=$AzureAD_DevOpsClientSecret;Persist Security Info=True;" "$($_.BuildASDatabaseName)$($BuildNumber)" `
-C `
-O `
-R `
-M `
-V | Out-Default
```

**Comment by jcberg3** [comment]
Additionally, if I attempt this same deployment through the GUI it appears to work fine.

**Comment by otykier** [comment]
[2.16.2](https://github.com/TabularEditor/TabularEditor/releases/tag/2.16.2) now removed the memberId property from the TMSL script for AzureAD-based role members.

**Comment by otykier** [comment]
Apparently, when deploying to SSAS (on-premises), the [MemberID must be present](https://github.com/TabularEditor/TabularEditor3/issues/263), so this change will likely have to be rolled back. In your case, it seems that the issue arises from the Model.bim file specifying both the MemberID and MemberName properties, where as it should only specify MemberName. Any idea how it got to the point where both properties were specified?

**Comment by jcberg3** [comment]
We do our development of tabular models in VS2019, and anytime we edit a
role it saves the .bim file like that with both properties.  It must be
doing that for the reasons you mention about one way being required for
on-prem and another way being required for azure AS.  If you run the
deployment from VS it must have logic that identifies your target as Azure
or on-prem and is able to adjust on the fly accordingly.
