### ISSUE TITLE
Role Members part of multiple roles

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor#907]
**What are you trying to achieve?**
Looking to create a BPA rule that flags role members which are part of multiple roles (which can lead to various issues). Currently, the 'Applies to...' within the BPA Editor only shows 'Roles', not 'Role Members'. In order to accomplish this, I believe we'd need to have a 'Role Members' within the 'Applies to'. Or is it possible to catch this without that?

**What have you tried so far?**

This works in the Advanced Scripting window - but without being able to iterate through all the role members (irrespective of their role), I'm not sure how to do this in the BPA.

string rM = @"DOMAIN\alias";

if (Model.Roles.Where(a => a.Members.Any(b => b.MemberName == rM)).Count() > 1)
{
    "true".Output();
}

Thanks!

**Comment by otykier** [comment]
I agree that there should be an option for checking a rule against individual role members.

In the mean time, the following (pretty convoluted) LINQ expression, can check if a role contains members (by their MemberName property) that also exist in other roles:

**Applies to:** Model Roles
```
Model.Roles.Where(it != current).Any(Members.Any(current.Members.Any(MemberName == outerIt.MemberName)))
```

**Comment by otykier** [comment]
[2.16.3](https://github.com/TabularEditor/TabularEditor/releases/tag/2.16.3) now lets you create BPA rules that apply to Model Role Members. A similar update for TE3 will be available soon.

**Comment by otykier** [comment]
**Applies to:** Model Role Members
```
Model.Roles.Where(it != current.Role).Any(Members.Any(MemberName = current.MemberName))
```

I actually like the one I posted above (that applies to Roles) more than this one, since the former shows you which roles have identical members and lets you navigate directly to the role in question.

**Comment by m-kovalsky** [comment]
This is great, Daniel! I made a similar rule - both essentially do the same thing. The trick here is that we want both the member name and the overlapping roles. 

If we have the rule set on the role, it identifies the roles with the issue but not the member(s) that break the rule.

If we have the rule set on the members, it identifies the members but it doesn't identify the roles to which they belong.

Thoughts on how to show both the role and member for this rule (within the BPA itself)? This would make the identification process clearer.

```c#
Model.Roles.Where(Members.Any(MemberName = current.MemberName)).Count() > 1
```
