### ISSUE TITLE
Can not set column EncodingHintType

### ISSUE THREAD

**Issue by neednlab** [TabularEditor/TabularEditor#910]
I'm trying to set EncodingHintType in a power bi pbix file, but nothing changed.
Why it shows 0 model changes?
![eac3c8c940b88af5426410ca544e5f4](https://user-images.githubusercontent.com/41602171/132308286-37569130-e702-4a56-b2df-a95589444184.png)

**Comment by m-kovalsky** [comment]
Go to File->Preferences and ensure that 'Allow unsupported Power BI features (experimental)' is checked.

![image](https://user-images.githubusercontent.com/29556918/132556079-10050ee3-87a3-44cc-abb1-212651f72f54.png)

**Comment by neednlab** [comment]
@m-kovalsky thanks, it works.
However, I'm confused that it still used HASH encoding after I changed encoding hint to "Value"
![image](https://user-images.githubusercontent.com/41602171/132606303-b8be0f55-5b2c-4b5d-b94d-dfc4fb17d144.png)

**Comment by marcosqlbi** [comment]
The hint is not enforcement. If the column cannot be represented as a value encoded column, it's compressed as hash encoded column. For example, the value encoded is 32-bit, if you have values outside the 32-bit range, it will be always hash-encoded.

**Comment by neednlab** [comment]
@marcosqlbi Got it, many thanks
