### ISSUE TITLE
BPA - create new rule file from gui dont work 

### ISSUE THREAD

**Issue by nexus150** [TabularEditor/TabularEditor#912]
!!! Please make sure you're using the latest version of Tabular Editor before submitting a bug !!!

**Describe the bug**
if I create a new rules file from the BPA gui, and tabular editor does not have write permissions in the folder I select, the file is not created, the annotation in the model is created and you can create rules to this new file, move them from another, etc, and everything works fine, but the file is not created physically in the selected location, and the problem is that there is no error message, when you save the model or .bim, close it and open it again appears the reference to this new set of rules but without rules, because the physical file does not exist.

**To Reproduce**

1. Open a model or .bim with tabuler editor
2. Go to Manage BPA Rules
3. Select add / create new rule file
4. Select a folder and file name for the new rule file
5. Create or move rules to the new rules file ( following the first rule creation / copy from , the file would be created,but that not happen.
6. Click OK
7. Close and reopen the model
8. go to manage bpa rules / select the new file created
9. The file dont have any rules

**Expected behavior**
the new file should have the rules created or you should get an error stating that the file cannot be created due to lack of permissions

**Application specifics**
 - Tabular Editor version: 2.16.2
 - Semantic Engine used: Poiwer BI Desktop August 2021
 - Model Compatibility Level: 1500

**Additional context**
if tabular editor is running as administrator then the issue gone

**Comment by otykier** [comment]
Fixed in [2.16.4](https://github.com/TabularEditor/TabularEditor/releases/tag/2.16.4). Thanks for reporting!
