### ISSUE TITLE
Lenght function not provided for column.Name and Table.Name

### ISSUE THREAD

**Issue by elsdestickere** [TabularEditor/TabularEditor#914]
I want to make displayfolder names based on the column names.
To create a substring I need to find the length of a string, but this function is not available.

**Describe the bug**
var c = Model.Tables["tablename"].Columns["columnName"].Name;
var tableName=Model.Tables["tablenam"].Columns["columnName].Table.Name.ToLower();
Output ( c.lenght, tableName.lenght);

Error message: CS1061 'type' does not contain a definition for 'name' and no accessible extension method 'name' accepting a first argument of type 'type' could be found (are you missing a using directive or an assembly reference?).

** Question: Can I fix this or not?

**Application specifics**
 - Tabular Editor version: [e.g. 2.16.2]

**Comment by otykier** [comment]
In C#, properties are usually named with a capital first letter: `tableName.Length`

Also, the Output method only takes a single parameter, so if you want to output two or more values you must concatenate them first:

```csharp
Output(c.Length.ToString() + "," + tableName.Length.ToString());
```

**Comment by elsdestickere** [comment]
👍
