### ISSUE TITLE
Defining table description in Tabular Editor 2 generates a "There are pending changes in your queries that hasn't been applied" message

### ISSUE THREAD

**Issue by erapade** [TabularEditor/TabularEditor#916]
!!! Please make sure you're using the latest version of Tabular Editor before submitting a bug !!!

**Describe the bug**
Defining table description in Tabular Editor 2 generates a "There are pending changes in your queries that hasn't been applied" message. This message will never go away until you remove the description.
Creating a table description using Power Query editor works with no problem. The strange thing is that if I compare the two models (1 with description created with PQ and the other with description created with TE2), they look exactly the same. So no differences in the model

**To Reproduce**
1. Open TE2 from within Power BI Desktop
2. Click on a table
3. Change the description properties
4. save the model

**Expected behavior**
The description added to the table

**Observed behavior**
"There are pending changes in your queries that hasn't been applied". And this message never goes away until I remove the description using TE2

**Application specifics**
 - Tabular Editor version: [e.g. 2.16.3]
 - Semantic Engine used: Latest PBI Desktop
 - Model Compatibility Level: [e.g. 1400, 1500, 1520, etc.]

**Additional context**
Added a minimal file with this issue
[tst.zip](https://github.com/TabularEditor/TabularEditor/files/7259962/tst.zip)

**Comment by otykier** [comment]
Editing table properties through external tools is [not supported by Power BI Desktop](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-operations). If you would like to be able to edit more objects and properties than those currently supported, please raise this with Microsoft.
