### ISSUE TITLE
Don't show zero-width non-breaking spaces in expression editor

### ISSUE THREAD

**Issue by ruve1k** [TabularEditor/TabularEditor#938]
If a table or measure contains zero-width non-breaking space characters in the object name they are displayed as spaces in the expression editor.  In the properties window however, they are not displayed as spaces.
The request is to use a different font or change a setting in the text (expression) editor so that zero-width non-breaking spaces are not displayed (with any width) just like in the properties window.

![image](https://user-images.githubusercontent.com/20305564/139719380-05cab396-ea37-4b72-8323-a741e1e8f784.png)

**Comment by otykier** [comment]
The expression editor uses a mono width font by design, since features like block select, etc. would not work correctly if all characters does not have equal width.

**Comment by ruve1k** [comment]
Daniel, thanks for the quick response.
Can you elaborate on or provide links to the features that _require_ mono-spaced font? I'm not familiar with them.
DAX Studio seems to have a fairly robust editor and still allows for a variety of fonts.
