### ISSUE TITLE
CTRL + S saves current query, does not synchronize changes to the model

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor#939]
While writting a DAX query a yellow banner appears with the message "You have made structural changes to the model metadata ... Hit CTRL+S to syncronize" 
But if you click CTRL+S you get the dialog to save the DAX query. 
Also there's no button to synchronize either, at least that I have found. 

Regards!

**Comment by otykier** [comment]
Closing this as duplicate of https://github.com/TabularEditor/TabularEditor3/issues/251

(Also, please post Tabular Editor 3 issues on the TE3 GitHub site: https://github.com/TabularEditor/TabularEditor3/issues - this is the site for TE2)

**Comment by bernatagulloesbrina** [comment]
oups! sorry -- jumped in from google
