### ISSUE TITLE
Force Tabular Editor CLI to log in English

### ISSUE THREAD

**Issue by justBlindbaek** [TabularEditor/TabularEditor#941]
Hi

I have setup automated build with Azure DevOps using the Tabular Editor CLI. We do schema validation, run best practice rules and deploy the data models. Everything works great, but it annoys me that some of the output Visual Studio Team Services logging commands is shown in Danish. 

Examples:
```
##[warning]Error on measure 'N�gletal'[Daglig fakturering %]: Dette udtryk refererer til et Measure-objekt med navnet 'N�gletal[Daglig fakturering]', som har en fejl.
##[warning]Error on measure 'Transaktion'[FREMDLOHN]: Kolonnen 'OriginalFremmed' i tabellen 'Sransaktionstype' blev ikke fundet, eller den kan muligvis ikke bruges i dette udtryk.
```
It only seems to happen with the deployment, but here I also get messages in English...

This is a fix of logging from both schema validation, BPA check and deployment where the output is English:
```
##[warning]Information: Unprocessed object: partition 'Kalender' on table 'Kalender' (NoData)
##[warning]Column 'Vogndb'[MKoder] violates rule "[Performance] Remove redundant columns in related tables"
##[error]Measure [Tilbud] violates rule "[Formatting] Provide format string for measures"
##[warning]Column named 'Postnr' exists in the source query for table 'Eftermarkedsordre Header', but is not mapped to any Tabular Model column.
##[warning]Column 'KPI'[�r M�ned] violates rule "[Maintenance] Remove unnecessary columns"
```

Is it possible to show all errors in English?

And can you also help with fixing the special danish characters, that is shown as �. I'm not sure it has anything to do with Tabular Editor as I also get this with SQL deployment using the Invoke-Sqlcmd PowerShell cmdl. You might have an idea on this too?

**Comment by otykier** [comment]
Tabular Editor simply outputs the error messages returned from Analysis Services. To make Analysis Services speak a different language, add the LocaleIdentifier to the AS connection string: https://docs.microsoft.com/en-us/analysis-services/translation-support-in-analysis-services?view=asallproducts-allversions

**Comment by justBlindbaek** [comment]
Perfect. That made the trick.

Our Analysis Services engine is a Power BI Premium Capacity, so I really don't know why it should speak Danish? And only with some of the outputs. We connect with a Service Principal, that don't have a locale/language setting?

Any way - I learned something new and it's working. Now I just need to figure out why I get � in the output. Probably something I should change in the settings on the Azure DevOps Pipeline.

**Comment by otykier** [comment]
I believe the engine speaks whatever language the client machine OS uses.

Not sure about the special characters - you could try to run TabularEditor.exe through a PowerShell task rather than a command line task, to see if that changes anything.

**Comment by justBlindbaek** [comment]
We already run it through a PowerShell task, so that don't change it. But we also get the � in the output when using Invoke-Sqlcmd. So it must be something generic.

I close this comment. Thanks for the help!
