### ISSUE TITLE
Error saving Tabular model when referencing KPI measures

### ISSUE THREAD

**Issue by kjoebie** [TabularEditor/TabularEditor#942]
Hi,

In TE free edition and TE3, when I reference a KPI measure (e.g. status) and try to save the changes to the database, I have to wait for a long time and finally get an error:
![image](https://user-images.githubusercontent.com/7207207/143020223-47d5a8ba-a265-49b2-9db6-3605ee9d4b96.png)

I use the following DAX to select the KPI measure:

I use a calculation group to reference the status from KPI's. The dax I use is the following
SWITCH (
    TRUE (),
    ISSELECTEDMEASURE ( [Measure actual] ), [_Measure status] 
)

**Comment by otykier** [comment]
This doesn't seem to be a Tabular Editor-specific issue. The error message originates from Analysis Services. You can confirm this by trying to add a calc group with the same expression using SSMS (as a TMSL script - use Tabular Editor to generate the script on the model where you already added the calc group). If it is indeed an Analysis Services error, you should contact Microsoft support.

**Comment by kjoebie** [comment]
You are correct. I executed a TMSL-script with a new calculation group and the measure and it fails with the same error message. I'll file a bug to MS.

Thanks!
