### ISSUE TITLE
IgnoreSourceColumnAdded as part of CLI execution

### ISSUE THREAD

**Issue by justBlindbaek** [TabularEditor/TabularEditor#943]
We're in a situation, where we have shared SQL views to multiple tabular models. This way we for instance have DimCustomer defined in one view and used in multiple different tabular models. In some of the models we only use a subset of the available columns. I have then learned that I can set the TabularEditor_IgnoreSourceColumnAdded as a annotation on the table level, but how about doing it on model level as part of execution the schema check through the CLI? Could this be possible?

Or another option could be to set severity on the different out comes of the check like with BPA rules:
- Missing Source Column should give 3 (error)
- Data Type Change should give 2 (warning)
- Source Column Added should give 1 (information)

This is just my recommendation for the severity, but ultimately you should be able to set it at run time or as an annotation on the model level.

**Comment by otykier** [comment]
I'm hesitant to add more configuration/customization in this area, as it requires a lot of documentation and only solves a very small number of use cases. In your case, for example, a simple workaround could be to run a C# script before executing the schema check (this can be done in a single CLI call). The C# script would simply add the TabularEditor_IgnoreSourceColumnAdded annotation to every table of the model:

```csharp
foreach(var table in Model.Tables) table.SetAnnotation("TabularEditor_IgnoreSourceColumnAdded", "1");
```

A word of advice, though: These warnings exist for a reason. When your source expression returns columns that are not imported into the tabular model, you are wasting network bandwidth, which could ultimately hurt your refresh times. For one or two columns, that's probably not important, but if you're only importing a few columns out of many, then you are needlessly transferring a lot of data over the wire... in that case, it would probably be better to use explicit SELECT-statements, or create additional views tailored specifically to each tabular model.

**Comment by justBlindbaek** [comment]
Thank you for the feedback! It's very valuable.
