### ISSUE TITLE
How to add a TablePermission into an existing role?

### ISSUE THREAD

**Issue by djpirra** [TabularEditor/TabularEditor#945]
I was trying to make a script to move a specific tablepermission definition into another table but I cannot seem to be able to add a tablepermission to the existing role.

Any assistance?

Thank you

**Comment by otykier** [comment]
TablePermissions do not exist as separate objects in the object model exposed to the scripting engine.

Instead, roles have a `Dictionary<string, string> RowLevelSecurity` property, which defines the RLS expression across every table. Conversely, there is a `Dictionary<string, string> RowLevelSecurity` property on each table, which is just a convenient way of accessing the RLS expressions for that table, across every role.

```csharp
// Assign RLS expression on role "My Role" from 'Table A' to 'Table B':
var role = Model.Roles["My Role"];
role.RowLevelSecurity["Table B"] = role.RowLevelSecurity["Table A"];

// Assign RLS expression on 'My Table' from "Role A" to "Role B":
var table = Model.Tables["My Table"];
table.RowLevelSecurity["Role B"] = table.RowLevelSecurity["Role A"];
```

Similarly, for object-level security, there is a `Dictionary<string, MetadataPermission> MetadataPermission` on roles, as well as on tables and columns.

Hope this helps!

**Comment by djpirra** [comment]
Hi Daniel.
Thanks for replying.

Actually I would want to copy only one of the tables security within that role.

Example Role A is filtering on two tables but I want to switch the expression on one of them to another table.

Is this possible?

**Comment by djpirra** [comment]
Thanks Daniel, after some experimentation and with these tips I was able to achieve what I needed.

Regards,
LS
