### ISSUE TITLE
Save model.bim backup here - power bi premium per user - xmla endpoint

### ISSUE THREAD

**Issue by jordandakota** [TabularEditor/TabularEditor#948]
!!! Please make sure you're using the latest version of Tabular Editor 2.X before submitting a bug !!!
!!! For Tabular Editor 3 issues, go here -> https://github.com/TabularEditor/TabularEditor3/issues !!!
Using version 2.16.4

**Describe the bug**
Setting a folder location to save model.bim backups on model modification does not save a backup file when connected to a Power BI premium per user workspace.

**To Reproduce**
Go to file > preferences > check save Model.bim backup here > choose either local or network drive and specify folder
Connect directly to a model in a premium per user power bi workspace
Make an edit to the model
Press Save
Note there is no backup_{modelname}_yyyymmddhhmmss.zip file in the specified folder

**Expected behavior**
A backup file backup_{modelname}_yyyymmddhhmmss.zip should be in the folder shortly after pressing Save, following the steps above.

**Observed behavior**
No backup file is produced

**Application specifics**
 - Tabular Editor version 2.16.4
 - Power BI Premium Per User Workspace
 - Model Compatibility Level: 1550

**Additional context**
No additional context

**Comment by otykier** [comment]
This has been fixed in [2.16.5](https://github.com/TabularEditor/TabularEditor/releases/tag/2.16.5). Thanks for reporting!
