### ISSUE TITLE
Error when cloning an Entity Table

### ISSUE THREAD

**Issue by joanteixi** [TabularEditor/TabularEditor#949]
**Describe the bug**
I get a **TomInternalException, An internal error has ocurred**  when try to *clone* an Entity Table, that is, a powerbi.com dataset. 

**To Reproduce**
1. Create a pbit with powerbi Desktop pointing to a Powerbi.com dataset
2. Add a local model: just create a dummy table
3. Open in Tabular Editor
4. Execute: Model.Tables["TABLE_NAME"].Clone()

It's strange, because if you close an open again the PBIT you can see a copy of the table. So internally, before the error is throwed, the table is duplicated and the model is saved. 

**Application specifics**
 - Tabular Editor 2.X version: [e.g. 2.16.5]
 - Semantic Engine used:  Power BI Desktop
 - Model Compatibility Level:  1550

**Additional context**
![image](https://user-images.githubusercontent.com/286098/145787115-938b6709-26d7-4cb2-bcfe-5cbc3bfcaaba.png)

Thanks for your incredible work!

**Comment by otykier** [comment]
This error message does not originate from Tabular Editor, but from the TOM client library provided by Microsoft. Currently, adding/editing/deleting tables in a PBIT or Power BI Desktop model is [not supported by Microsoft](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools#data-modeling-limitations).
