### ISSUE TITLE
Chinese Display Optimization

### ISSUE THREAD

**Issue by jiaopengzi** [TabularEditor/TabularEditor#951]
The current version of Chinese display is very awkward. Can the support for Chinese display be optimized.thanks！

**Comment by otykier** [comment]
Hi @jiaopengzi 
Could you be more specific or provide a few screenshots to display the issue? Is it a matter of increasing font size in the application? Unfortunately, I don't have any experience in writing software that is optimized for Chinese display. Sorry!

**Comment by jiaopengzi** [comment]
I'm sorry, I didn't make this question clear.
this
![image](https://user-images.githubusercontent.com/52224629/151328546-b51cbd01-210c-48b2-8344-d8170f1697f7.png)

**Comment by otykier** [comment]
Thanks for clarifying.

Does it help if you zoom the editor (hold down the CTRL button while scrolling the mouse wheel)?

![zoom-editor-chinese](https://user-images.githubusercontent.com/8976200/151337070-3e049af5-1d3f-4bba-8e53-a02d45f9a10e.gif)

If so, we can provide a default zoom setting, so you do not have to zoom every time (for example, 150% zoom by default).

**Comment by jiaopengzi** [comment]
I know this(hold down the CTRL button while scrolling the mouse wheel)；but 100% too samll，but the current version of Chinese display is very awkward I think。At the moment, it seems to be the only way provide a default zoom setting,150% zoom by default。It would be great if the Chinese font was displayed better.
Finally, thank you very much for your answer.

**Comment by Stivenke** [comment]
Recommendation: Allow users to select different editor fonts and font sizes.
![I4PuFdwmnV](https://user-images.githubusercontent.com/23474403/204985132-00b96dd5-48d4-4838-9f40-5e7a4922c8d4.png)
