### ISSUE TITLE
Save To Folder silently not saving tables named with trailing whitespace

### ISSUE THREAD

**Issue by emondoni-amplifon** [TabularEditor/TabularEditor#952]
Hi,

I've come across the following bug after splitting a .bim into multiple files with the Save To Folder function.

**Describe the bug**
Tables whose name ends with a whitespace are not persisted to the folder structure when using Save To Folder.

**To Reproduce**
1. Open a .bim file containing at least one table with a trailing whitespace in its name
2. Set the serialization options as shown in the screenshots below
3. Go to File --> "Save To Folder..."
4. Save the model to any folder in the file system

_Serialization settings_

![serializationSettings1](https://user-images.githubusercontent.com/96575787/147554413-58e17019-d9d9-4633-9cf8-538f7f1bf379.png)
![serializationSettings2](https://user-images.githubusercontent.com/96575787/147554414-3ff33e5f-3923-497a-8b24-25c6477f2c89.png)

**Expected behavior**
I would expect the model saved to the folder structure to be identical to the initial one. More in detail, I would expect it to contain the exact same number of tables as the initial model, i.e. I would expect folder `tables` in the generated folder structure to contain as many subfolders as there are tables in the model.

**Observed behavior**
Instead, `tables` contains no subfolder for tables whose name ends with a whitespace. For example, our model included a table named "Dummy Sales " which is nowhere to be found in the saved folder structure: as a result, `tables` contains 213 subfolders whereas the model originally contained 214 tables.

Right after saving to folder, the table is still visible in the Tabular Editor UI but there seems to be no way to persist it to the folder structure. As a consequence, the table is irreversibly lost upon closing Tabular Editor: the table is absent from the model when reloading from the folder structure.

Tabular Editor outputs no warning whatsoever that one or more tables are being lost, but references to the missing tables still remain in other parts of the model (e.g. perspectives) which causes the deploy to AAS to fail because of unresolvable references -- this is how I realized something was wrong with the model.

**Application specifics**
 - Tabular Editor 2.X version: 2.16.4 and 2.16.5 (bug affects both)
 - Semantic Engine used: N/A (the model is deployed to Azure Analysis Services but the bug does not involve connecting to the server)
 - Model Compatibility Level: 1500

**Additional context**
The bug is consistent, meaning it happens with all tables with a trailing whitespace independently of whether they were already present in the bim file or they were created after the split. Removing the trailing whitespace from a table makes it reappear in the folder structure.

**Additional screenshots**

_Model loaded from bim file: there are 214 tables_

![bimModel](https://user-images.githubusercontent.com/96575787/147554402-6411ea76-aafe-4f64-b657-79242d860438.png)

_Table 'Dummy Sales ' has a trailing whitespace in its name_

![dummySales](https://user-images.githubusercontent.com/96575787/147554405-47ae2c24-0f0b-4639-879a-3b7baa60e217.png)

_Content of the `tables` folder after saving: no "Dummy Sales " folder, 213 subfolders in total_

![modelSavedToFolder](https://user-images.githubusercontent.com/96575787/147554412-1d85ac52-2f77-4925-8312-c4eb7aa94af0.png)

_'Dummy Sales ' disappears from Tabular Editor upon reloading from folder_

![modelReloadedFromFolder](https://user-images.githubusercontent.com/96575787/147554409-8f38a6a5-0ced-4392-889b-50607547c5fc.png)

**Comment by otykier** [comment]
Interestingly, Windows does not allow folders with trailing whitespace, so this probably triggers the bug somehow. We will see if we can find a solution to this somehow - for example by replacing the trailing whitespace with `%20` like we do for other special characters that are not allowed in the file name.

**Comment by emondoni-amplifon** [comment]
Thank you for the quick feedback @otykier!

**Comment by otykier** [comment]
Fixed in [2.16.6](https://github.com/TabularEditor/TabularEditor/releases/tag/2.16.6). Thanks for reporting!
