### ISSUE TITLE
Login flag not disabling integrated security

### ISSUE THREAD

**Issue by AGSSAS** [TabularEditor/TabularEditor#953]
I want to deploy a tabular database using gitlab ci/cd.  I am trying use the login flag to override the username / password used for the deployment of the database to my SSAS server.

https://docs.tabulareditor.com/te2/Command-line-Options.html

```
 -L / -LOGIN         Disables integrated security when connecting to the server. Specify:
    user                Username (must be a user with admin rights on the server)
    pass                Password

Start-Process -filePath "TabularEditor.exe" -Wait -NoNewWindow -PassThru  -argumentList "database.json   -D mytabularservername mytabulardatabasename -L anyusername anypassword  -O -P -V -E -W"
```

Regardless of what username / password I enter after the -L flag (valid or not), it doesn't seem to make any difference.  As long as I am the logged in user running the powershell script changing the login credentials does nothing.

What I would like to do is be able to enter service credentials to run this as for the CI/CD deployment, but I could just be misunderstanding how this works.  Thanks.

**Comment by otykier** [comment]
That looks like a bug. Could you try to specify the full connection string including username and password as the first parameter after `-D`:

```powershell
Start-Process -filePath "TabularEditor.exe" -Wait -NoNewWindow -PassThru -argumentList `
    'database.json -D "Provider=MSOLAP;Data Source=mytabulardatabasename;User ID=anyusername;Password=anypassword" mytabulardatabasename -O -P -V -E -W'
```

**Comment by AGSSAS** [comment]
I had to modify the arguments slightly because my TabularEditor.exe and database.json currently require longer path names and my database name has a space in it, but after doing this:

```
Start-Process -filePath "C:\Path to exe\TabularEditor.exe" -Wait -NoNewWindow -PassThru -argumentList `
    '"C:\path to database\database.json" -D "Provider=MSOLAP;Data Source=mytabulardatabasename;User ID=anyusername;Password=anypassword" "mytabulardatabasename" -O -P -V -E -W'
```

I'm still seeing the same result.  As long as the powershell user running the script has access to the tabular database then the username/password are being ignored and can be invalid.  It seems totally dependent on the credentials of the executing user from what I'm able to see.

**Comment by otykier** [comment]
Sorry, I made a typo in the command. The connection string should look like this:

```
Provider=MSOLAP;Data Source=mytabularservername;User ID=anyusername;Password=anypassword
```

By the way - how do you conclude that Tabular Editor is connecting using the credentials of the user running the PowerShell script? That should definitely not be the case when using the connection string shown above.

**Comment by AGSSAS** [comment]
Thanks, I actually ran the connection with the tabular server name in the full connection string and not the database name, I didn't notice that either.

The reason I think Tabular Editor is connecting using the windows credentials of the user running the PowerShell script is because these are the scenarios I've tried.

- Run tabular model deployment from powershell where user running script has access to tabular server but username / password in connection string are incorrect (**deployment successful**)
- Run tabular model deployment from powershell where user running script does not have access to tabular server but username / password in connection string are correct (**deployment unsuccessful**)

I could definitely be doing something wrong here and am going to have someone else look at this with me, but that's what I'm seeing so far.

**Comment by otykier** [comment]
That doesn't really make any sense. The connection string is passed as-is to the TOM client library that connects to Analysis Services. Which version of Tabular Editor are you using and which version of SSAS? Maybe if the connection string is somehow malformed or invalid TOM falls back to integrated security, but I have never seen that happen before.

**Comment by AGSSAS** [comment]
Here's what I see when I deploy.  The aaaa username doesn't exist as a user so that username / password combo are incorrect.  Even if I use a valid user with an incorrect password I get the same result.

Tabular Editor is 2.16.5
SSAS is 2019

![sample deploy](https://user-images.githubusercontent.com/96793224/148076869-32a99724-b67d-44a3-a31b-465ab730d06f.jpg)

Am I calling something wrong in the command line?

**Comment by otykier** [comment]
Okay, I've looked into it a little more. I'm not sure if this is a bug or by design in the AMO/TOM client library used by Tabular Editor, but it seems to completely ignore explicit credentials when connecting to an SSAS instance - at least when I test it locally on my machine, which is not connected to any domain controllers. Interestingly, when connecting to Azure AS or Power BI, specifying credentials in the connection string or using the `-L` switch, is the **only** way to deploy when using the CLI. And I'm like 80% sure that it works fine against SSAS on a domain-joined network as well (or maybe a recent update to AMO/TOM has broken this functionality - in any case, I'll report it to Microsoft).

In your case, as a workaround, consider using the `-Credential` parameter of [Start-Process](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-7.2#parameters) to run TabularEditor.exe under the context of a user who has permission to deploy to SSAS.

**Comment by AGSSAS** [comment]
Great, thank you for looking into this.  In my case I ran the CI / CD job runner as user with permission to deploy to SSAS which is essentially the same thing as you suggested, and that worked.  Thanks for making this great tool!
