### ISSUE TITLE
Setting model permission for a role using scripting

### ISSUE THREAD

**Issue by evaverbeke** [TabularEditor/TabularEditor#954]
Hi,

I'm trying to create a new role using a script, setting the model permission for the role, and add a windows user. So far, I've been able to create the role, and add the user, but I haven't succeeded in setting the model permission. I've tried the following:

  ```
var newRole = Model.AddRole("Admin_");
newRole.ModelPermission = "Administrator";
newRole.AddWindowsMember("Admin"); 
```

I think the newRole.ModelPermission is the correct attribute, since the following

```
foreach(var role in Selected.Roles) {
    Output(role.ModelPermission);
}
```

returns the correct permission that I set manually.

How can I set this property? With other objects, setting a property is usually done the way I tried (object.Property = <something>).

Does an overview of possible attributes and how to set them, functions, etc. exist, apart from [https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.modelrole?view=analysisservices-dotnet](url)?

Many thanks!
Best regards,
Eva

**Comment by otykier** [comment]
Hi Eva,
Try this:

```csharp
var newRole = Model.AddRole("Admin_");
newRole.ModelPermission = ModelPermission.Administrator;
newRole.AddWindowsMember("Admin");
```

The [ModelRole.ModelPermission](https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.modelrole.modelpermission?view=analysisservices-dotnet) property is an [enum type](https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.modelpermission?view=analysisservices-dotnet).

**Comment by evaverbeke** [comment]
Hi Daniel,

Thanks, that works like a charm! I didn't realise it was an enum type, I only found the first page you referenced, which doesn't make a note of it being an enum type.

Best,
Eva
