### ISSUE TITLE
Script to update metadata before processing the model

### ISSUE THREAD

**Issue by oskaracier** [TabularEditor/TabularEditor#960]
**What are you trying to achieve?**
I have a few tables in my data model where the list of columns change quite often. The model is processed every night and each time a column has disappeared in the source the process fails.  

I would like to create a script that before processing these tables checks and if necessary updates the metadata to reflect the source.
The scripting possibilities in Tabular Editor seems to be very powerful, but I am new to it so any help would be very appreciated!

**Comment by otykier** [comment]
I'm afraid we currently don't have a good way of updating column metadata through scripts. The issue is that you might want to react to certain changes in different ways: For example, if a column is renamed from "FlagHasChildren" to "Has Children" in the data source, do you want to treat that as a column removal + column addition, or a column rename? If we simply regard it as a column removal + column addition we may be breaking DAX code that refers to the column.

Assuming your data source is a SQL server, and you're using an OLE DB provider string in your tabular model to connect to the source, you can use something like the following code to connect to the source and retrieve the column metadata. Then you'd still need some code to compare the retrieved column metadata with that in the tabular model table, to determine how column removals, additions, etc. should be handled. But hopefully this can get you started:

```csharp
using System.Data.OleDb;

// We use this structure to translate .NET data types obtained by the OLE DB provider, to Analysis Services data types:
var dataTypeMapping =
    new Dictionary<Type, DataType>() {
        { typeof(string), DataType.String },
        { typeof(char), DataType.String },
        { typeof(byte), DataType.Int64 },
        { typeof(sbyte), DataType.Int64 },
        { typeof(short), DataType.Int64 },
        { typeof(ushort), DataType.Int64 },
        { typeof(int), DataType.Int64 },
        { typeof(uint), DataType.Int64 },
        { typeof(long), DataType.Int64 },
        { typeof(ulong), DataType.Int64 },
        { typeof(float), DataType.Double },
        { typeof(double), DataType.Double },
        { typeof(decimal), DataType.Decimal },
        { typeof(bool), DataType.Boolean },
        { typeof(DateTime), DataType.DateTime },
        { typeof(byte[]), DataType.Binary },
        { typeof(object), DataType.Variant }
    };

// Loop through all tables in the model:
foreach(var table in Model.Tables)
{
    var partition = table.Partitions.FirstOrDefault();
    if(partition == null || partition.SourceType != PartitionSourceType.Query) continue;
    
    // Code below is only executed for tables that have at least one Query-type partition:
    
    // TODO: Here, you may want to specify a different connection string, if the one used by the partition DataSource
    // does not include the necessary credentials/authentication mechanism.
    var connectionString = (partition.DataSource as ProviderDataSource).ConnectionString;
    using (var conn = new OleDbConnection(connectionString))
    {
        // Connect to the SQL source and get the schema of the partition query:
        conn.Open();
        var cmd = new OleDbCommand(partition.Query, conn);
        var rdr = cmd.ExecuteReader(System.Data.CommandBehavior.SchemaOnly);
        var schema = rdr.GetSchemaTable();

        // Todo: Write code that determines when to add/remove columns from the table. For example, the code below
        // adds columns that do not already exist (by their SourceColumn property):

        // Loop through every row in the schema table (which corresponds to a column in the partition query):
        foreach(System.Data.DataRow row in schema.Rows)
        {
            var name = (string)row["ColumnName"];
            var type = (Type)row["DataType"];
            
            if(!table.Columns.OfType<DataColumn>().Any(c => c.SourceColumn.EqualsI(name)))
            {
                var col = table.AddDataColumn(name, name);
                col.DataType = dataTypeMapping.ContainsKey(type) ? dataTypeMapping[type] : DataType.Automatic;
            }
        }
    }
}
```

**Comment by oskaracier** [comment]
Thank you very much! 
Because of how the data is structured I know that names will not change and there is also no DAX code referencing the columns. Possible events are columns being removed in the source and should then be removed before processing or columns added in the source and they should then be added in the model.
