### ISSUE TITLE
EULA of Tabular 2.x

### ISSUE THREAD

**Issue by aicirtap027** [TabularEditor/TabularEditor#964]
!!! For Tabular Editor 3 questions, go here --> https://github.com/TabularEditor/TabularEditor3/issues !!!

Hello, 
I need some help to know where is the EULA for tablular editor 2.x, I am proposing this external tool as part of our Power BI since it has a big help on creating calculations but they need the EULA to approve this tool as part of our Power BI please help me on my problem. I tried searching for it but the only EULA available is for the tabular editor 3 only but the cost is too much, I really want to have this tabular editor 2.x since it has a big help on my creation of dashboards. Please help. Thank you so much.

**Comment by otykier** [comment]
There is no EULA for Tabular Editor 2.c. It is open-source software governed by this [MIT license](https://github.com/TabularEditor/TabularEditor/blob/master/LICENSE).
