### ISSUE TITLE
C # script automatically write DAX problems: retained a newline; Please help

### ISSUE THREAD

**Issue by jiaopengzi** [TabularEditor/TabularEditor#967]
The official document [https://docs.tabulareditor.com/te2/Useful-script-snippets.html#generating-measures-from-a-file](https://docs.tabulareditor.com/te2/Useful-script-snippets.html#generating-measures-from-a-file) 

Step by step according to do;measure are set up automatically.
***But newline is saved, which leads to the DAX not work properly.***
What should I do.And Single-line DAX is correct, multi-line retained a newline character.
The following figure shows
![image](https://user-images.githubusercontent.com/52224629/155098556-3c0a5471-4300-41e1-95b1-020145fd8993.png)
![image](https://user-images.githubusercontent.com/52224629/155098041-92cbbc6f-6475-4c23-9281-ccff26bb0544.png)
![image](https://user-images.githubusercontent.com/52224629/155098161-7729fed8-18d7-4195-8678-dd308b75ffdf.png)

```
//var tsv = ExportProperties(Model.AllMeasures);
//SaveFile(@"D:\DESKTOP\TEST\TEST01.tsv", tsv);

var targetTable = Model.Tables["tb1"];  // Name of the table that should hold the measures
var measureMetadata = ReadFile(@"D:\DESKTOP\TEST\TEST01.tsv");   // c:\Test\MyMeasures.tsv is a tab-separated file with a header row and 3 columns: Name, Description, Expression

// Delete all measures from the target table that have an "AUTOGEN" annotation with the value "1":
foreach(var m in targetTable.Measures.Where(m => m.GetAnnotation("AUTOGEN") == "1").ToList())
{
    m.Delete();
}

// Split the file into rows by CR and LF characters:
var tsvRows = measureMetadata.Split(new[] {'\r','\n'},StringSplitOptions.RemoveEmptyEntries);

// Loop through all rows but skip the first one:
foreach(var row in tsvRows.Skip(1))
{
    var tsvColumns = row.Split('\t');     // Assume file uses tabs as column separator
    var name = tsvColumns[1];             // 1st column contains measure name
    //var description = tsvColumns[1];      // 2nd column contains measure description
    var expression = tsvColumns[4];       // 3rd column contains measure expression

    // This assumes that the model does not already contain a measure with the same name (if it does, the new measure will get a numeric suffix):
    var measure = targetTable.AddMeasure(name);
    //measure.Description = description;
    measure.Expression = expression;
    measure.SetAnnotation("AUTOGEN", "1");  // Set a special annotation on the measure, so we can find it and delete it the next time the script is executed.
}
```

**Comment by otykier** [comment]
Hi @jiaopengzi 
Use `.Replace("\\n", "\n")` when assigning the expression to the measure, to convert the literal characters `\` and `n` to actual linebreaks:

```csharp
    ...
    measure.Expression = expression.Replace("\\n", "\n");
    measure.SetAnnotation("AUTOGEN", "1");  // Set a special annotation on the measure, so we can find it and delete it the next time the script is executed.
}
```

Hope this helps!

**Comment by jiaopengzi** [comment]
> 嗨@jiaopengzi在将表达式分配给度量时 使用，`.Replace("\\n", "\n")`以将文字字符转换为实际的换行符：`\``n`
> 
> ```cs
>     ...
>     测量。表达式 = 表达式。替换（“ \\ n ”，“ \n ”）；
>     测量。SetAnnotation ( " AUTOGEN " , " 1 " );  //在度量上设置一个特殊的注解，这样我们可以在下次执行脚本时找到并删除它。
> }
> ```
> 
> 希望这可以帮助！

It is the perfect solution.

Thank you very much.

**Comment by jiaopengzi** [comment]
> Hi @jiaopengzi Use `.Replace("\\n", "\n")` when assigning the expression to the measure, to convert the literal characters `\` and `n` to actual linebreaks:
> 
> ```cs
>     ...
>     measure.Expression = expression.Replace("\\n", "\n");
>     measure.SetAnnotation("AUTOGEN", "1");  // Set a special annotation on the measure, so we can find it and delete it the next time the script is executed.
> }
> ```
> 
> Hope this helps!

It is the perfect solution.

Thank you very much.
