### ISSUE TITLE
Very slow during measures creation/adjustment

### ISSUE THREAD

**Issue by SteveFringe** [TabularEditor/TabularEditor#968]
Hi, 
Recently i've started experiencing very slow performance of Tabular editor during operations with measures.
Example: i click create measure, give it a name, click enter and have to wait for a long time. I'm attaching a video of it (i clicked "Enter" at around 7 seconds into the video, then it's waiting time until almost the end of the video).
I'm using the latest 2.16.5, PBI desktop the latest version. 
PBI file is around 400 mb. Created 2 days ago. 
Thanks in advance.

https://user-images.githubusercontent.com/72388338/155309972-3f50501c-37c4-430f-b30b-04414ec95a79.mp4

**Comment by otykier** [comment]
That's weird. Could you export and send me a .pbit (Power BI Template) of the file you're working on? daniel@tabulareditor.com

**Comment by otykier** [comment]
Hi @SteveFringe 
Thanks for sending the file. I wasn't able to reproduce the issue immediately, but then I tried loading the Power BI Best Practice Rules created by @m-kovalsky, and I noticed that the Best Practice Analyzer took a very long time to complete a scan.

In particular, the rule **No two measures should have the same definition** is very slow to evaluate, when a model contains many measures. After disabling this rule (see screenshot below), a BPA scan now only takes 1-2 seconds, and there were no longer any slowdowns in the application itself.

![image](https://user-images.githubusercontent.com/8976200/155325778-a1034a44-b9ce-46e8-99a5-75b2f2755ce7.png)

Could you confirm if you are using these rules, and if disabling them improves the performance in your case?

**Comment by SteveFringe** [comment]
Just a kind of magic! Thanks a lot Daniel for a super quick reaction. it worked. Now i can continue using the tabular editor) 
Thanks a lot for your support!

**Comment by m-kovalsky** [comment]
Thanks to @otykier's advice, we removed this rule from the Best Practice Rules (as of version 1.1). The latest version of the rules is v1.2.1.

**Comment by otykier** [comment]
Thanks @m-kovalsky!
