### ISSUE TITLE
Date Format example for Format String properties shows incorrectly

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor#969]
**Describe the bug**
The example shown after entering a format string property for a date column shows incorrectly.

**To Reproduce**
1. Go to a date column in the model
2. Enter 'mm/dd/yyyy' to the Format String property
3. It shows this:

![image](https://user-images.githubusercontent.com/29556918/155343169-0e884e6e-4fa3-42d8-b6a2-19c96bdfd9a9.png)

**Expected behavior**
I tried a variety of date formats and many showed incorrectly in the example. Note, this seems to work fine in TE3.

**Observed behavior**
It appears to be taking the hour and tens of minutes instead of the month.

**Application specifics**
 - Tabular Editor 2.X version: 2.16.5

**Comment by zenzeinet** [comment]
Month is MM, case se sensitive

**Comment by otykier** [comment]
Fixed in [2.16.6](https://github.com/TabularEditor/TabularEditor/releases/tag/2.16.6). Thanks for reporting!
