### ISSUE TITLE
How to elegantly export the DAX of the calculation group

### ISSUE THREAD

**Issue by jiaopengzi** [TabularEditor/TabularEditor#976]
hi @otykier
I came again.
The official documentation has a script for exporting measure, which is very easy to use.
I want to export the DAX of the calculation group.
Now I create a new measure for the calculation group DAX and export it.
**Is there a more elegant way to export the DAX of the calculation group?**
Thank you very much.

code：
```

var tablename0="G03_P60_DWMQHY";//Calculation group table name.
var file0=@"D:\desktop\cgi0.tsv";//TSV absolute path to export.
var tablename1=tablename0+"1";
    //See if there are tables with the same name in the model and delete them if there are.
foreach(var t0 in Model.Tables)
{
    var tn0 = t0.Name;
    if (tn0 == tablename1)
    Model.Tables[tablename1].Delete();
}

Model.AddCalculationGroup(tablename1);
var targetTable = (Model.Tables[tablename1] as CalculationGroupTable);
foreach(var ci in (Model.Tables[tablename0] as CalculationGroupTable).CalculationItems)
{
    var measure = targetTable.AddMeasure(ci.Name);//Create a new measure of the same name.
    measure.Expression = ci.Expression;//Write the DAX of the calculation group for subsequent export.。
}
    
SaveFile(file0, ExportProperties(Model.Tables[tablename1].Measures));//Used to measure value saving for local overuse.

//Manually clear the table tablename1
```
![image](https://user-images.githubusercontent.com/52224629/159146663-de8c0e6f-c8f9-457f-9eb6-7fb2bbb20313.png)

**Comment by otykier** [comment]
Hi @jiaopengzi 
Unfortunately, the `ExportProperties` method does not support calculation items currently.

Instead, you can use something like below:

```csharp
var calcItemsInfo = 
    "Name\tExpression\tFormatStringExpression\tOrdinal\tDescription\n" +
    string.Join("\n", targetTable.CalculationItems.Select(ci =>
        ci.Name + "\t" + 
        ci.Expression + "\t" + 
        ci.FormatStringExpression + "\t" + 
        ci.Ordinal + "\t" + 
        ci.Description));
SaveFile(file1, calcItemsInfo);
```

**Comment by jiaopengzi** [comment]
get it. Thank you very much.

**Comment by otykier** [comment]
Hi @jiaopengzi 
FYI, v. [2.16.6](https://github.com/TabularEditor/TabularEditor/releases/tag/2.16.6) now lets you use the `ExportProperties` and `ImportProperties` methods for calc groups/calc items.

**Comment by jiaopengzi** [comment]
> Hi @jiaopengzi FYI, v. [2.16.6](https://github.com/TabularEditor/TabularEditor/releases/tag/2.16.6) now lets you use the `ExportProperties` and `ImportProperties` methods for calc groups/calc items.

Perfect.

**Comment by bdarbonneau** [comment]
An example, for those who are looking for a code snippet:
`var mycalcgroup = Selected.Table as CalculationGroupTable ;
string _TableName = mycalcgroup.Name.Replace(" ", "_");
var file0=@"C:\Users\XXX\Downloads\" + _TableName +"CalcItems.tsv";//TSV absolute path to export.
SaveFile(file0, ExportProperties(mycalcgroup.CalculationItems, "Ordinal,Name,Expression,FormatStringExpression"));
`
