### ISSUE TITLE
Save to folder: cannot save column named "aux", "con" and other reserved windows filenames 

### ISSUE THREAD

**Issue by zenzeinet** [TabularEditor/TabularEditor#978]
**Describe the bug**
Save to folder: cannot save to folder column named "aux"  or other reserved windows filenames

**To Reproduce**
Create a model with a table that has a column called "aux". Try to save it as a model. It gives an unhandled exception.
The model stops being saved and an incomplete folder structure is saved, stopping wherever the "aux" column in the .bim file exists

**Expected behavior**
Properly saving to folder.

**root cause** (NEW! :-D)
Of course, the root cause of this is due to the column being called the same as a windows reserved name, the infamous "CON" "AUX" and others . Just try, you cannot have on windows a file called aux.json  , neither a file called con.json  . I can't believe this is still a thing in 2022... but it still is.

As per: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN
"CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended."

I don't know what workaround to use there - probably escaping all these if they are a column name. Working names include "[aux].json" , _aux.json , using % simbols, etc. 

**Observed behavior**

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabularEditor.UI.UIController.HandleError(String operationTitle, Exception e)
   at TabularEditor.UI.UIController.File_SaveAs_ToFolder()
   at TabularEditor.FormMain.actSaveToFolder_Execute(Object sender, EventArgs e)
   at Crad.Windows.Forms.Actions.Action.OnExecute(EventArgs e)
   at TabularEditor.UI.UIModelAction.OnExecute(EventArgs e)
....

**Application specifics**
 - Tabular Editor 2.X version: 2.16.5
 - Semantic Engine used:  SSAS 2019
 - Model Compatibility Level:  1500,

**Additional context**
This simple .bim file triggers the bug when trying to save as Folder:
{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "dataSources": [
      {
        "name": "New Provider Data Source",
        "impersonationMode": "impersonateServiceAccount"
      }
    ],
    "tables": [
      {
        "name": "Table1",
        "columns": [
          {
            "name": "aux",
            "dataType": "string"
          }
        ],
        "partitions": [
          {
            "name": "New Table",
            "source": {
              "type": "query",
              "dataSource": "New Provider Data Source"
            }
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Calculation Items\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Translations\"]}"
      }
    ]
  }
}

**Comment by otykier** [comment]
What an insane bug! Thanks for reporting. We’ll find a solution (I’m partial to adding an underscore in front of the name).

**Comment by kurtbuhler** [comment]
I also experienced this today with a table that had the column name "CON".
After removing the column, I could save to folder without issue.

![Cannot-Save-folder](https://user-images.githubusercontent.com/46317235/161375648-6d3f94c3-40b4-4f88-b40b-ba632414eb2d.png)

![DND-Dataset-CON](https://user-images.githubusercontent.com/46317235/161375706-9704d521-465b-4aee-83a7-8a07c8bb1f6f.png)

**Comment by otykier** [comment]
Fixed in [2.16.6](https://github.com/TabularEditor/TabularEditor/releases/tag/2.16.6). Thanks for reporting!
