### ISSUE TITLE
Use Placeholder after deploy switches for role member, role, partition like ConnectionString

### ISSUE THREAD

**Issue by duanzy47** [TabularEditor/TabularEditor#982]
Hello Daniel,

I'm configuring the Azure Devops pipelines to deploy different Tabular models for different clients.

I followed step by step from your blog https://docs.tabulareditor.com/te2/Master-model-pattern.html, great job !

However, I found that it is not possible to use the placeholder like the -C switch for the other objects:
role member, role and partition.

In a scenario of Continuous Integration, it will be very useful to inject a model-specific variable to the C# script from the pipeline instead of hardcoding in script. 

Will you consider the implementation of  `Placeholder replacing` in other switches like for -C ?

Thanks in advance ;)

**Comment by otykier** [comment]
The placeholder feature is obsolete - we don't have any plans of using this pattern in other switches. A more flexible approach is to use a C# script with the `-S` switch, and then within the script read the values from environment variables (which you can directly assign in your DevOps pipeline):

For example, assume that you map a variable called "AdminGroupName" in your DevOps pipeline, and you want the value of this variable to be added as an external role member to a specific role within the model. You would use the following script:

```csharp
var adGroupMemberName = Environment.GetEnvironmentVariable("AdminGroupName");
Model.Roles["Admins"].AddExternalRoleMember(adGroupMemberName);
```

If this script is stored as "MyScript.cs", you simply pass it in following the `-S` switch. Keep in mind you can execute multiple scripts by specifying their file names separately after the `-S` switch - they'll be executed in the order they are provided in the command line.

**Comment by duanzy47** [comment]
Thank you so much for the help!
