### ISSUE TITLE
When deploying an existing model with a new name, you can't uncheck "Deploy Table Partitions" 

### ISSUE THREAD

**Issue by StarSchemer** [TabularEditor/TabularEditor#984]
TE 2.16.5

1. If I choose to deploy the model with the pre-existing name:

![CHOOSE_DESTINATION_SERVER](https://user-images.githubusercontent.com/80753308/162922125-60307c33-0cb8-452b-99f7-080f1705e7ef.JPG)

2, In the deployment options I can select to not deploy the table partitions.

![DEPLOYMENT_OPTIONS](https://user-images.githubusercontent.com/80753308/162922392-0d8f769b-20ba-4156-88d2-df534f2038ae.JPG)

3. If I rename the database:

![RENAME_DATABASE](https://user-images.githubusercontent.com/80753308/162922480-cf89409d-ceb6-4304-92f4-0ca4e9fe6b8c.JPG)

4. The option to not deploy the partitions is unavailable.

![OPTIONS_GREYED_OUT](https://user-images.githubusercontent.com/80753308/162922560-f52a6411-c3e3-4647-aec1-0cef316c8802.JPG)

I have so far been unable to find a workaround.

Jamie

**Comment by otykier** [comment]
This is by design. Deploying the model with a new name means that you are deploying it as a new database, without overwriting an existing one. Since all tables must have at least 1 partition, it does not make sense to deploy a new database without partitions.
