### ISSUE TITLE
Publish Datamodel to PowerBI Pro Workspace?

### ISSUE THREAD

**Issue by Markus531** [TabularEditor/TabularEditor#990]
I am trying to publish my Tabular Model created with Tabular Editor 2.16.5 to an empty PowerBI Pro Workspace and I am getting the error message: "Initial catalog property is required in order to connect to Power BI Pro Workspaces". 
My connect string is: powerbi://api.powerbi.com/v1.0/myorg/ProWorkspacename
If I try to publish same model to a premium Workspace, everything works fine.

I tried to change my connection string to add an initial catalog like:
powerbi://api.powerbi.com/v1.0/myorg/ProWorkspacename;initial catalog=DSName
But then I am getting the error message "PowerBI Entity not found" (the Workspace is empty, I am not sure which initial catalog is needed)

Is it possible to publish to a pro Workspace and what are the steps?
Thanks for help!

**Comment by otykier** [comment]
Hi @Markus531 
It's unfortunately not possible to use 3rd party tools with Power BI Pro. You need Power BI Premium or Premium-per-user in order to [enable the XMLA endpoint](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-connect-tools).
